palantir/tslint

Gruntfile.js
lib/tslint.d.ts
src/language/walker/syntaxWalker.ts
src/rules/variableNameRule.ts

- also fix some compilation / linting errors in the source

Migrate variable name rule to 1.4

---

README.md

markdown rendering of this block got broken

Fix whitespace in readme

---

src/language/utils.ts

As long as you remove the linting step from grunt all tests should pass on Windows now

Normalize windows paths

---

src/rules/noDuplicateVariableRule.ts
test/files/rules/duplicate-variable.test.ts
test/rules/noDuplicateVariableRuleTests.ts

Now differentiates between lets and vars

Fixes #295

---

README.md

This also updates the other two badges to use svg instead of png

Add appveyor build status badge

---

README.md

Updated library example - making it easier for people who are new to this.

Improved README.md library example to make it easier for beginners

---

lib/tslint.d.ts
src/enableDisableRules.ts
src/language/walker/skipableTokenAwareRuleWalker.ts
src/language/walker/skippableTokenAwareRuleWalker.ts
src/rules/commentFormatRule.ts
src/rules/jsdocFormatRule.ts
src/rules/noConsecutiveBlankLinesRule.ts
src/rules/noTrailingWhitespaceRule.ts
src/rules/whitespaceRule.ts
src/tslint.ts
test/files/rules/enabledisable.test.ts
test/files/rules/jsdoc.test.ts
test/files/rules/whitespace.test.ts
test/rules/jsdocFormatRuleTests.ts
test/rules/noTrailingWhitespaceRuleTests.ts

Fixes #357, #349, #332, and possibly a couple others I missed

Fix things that walk tokens to properly handle templates, etc.

---

src/rules/noDuplicateVariableRule.ts
test/files/rules/duplicate-variable.test.ts

Skip method signatures and catch clause variable declarations

Fixes #372 -- remove additonal false positives

---

.jscsrc
Gruntfile.js
package.json
test/files/formatters/simple.js

Add JSCS to build

---

lib/tslint.d.ts
src/language/walker/syntaxWalker.ts
src/rules/noUnusedVariableRule.ts
test/files/rules/nounusedvariable-class.test.ts
test/files/rules/nounusedvariable-imports.test.ts
test/rules/noUnusedVariableRuleTests.ts

Add destructuring syntax & support for no-unused-variable imports

---

src/rules/noUseBeforeDeclareRule.ts
test/files/rules/nousebeforedeclare.test.ts
test/rules/noUseBeforeDeclareRuleTests.ts

Add destructuring & namespace import syntax support to no-use-before-declare rule

---

src/rules/variableNameRule.ts
test/files/rules/varname.test.ts
test/helper.ts
test/rules/variableNameRuleTests.ts

Enhance variable-name rule to support parameter names & destructuring

---

lib/tslint.d.ts
src/language/walker/syntaxWalker.ts
src/rules/curlyRule.ts
test/files/rules/curly.test.ts
test/rules/curlyRuleTests.ts

Add for-of loop checking to curly brace rule

---

src/rules/noDuplicateKeyRule.ts
test/files/rules/dupkey.test.ts
test/rules/noDuplicateKeyRuleTests.ts

- also use `const` instead of `var`

Add tests for computed properties in no-duplicate-key rule

---

README.md
src/rules/whitespaceRule.ts
test/files/rules/whitespace.test.ts
test/rules/whitespaceRuleTests.ts

Update whitespace rule to support ES6 module syntax

---

README.md
docs/sample.tslint.json
src/rules/noVarKeywordRule.ts
src/rules/tsconfig.json
test/files/rules/novarkeyword.test.ts
test/rules/noVarKeywordRuleTests.ts

Added no-var-keyword rule.
I couldn't think of a better name for this rule so if you have a better name I will change it :)
fix #378
Feel free to close this PR if this isn't the way you want it :)
Btw: I'm currently on vacation so feedback might take till around Sunday :)

No var keyword rule

---

src/rules/noDuplicateVariableRule.ts
test/files/rules/no-duplicate-variable.test.ts
test/rules/noDuplicateVariableRuleTests.ts

looks like we get nested binding patterns for free!

Add destructuring support to no-duplicate-variable rule

---

test/files/rules/noAny.test.ts
test/files/rules/noany.test.ts
test/rules/noAnyRuleTests.ts

Add more tests for the <no-any> rule

---

src/rules/noUnusedVariableRule.ts
test/files/rules/nounusedvariable-function.test.ts

fix export default function error in no-unused-variable

---

lib/tslint.d.ts
src/tslint.ts

Declare 'tslint' module

---

src/configuration.ts
src/rules/indentRule.ts
src/rules/noDuplicateVariableRule.ts
src/rules/noShadowedVariableRule.ts
src/rules/sortObjectLiteralKeysRule.ts
src/tslint-cli.ts
test/rules/indentRuleTests.ts
tslint.json

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/470)

turn on comment rule in TSLint and fix comments

---

CHANGELOG.md
package.json
src/tslint.ts

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/473)

2.3.1-beta

---

src/rules/noVarKeywordRule.ts

See minor edit..
Its confusing!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/476)

Confusing message for forbidden var statement!

---

README.md
src/tslint-cli.ts
test/check-bin.sh

Resolves #438 
I also cleaned up and added a relevant test to test/check-bin.sh.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/462)

Remove -f option from CLI

---

npm-shrinkwrap.json
package.json

- Fix some NPM warn errors about peerDependencies
- Fix license format (see https://spdx.org/licenses/)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/484)

Update npm dependencies, fix build on master

---

.travis.yml

Resolve #475
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/480)

Use node 0.12 in TravisCI

---

lib/tslint.d.ts
src/language/utils.ts
tslint.json

fixes #499
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/501)

Use no-shadowed-variable rule

---

CHANGELOG.md
Gruntfile.js
npm-shrinkwrap.json
package.json
src/language/languageServiceHost.ts
src/tsconfig.json
src/tslint.ts
test/tsconfig.json
typings/typescriptServices.d.ts
typings/typescriptServicesScanner.d.ts

- Update typings
- Fix tsconfig.json build output paths
- Add "concat-and-test" grunt task for running tests after building from an editor like Atom
- Bump to v2.4.0
- Use TS v1.5.3 release
- Update changelog
- Update npm-shrinkwrap.json
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/508)

Release v2.4.0

---

README.md
docs/sample.tslint.json
lib/tslint.d.ts
src/language/utils.ts
src/rules/noInternalModuleRule.ts
src/rules/tsconfig.json
test/files/rules/nointernalmodule.test.ts
test/rules/noInternalModuleTests.ts
test/tsconfig.json

implement #513
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/517)

Add no-internal-module rule

---

lib/tslint.d.ts
src/language/walker/skippableTokenAwareRuleWalker.ts
src/language/walker/syntaxWalker.ts
src/rules/whitespaceRule.ts
test/files/tsx/react.test.tsx
test/tsxTests.ts

Fixes #551.
Also some small refactoring.

Better tsx support

---

CHANGELOG.md
README.md
package.json
src/tslint.ts

- Fixes #536
- Add docs about "next" distribution to README

Prepare Release v2.5.0-dev.1

---

package.json

This will allow `tsd` 0.6 to discover the file

Add TypeScript definition

---

lib/tslint.d.ts
src/language/walker/syntaxWalker.ts
src/rules/noUnusedVariableRule.ts
src/rules/whitespaceRule.ts
test/files/tsx/react.test.tsx
test/tsxTests.ts
typings/typescriptServices.d.ts

also update TS compiler to latest

Fix some issues in linting JSX

---

lib/tslint.d.ts
src/formatterLoader.ts
src/ruleLoader.ts
src/rules/labelPositionRule.ts
src/rules/noShadowedVariableRule.ts
src/rules/noSwitchCaseFallThroughRule.ts
src/rules/noVarKeywordRule.ts
src/tslint-cli.ts
test/ruleDisableEnableTests.ts
tslint.json

- Fixes #505
- Also rename some variables to better adhere to variable-name rule

Turn on no-unused-variable rule

---

README.md
src/tslint-cli.ts

Add usage info for tslint binary

---

src/rules/memberOrderingRule.ts

Small refactoring of member-ordering rule

---

src/rules/forinRule.ts
src/rules/oneLineRule.ts
src/tslint.ts
tslint.json

Turn on member-ordering rule

---

src/language/utils.ts
src/rules/tsconfig.json
src/tsconfig.json
typings/typescriptServices.d.ts
typings/typescriptServicesScanner.d.ts

Use latest compiler

---

package.json

This reverts commit c510503fcdf87efe60bfba0e0b63e422b4a86f66.
Fixes #606.

Revert "Add TypeScript definition"

---

src/rules/noInternalModuleRule.ts
test/files/rules/nointernalmodule.test.ts
test/rules/noInternalModuleTests.ts

Tests and improvement for no-internal-module rule on next branch

---

README.md
docs/sample.tslint.json

Add documentation for sort-object-literal-keys rule

---

src/rules/oneLineRule.ts
test/files/rules/oneline.test.ts
test/rules/oneLineRuleTests.ts

Fix one-line rule bug

---

src/rules/noUseBeforeDeclareRule.ts
test/files/rules/nousebeforedeclare.test.ts

Fix bug that caused tslint to crash with object destructuring

---

src/language/languageServiceHost.ts
test/files/rules/nounusedvariable-falsepositives.test.ts
test/rules/noUnusedVariableRuleTests.ts

See discussion of https://github.com/Microsoft/TypeScript/issues/4560
Fixes https://github.com/palantir/tslint/issues/570
Fixes #613

Fix bug with false positives in unused variable rule and other problems when using language services

---

lib/tslint.d.ts
src/language/walker/syntaxWalker.ts
src/rules/noShadowedVariableRule.ts
test/files/rules/no-shadowed-variable.test.ts

Don't check parameters in call signatures

---

README.md
lib/tslint.d.ts
src/tslint.ts

Fix typing bug and make Readme clearer

---

src/language/utils.ts

Add deprecation notice to Lint.abstract()

---

src/rules/noUnusedExpressionRule.ts
test/files/rules/unused.expression.test.ts

Yield expressions are valid standalone expressions

---

.travis.yml
appveyor.yml

Update appveyor and travis to build against node 4.1

---

test/files/tsx/react.test.tsx

Add unit test for no-unused-variable false positive

---

src/language/utils.ts

Remove Lint.abstract()

---

src/language/walker/syntaxWalker.ts
src/rules/quotemarkRule.ts

Update quotemark rule to use string literal method

---

src/language/walker/syntaxWalker.ts

Add methods for WithStatement and TypeReference nodes

---

.travis.yml
appveyor.yml

Update appveyor and travis to use node 4.2

---

src/rules/noUseBeforeDeclareRule.ts

See https://github.com/palantir/tslint/issues/583#issuecomment-153128142 and below for relevant discussion

Make sure highlights is not null

---

README.md

Added links to `buzinas/tslint-eslint-rules` and `Microsoft/tslint-microsoft-contrib`.

Fixes #757 - links to community custom rules

---

src/language/utils.ts
src/rules/noShadowedVariableRule.ts
test/files/rules/no-shadowed-variable.test.ts
test/rules/noShadowedVariableRuleTests.ts

not really happy with the getBindingElementVariableDeclaration() but...

Fixes #727

---

CONTRIBUTERS.md

Remove CONTRIBUTERS.md

---

CHANGELOG.md
package.json
src/tslint.ts

Also merge `next` into `master`

Prepare Release v3.2.0

---

src/configuration.ts
src/ruleLoader.ts
test/check-bin.sh
test/config/tslint-custom-rules-with-two-dirs.json
test/files/custom-rules-2/noFail.js

Fix bug where only one directory of custom rules was considered

---

src/rules/labelPositionRule.ts
test/rules/label-position/test.ts.lint

Added for-of statement to the label position rule whitelist.

Labels can be used with for-of statements.

---

src/rules/noStringLiteralRule.ts
test/rules/no-string-literal/test.ts.lint

I think, that this will help in #906

Fix for "Cannot read property 'getText' of undefined" noStringLiteralRule.ts

---

README.md
src/rules/noUnusedVariableRule.ts
test/rules/no-unused-variable/ignore-pattern/react.tsx.lint
test/rules/no-unused-variable/ignore-pattern/tslint.json
test/rules/no-unused-variable/ignore-pattern/var.ts.lint

Add ignore-pattern option to no-unused-variable

---

src/configuration.ts

This is a different approach to issue #1020.

Add deprecation warning.

---

src/tslint-cli.ts

Closes https://github.com/palantir/tslint/issues/915. Very simple, but I've need it for a while :smile:

Exclude globs

---

README.md

Alphabetized the list of supported editors too...
Fixes #1042.

Added Visual Studio to readme's support list

---

README.md
src/tslint-cli.ts

Added --force (-n) option. Fixes #1059

---

src/tslint-cli.ts
test/check-bin.sh
typings/optimist/optimist.d.ts

No alias for --force

---

src/rules/noInternalModuleRule.ts
test/rules/no-internal-module/test.ts.lint

Fix false positive from no-internal-module on global augmentation

---

test/lint.ts

Removed tslint:disable hack in hackfromtest/lint.ts

---

src/rules/noUnusedExpressionRule.ts
test/rules/no-unused-expression/test.ts.lint

Allow directives at the top of a namespace

---

README.md
src/rules/variableNameRule.ts
test/rules/variable-name/allow-pascal-case/test.ts.lint
test/rules/variable-name/allow-pascal-case/tslint.json

Added "allow-pascal-case" to variable-name-rule

---

src/rules/memberOrderingRule.ts
test/rules/member-ordering/method/test.ts.lint

member-ordering: add a check of constructor

---

src/rules/useIsnanRule.ts
test/rules/use-isnan/test.ts.lint

[Issue #1054] use-isnan fixed to ignore assignments to NaN

---

README.md
docs/sample.tslint.json
src/rules/noInvalidThisRule.ts
test/rules/no-invalid-this/enabled/tslint.json

Rename no-invalid-this rule option

---

src/rules/noDefaultExportRule.ts
src/tsconfig.json
test/rules/no-default-export/test.ts.lint
test/rules/no-default-export/tslint.json
test/tsconfig.json

I believe this is all that is required for this rule. open to any suggestions for improvements.
p.s. love the new testing framework!
resolves #1182

adding no-default-export rule

---

README.md
docs/sample.tslint.json
src/rules/newParensRule.ts
src/tsconfig.json
test/rules/new-parens/test.ts.lint
test/rules/new-parens/tslint.json
test/tsconfig.json

Add new-parens rule

---

src/rules/semicolonRule.ts
test/rules/semicolon/always/test.ts.lint
test/rules/semicolon/enabled/test.ts.lint
test/rules/semicolon/never/test.ts.lint

semicolon: check export assignment

---

circle.yml
scripts/npmPublish.sh

Fixes #1165 
(untested as of right now)

CircleCI deployment

---

src/rules/banRule.ts
test/rules/ban/test.ts.lint
test/rules/ban/tslint.json

Ban chained methods

---

src/rules/noDefaultExportRule.ts
test/rules/no-default-export/test.ts.lint

more tests for less common export statements. new code to handle inline class and function declarations (and possibly other inline declarations if any exist).

improved no-default-export rule

---

README.md

member-access: modify docs

---

test/rules/no-unused-variable/default/import.ts.lint

#325 now fixed in typescript

---

README.md

Update README to include more details about tslint.json

---

README.md
docs/sample.tslint.json
src/rules/typedefRule.ts
test/rules/typedef/all/test.ts.lint
test/rules/typedef/all/tslint.json
test/rules/typedef/arrow-call-signature/test.ts.lint
test/rules/typedef/arrow-call-signature/tslint.json
test/rules/typedef/call-signature/test.ts.lint
test/rules/typedef/call-signature/tslint.json

call-signature option of typedef: check arrow function

---

README.md

Fixes #1319 (after I update the docs site as well)

Remove broken link to sample.json

---

src/rules/typedefRule.ts
test/rules/typedef/all/test.ts.lint

Fix null reference bug

---

README.md

Swapped two lines in the readme to sort them alphabetically.

Fix sorting of whitespace rule options

---

Gemfile
_config.yml
circle.yml

This also allows me to build using this new Jekyll CMS I want to try out called [Forestry](https://forestry.io/).

Allow gh-pages to build on CI

---

src/rules/oneLineRule.ts
test/rules/one-line/all/test.ts.lint
test/rules/one-line/none/test.ts.lint

Fix TS 2.0 one-line rule bug

---

src/rules/typedefRule.ts

Update "typedef" rule metadata

---

CHANGELOG.md
package.json
src/configs/latest.ts
src/tslint.ts

v3.15.1 with updated tslint:latest config

---

src/rules/typedefWhitespaceRule.ts
test/rules/typedef-whitespace/both/nospace/test.ts.lint
test/rules/typedef-whitespace/both/nospace/tslint.json
test/rules/typedef-whitespace/both/onespace/test.ts.lint
test/rules/typedef-whitespace/both/onespace/tslint.json
test/rules/typedef-whitespace/both/space/test.ts.lint
test/rules/typedef-whitespace/both/space/tslint.json
test/rules/typedef-whitespace/right/nospace/test.ts.lint
test/rules/typedef-whitespace/right/nospace/tslint.json
test/rules/typedef-whitespace/right/onespace/test.ts.lint
test/rules/typedef-whitespace/right/onespace/tslint.json
test/rules/typedef-whitespace/right/space/test.ts.lint
test/rules/typedef-whitespace/right/space/tslint.json

Don't enforce trailing spaces on newlines in typedef-whitespace rule

---

src/formatters/fileslistFormatter.ts
test/formatters/fileslistFormatterTests.ts

Addresses review [#875140](https://github.com/palantir/tslint/pull/1558#discussion_r79750793) in PR #1558 for compatibility with discussion item #1553

Doesn't print \n if no failures

---

src/tslintMulti.ts

Fixes https://github.com/palantir/tslint/issues/1578

Existence check in tslintMulti for source file

---

test/check-bin.sh

... to replace expr command and [ (string eq)

use some bash arithmetics

---

package.json
src/ruleLoader.ts
src/tslintMulti.ts
test/config/tslint-almost-empty.json
test/config/tslint-custom-rules-with-dir.json
test/config/tslint-custom-rules-with-two-dirs.json
test/config/tslint-custom-rules.json
test/config/tslint-with-bom.json
test/config/tslint-with-comments.json
test/configurationTests.ts
test/executable/executableTests.ts
test/external/tslint-test-config-non-relative/tslint.json
test/external/tslint-test-config/tslint.json
test/external/tslint-test-custom-rules/tslint.json

Make mocha run all tests, fix broken tests

---

test/rules/ordered-imports/case-insensitive/test.js.lint
test/rules/ordered-imports/lowercase-first/test.js.lint

Fix js import ordering tests

---

.npmignore
.vscode/launch.json
.vscode/tasks.json
src/tsconfig.json

make tslint debuggable out of the box for vscode

Add vscode launch.json

---

src/configuration.ts

remove no-var-rule from  DEFAULT_CONFIG

---

package.json

Typescript peer dependency >= 2.0.0

---

src/configs/latest.ts
src/configs/recommended.ts

Add recommended rules

---

src/linter.ts

this.failures was being overwritten instead of appended to

Fix issue - not all errors displayed

---

CHANGELOG.md
docs/_data/rules.json
docs/rules/object-literal-key-quotes/index.html
src/configs/recommended.ts
src/rules/objectLiteralKeyQuotesRule.ts
test/rules/object-literal-key-quotes/consistent-as-needed/test.js.lint
test/rules/object-literal-key-quotes/consistent-as-needed/test.ts.lint
test/rules/object-literal-key-quotes/consistent-as-needed/tslint.json
test/rules/object-literal-key-quotes/consistent/test.js.lint
test/rules/object-literal-key-quotes/consistent/test.ts.lint
test/rules/object-literal-key-quotes/consistent/tslint.json

fixes #1453
Added new rule options `consistent` and `consistent-as-needed`

Add rule options for `object-literal-key-quotes`

---

src/linter.ts
src/rules/noNullKeywordRule.ts
test/rules/no-null-keyword/test.ts.lint

This checkin got lost in `next`

Allow null keyword in a type position (originally #1277)

---

src/rules/oneLineRule.ts
test/rules/one-line/all/test.ts.lint
test/rules/one-line/none/test.ts.lint

This commit got lost in `next`

Fix TS 2.0 one-line rule bug (originally #1429)

---

src/rules/maxClassesPerFileRule.ts

Fix description of maxClassesPerFileRule

---

src/configs/recommended.ts

Remove no-unused-variable from recommended config

---

src/linter.ts

Should not be clearing list of linter.fixes for each fix iteration

Was not reporting correct # of fixes

---

src/ruleLoader.ts
test/ruleLoaderTests.ts

Don't exit on missing rules

---

src/runner.ts

Loosened runner options

---

src/runner.ts

Added final onComplete, returns after onCompletes

---

docs/develop/custom-rules/index.md

Very small fix for an *Important conventions* list on the [Custom Rules](https://palantir.github.io/tslint/develop/custom-rules/) page.
(optional)

Fixed broken list on Custom Rules page

---

src/rules/promiseFunctionAsyncRule.ts

Minor code style fixes in promiseFunctionAsyncRule

---

package.json

Add missing dependency that was left from #1819

Install babel-code-frame

---

package.json
src/formatters/codeFrameFormatter.ts

Fixed the syntax for importing "babel-code-frame". This was changed by DefinitelyTyped/DefinitelyTyped#13246.

Fix import of "babel-code-frame"

---

src/rules/orderedImportsRule.ts

Add missing space line in docs for proper docs generation.
No

Add missing line for proper docs generation

---

package.json
src/language/utils.ts
src/linter.ts
src/rules/arrowParensRule.ts
src/rules/noConditionalAssignmentRule.ts
src/rules/noInferredEmptyObjectTypeRule.ts
src/rules/noNamespaceRule.ts
src/rules/preferConstRule.ts
src/rules/restrictPlusOperandsRule.ts
src/rules/typedefRule.ts
src/test.ts
test/rules/restrict-plus-operands/test.js.lint
test/rules/restrict-plus-operands/test.ts.lint

Lots of stuff broken by the TS API
fixes #1572

Upgrade to TypeScript v2.1.4

---

docs/usage/library/index.md

- Documentation update
Made docs compatible to 4.0.0.

Update Node API usage documentation

---

docs/_data/rules.json
docs/rules/no-inferred-empty-object-type/index.html
docs/rules/prefer-const/index.html
docs/rules/strict-boolean-expressions/index.html

Ran `npm run docs`.
Would be nice to get the tester to force pull requests to update docs. Otherwise people who run `npm run verify` will see additional chagnes from git.

Update docs (`npm run docs`)

---

CHANGELOG.md
docs/_data/rules.json
docs/rules/ban/index.html
docs/rules/completed-docs/index.html
docs/rules/object-literal-key-quotes/index.html
docs/rules/only-arrow-functions/index.html
docs/rules/ordered-imports/index.html
docs/rules/radix/index.html
package.json
src/linter.ts

this turned out to be a pretty big release

Prepare version 4.1.0

---

src/rules/preferConstRule.ts
test/rules/prefer-const/test.ts.fix
test/rules/prefer-const/test.ts.lint

`prefer-const` to handle destructuring arrays

---

src/language/walker/blockScopeAwareRuleWalker.ts
src/rules/noShadowedVariableRule.ts
test/rules/no-shadowed-variable/test.ts.lint

fixes #1796 
I don't understand why the code was the way it was before, so maybe I'm missing something

Fix and refactor `no-shadowed-variable`

---

src/test.ts

Swap fixes from markup and fixes from linter in diff
Any idea how to display whitespace diffs? Not relevant for this change, but may result in a followup PR.

Fix color output of fixer test

---

src/rules/objectLiteralKeyQuotesRule.ts

Remove trailing whitespace

---

docs/rules/semicolon/index.html

Fix list formatting in Semicolon rule docs.
(optional)

Fix list formatting

---

docs/rules/arrow-parens/index.html
src/rules/arrowParensRule.ts

Fix example configuration
(optional)

Add quotes around example option

---

src/rules/objectLiteralKeyQuotesRule.ts
test/rules/object-literal-key-quotes/always/test.js.lint
test/rules/object-literal-key-quotes/always/test.ts.lint
test/rules/object-literal-key-quotes/as-needed/test.js.lint
test/rules/object-literal-key-quotes/as-needed/test.ts.lint

Ignored any shorthand property assignments or spread assignments.

Exclude shorthand and spread properties from object-literal-key-quotes

---

src/rules/semicolonRule.ts

Fix formatting for semicolon rule docs.
(optional)

Semicolon docs: fix list formatting in source file

---

test/rules/object-literal-key-quotes/always/test.js.fix
test/rules/object-literal-key-quotes/always/test.ts.fix
test/rules/object-literal-key-quotes/as-needed/test.js.fix
test/rules/object-literal-key-quotes/as-needed/test.ts.fix

Fix test failures introduces by #1953
(optional)

Fix fixer tests of object-literal-key-quotes

---

src/rules/memberAccessRule.ts
test/rules/member-access/accessor/test.ts.lint
test/rules/member-access/constructor/test.ts.lint
test/rules/member-access/default/test.ts.lint

Error is reported from the start of the member until the end of its name instead of marking whole function bodies.
(optional)

Narrow error location of member-access

---

src/language/utils.ts
src/language/walker/syntaxWalker.ts
src/linter.ts
src/rules/banRule.ts
src/rules/forinRule.ts
src/rules/importBlacklistRule.ts
src/rules/noAngleBracketTypeAssertionRule.ts
src/rules/noConditionalAssignmentRule.ts
src/rules/noConstructRule.ts
src/rules/noDuplicateVariableRule.ts
src/rules/noEvalRule.ts
src/rules/noMagicNumbersRule.ts
src/rules/noMergeableNamespaceRule.ts
src/rules/noShadowedVariableRule.ts
src/rules/noSwitchCaseFallThroughRule.ts
src/rules/noUnusedVariableRule.ts
src/rules/noUseBeforeDeclareRule.ts
src/rules/noVarRequiresRule.ts
src/rules/preferForOfRule.ts
src/rules/strictBooleanExpressionsRule.ts
src/rules/typedefRule.ts
src/rules/typeofCompareRule.ts
src/rules/variableNameRule.ts
test/rules/no-angle-bracket-type-assertion/test.ts.fix
test/rules/no-angle-bracket-type-assertion/test.ts.lint
tslint.json

Also enable the rule in our codebase.

Implement fixer for no-angle-bracket-type-assertion

---

src/rules/preferConstRule.ts

Fix `prefer-const` for TypeScript <2.1

---

src/configuration.ts
src/linter.ts

Fix back-compat break when formattersDirectory === null

---

package.json
src/updateNotifier.ts

Used `@types/update-notifier` to avoid an untyped import.

Use @types/update-notifier

---

src/linter.ts

Instead of manual string parsing, use path module to get configFile directory 
(optional)

Simplify default projectDirectory using path module

---

src/rules/noMagicNumbersRule.ts
test/rules/no-magic-numbers/custom/test.ts.lint

`no-magic-numbers`: negative numbers fail even if in allowed node

---

src/rules/importBlacklistRule.ts
test/rules/import-blacklist/test.js.lint
test/rules/import-blacklist/test.ts.lint

Only check (template) string literals.
Avoid node.getText().
Add tests for non-static imports.

Rewrite importBlacklistRule

---

README.md

README: fix library type checking example

---

usage/third-party-tools/index.md

I added mocha-tslint to the Third-Party Tools list.
I haven't found any guidelines on what you want to include in the third party tools list (or the website in general) but since it's not a lot of work I thought I can give it a shot :)

Added mocha-tslint to Third-Party Tools in docs

---

src/rules/strictBooleanExpressionsRule.ts
test/rules/strict-boolean-expressions/default/test.ts.lint

Make `strict-boolean-expressions` test consistent w/ ts 2.0

---

src/language/utils.ts
src/rules/noEmptyRule.ts
test/rules/no-empty/test.ts.lint

Simplify checking for comment in empty block.
Don't add a failure for private or protected constructor.
Does this need to be added to the docs? The exception for parameter properties isn't in documented either.

Enhance NoEmptyRule

---

src/language/walker/syntaxWalker.ts

Adde a `visitNumericLiteral` to `SyntaxWalker`
Are other node types that are missing?

Added visitNumericLiteral to SyntaxWalker

---

src/language/utils.ts
src/rules/noBooleanLiteralCompareRule.ts
src/rules/noUnsafeAnyRule.ts
src/rules/strictTypePredicatesRule.ts
src/rules/tripleEqualsRule.ts
src/rules/typeofCompareRule.ts
test/rules/typeof-compare/test.js.lint
test/rules/typeof-compare/test.ts.lint

Clean up code and add `getEqualsKind` helper

---

src/language/rule/rule.ts

Fixes https://github.com/palantir/tslint/issues/1788.

Added interface descriptors to Replacement

---

test/executable/executableTests.ts
test/files/incorrect-rule-test-copy/test.ts.lint
test/files/incorrect-rule-test-copy/tslint.json

Added tests for wildcard --test

---

src/rules/commentFormatRule.ts
test/rules/comment-format/exceptions-pattern/tslint.json
test/rules/comment-format/exceptions-words/tslint.json

This PR addresses https://github.com/palantir/tslint/pull/1757#issuecomment-274593468
(optional)

Make keys consistent with other options

---

CHANGELOG.md
package.json
src/configs/latest.ts
src/linter.ts
src/rules/adjacentOverloadSignaturesRule.ts
src/rules/commentFormatRule.ts
src/rules/memberAccessRule.ts
src/rules/noUnusedVariableRule.ts
src/rules/oneLineRule.ts
src/rules/preferForOfRule.ts
src/rules/whitespaceRule.ts
src/test.ts
yarn.lock

fix errant space in recommended rule name
fix tslint warnings from 4.4.0

Prepare for v4.4.1

---

src/rules/whitespaceRule.ts
test/rules/whitespace/check-separator/test.ts.lint
test/rules/whitespace/check-separator/tslint.json

Fix whitespaceRule at EOF

---

src/formatterLoader.ts

Could not actually reproduce #2130, but this is a likely fix
fixes #2130

Trim formatter name

---

test/rules/no-unbound-method/test.ts.lint

Added a test. (Re: https://github.com/palantir/tslint/pull/2089#issuecomment-274953428)

no-unbound-method: Add JSX test

---

README.md

Align to the new branding https://angularjs.blogspot.com/2017/01/branding-guidelines-for-angular-and.html

Remove Angular version number

---

src/rules/preferForOfRule.ts
test/rules/prefer-for-of/test.ts.lint

Fix `prefer-for-of` false positive

---

circle.yml
yarn.lock

Update yarn.lock and use yarn in CircleCI

---

src/rules/interfaceOverTypeLiteralRule.ts

Added rationale and option example for `interface-over-type-literal`
I was not sure how to build docs and view them locally so could not test how this actually looks.

Add docs for interface-over-type-literal

---

src/rules/noTrailingWhitespaceRule.ts
test/rules/no-trailing-whitespace/default/test.ts.fix
test/rules/no-trailing-whitespace/ignore-comments/test.ts.lint
test/rules/no-trailing-whitespace/ignore-jsdoc/test.ts.fix
test/rules/no-trailing-whitespace/ignore-jsdoc/test.ts.lint
test/rules/no-trailing-whitespace/ignore-jsdoc/tslint.json

Add an option to ignore trailing whitespace in JSDoc comments.
Refactored the RuleWalker to a walk function.
(optional)

Add ignore-jsdoc to no-trailing-whitespace

---

src/error.ts
src/language/rule/typedRule.ts
src/linter.ts

fix regression from #2188 
cc: @ajafff

Handle rule implementing both apply and applyWithProgram

---

docs/develop/custom-rules/migration.md
docs/develop/custom-rules/performance.md

Addresses: https://github.com/palantir/tslint/pull/2093#issuecomment-277340355
Add documentation on how to use `WalkContext` and `AbstractWalker`.
Add a section for migrating from `RuleWalker`.
Add a page of performance tips.
I didn't know where to put this, so I just created new `.md` files. This needs to be integrated somewhere.
Feedback is very appreciated. Maybe the wording can use some love, because I'm not a native English speaker.

Add documentation for AbstractWalker and Performance best practices

---

src/rules/classNameRule.ts
src/rules/forinRule.ts
src/rules/indentRule.ts
src/rules/interfaceNameRule.ts
src/rules/noAnyRule.ts
src/rules/noInferrableTypesRule.ts
src/rules/semicolonRule.ts
src/rules/variableNameRule.ts

Fix some typographical errors in docs.
(optional)

Fix typographical errors in rule docs

---

usage/third-party-tools/index.md

Supports automatic linting in the TextMate editor
Added a link to a new third-party tool in the usage section.

Added tslint.tmbundle to Third-Party Tools

---

.gitattributes
package.json

* Use 'LF' line endings for '.fix' files to match '.lint' files
* Can't run shebang script, so use 'node' explicitly

Fixes for windows

---

package.json
test/rules/no-floating-promises/promises/test.ts.lint
yarn.lock

[chore] Upgrade typescript dev dependency to 2.2.1

Upgrade to TypeScript 2.2.1

---

circle.yml
scripts/assertMinCircleNodes.js

Update circle.yml to test against typescript@next

---

circle.yml
scripts/assertMinCircleNodes.js

test matrix:
index | node | typescript
-|-|-
0 | 4.1.2 | ^2.2.1
1 | 5.7 | ^2.2.1
2 | 6.1 | 2.0.10
3 | 6.1 | next

reduce containers back to 4

---

src/rules/noUnsafeAnyRule.ts

Cleaned up `noUnsafeAnyRule.ts`.

no-unsafe-any: Clean up documentation and implementation

---

src/language/walker/ruleWalker.ts

[breaking] Remove method `skip` from `RuleWalker`
Closes: #1900

Remove method skip from RuleWalker

---

docs/usage/third-party-tools/index.md

This PR contains only updated `.md` file. Added link for Yeoman generator-tslint into `Usage -> Third-Party-Tools` topic

added link for yeoman generator-tslint

---

src/rules/noReferenceRule.ts

Convert 'no-reference' to use WalkContext

---

test/rules/_integration/enable-disable/tslint.json

Left behind in #2344 
[no-log]

Undo unnecessary change to test tslint.json

---

src/rules/noInvalidThisRule.ts

no-invalid-this: Convert to function

---

README.md

Removed unnecessary space from link in readme

---

.vscode/launch.json
src/rules/alignRule.ts
test/rules/align/statements/test.ts.fix
test/rules/align/statements/test.ts.lint

[bugfix] don't fix `align` if it would remove code
Fixes: #2365
Fixes: #2366
[enhancement] check parameter alignment for all signatures
[enhancement] check statement alignment for all blocks

Bugfix and enhance alignRule

---

docs/_data/develop_sidebar.json

Fix broken migration link

---

test/executable/executableTests.ts
test/formatters/tapFormatterTests.ts
test/ruleLoaderTests.ts

Fixes #2405
Fixes #2329
Fixes #2404
[no-log]

Enable broken tests

---

circle.yml
package.json
scripts/tsconfig.json

[breaking] Minimum version of TypeScript version now 2.1.0

Remove support for typescript 2.0.10

---

src/rules/noDuplicateVariableRule.ts
test/rules/no-duplicate-variable/test.ts.lint

Just refactored the implementation.

Rewrite no-duplicate-variable

---

src/rules/memberAccessRule.ts
test/rules/member-access/default/test.ts.lint

Support index signatures in `member-ordering`.
[bugfix] Support index signatures in `member-ordering`.

member-ordering: Support index signature

---

src/rules/noUseBeforeDeclareRule.ts
test/rules/no-use-before-declare/test.ts.lint

Handle symbol with empty declarations list in `no-use-before-declare`.
[bugfix] `no-use-before-declare`: Handle symbol with empty declarations list.

no-use-before-declare: Handle symbol with empty declarations list

---

src/rules/onlyArrowFunctionsRule.ts

Just a conversion to `applyWithFunction`.

Refactor only-arrow-functions to use function walker

---

README.md

As discussed in #2459. Closes #2459.

Add mention about tslint-immutable in readme

---

src/rules/noUnusedVariableRule.ts

This option was already ignored; just removing it from documentation.

no-unused-variable: "react" option unnecessary, this is handled by default

---

src/rules/fileHeaderRule.ts

file-header: Remove unnecessary RuleWalker

---

src/rules/interfaceNameRule.ts
src/rules/variableNameRule.ts

interface-name: Convert to function

---

src/rules/noBooleanLiteralCompareRule.ts

no-boolean-literal-compare: Convert to function

---

src/rules/cyclomaticComplexityRule.ts
src/rules/importBlacklistRule.ts
src/rules/memberAccessRule.ts
src/rules/noFloatingPromisesRule.ts
src/rules/noUnusedVariableRule.ts
src/rules/preferTemplateRule.ts

Just cleaning up code. No need to go through `getOptions()` to get `ruleArguments`.

Simplify accesses to ruleArguments

---

src/rules/strictTypePredicatesRule.ts
test/rules/strict-type-predicates/test.ts.lint

Just a refactor. Also added a test for https://github.com/palantir/tslint/pull/2479#issuecomment-291041890 (#2472)

strict-type-predicates: Convert to function

---

docs/usage/library/index.md

AFAIK this is needed for a working example.

Update index.md - fixes #2457

---

docs/_layouts/rule.html

Fix broken links in rule docs, 
Example: go to https://palantir.github.io/tslint/rules/promise-function-async/
and click the "Requires Type Info" link
no
N/A

docs: fix broken link

---

src/rules.ts

Export OptionallyTypedRule to Lint.Rules namespace

---

CHANGELOG.md
package.json
src/configs/latest.ts
src/linter.ts

Update CHANGELOG.md and version #s
[no-log]

Prepare v5.1.0

---

package.json
scripts/buildDocs.ts

downgrade @types/chai (3.5.0 breaks build)

---

src/rules/noInternalModuleRule.ts
test/rules/no-internal-module/test.ts.fix
test/rules/no-internal-module/test.ts.lint

[new-fixer] `no-internal-module`
[bugfix] `no-internal-module`: no more false positives for global augmentation

no-internal-module: fix bug with global augmentation and add fixer

---

src/rules/noDuplicateSuperRule.ts

no-duplicate-super: Convert to function

---

src/rules/interfaceOverTypeLiteralRule.ts

interface-over-type-literal: Convert to function

---

src/rules/labelPositionRule.ts

label-position: Convert to function

---

src/rules/preferMethodSignatureRule.ts

prefer-method-signature: Convert to function

---

src/rules/noStringThrowRule.ts

no-string-throw: Convert to function

---

src/rules/banTypesRule.ts

ban-types: Refactor to function

---

src/rules/classNameRule.ts
test/rules/class-name/test.ts.lint

[enhancement] `class-name` now also checks class expressions

class-name: Refactor and check class expressions

---

src/rules/classNameRule.ts
src/rules/interfaceNameRule.ts
src/rules/numberLiteralFormatRule.ts
src/rules/variableNameRule.ts
src/utils.ts

Add isUpperCase and isLowerCase utils

---

README.md

Added community rule set for consistent code style
No
[no-log]

Added community rule set for consistent code style

---

src/rules/noUnnecessaryTypeAssertionRule.ts

Just some code cleanup noticed in #2519. CC @mitchellwills

no-unnecessary-type-assertion: Minor cleanup

---

src/rules/callableTypesRule.ts
test/rules/callable-types/test.ts.fix
test/rules/callable-types/test.ts.lint

[bugfix] `callable-types`: suggest correct fix for interfaces with type arguments
[new-fixer] `callable-types`

callable-types: Refactor and add fixer

---

src/rules/trailingCommaRule.ts

Just some code cleanup. Made use of `Record` and a new `fillOptions` helper.

trailing-comma: Clean up code for options parsing

---

scripts/generate-changelog.ts

On Gitter @intellix suggested adding links to the docs for each rule in the changelog.
So here it is:
Convert all rule names to links to the docs while generating changelog. Rule names need to be enclosed in backticks
Also filter out [no-log] automatically
[no-log]

Make rule names in changelog clickable links

---

package.json
yarn.lock

Update tsutils to support nightlies of typescript 2.4

---

src/test/lines.ts
src/test/parse.ts
test/rules/_integration/error-format/test.ts.lint

Fixes incorrect use of \w in regex.
[no-log]

allow error templates with dash in name

---

src/rules/matchDefaultExportNameRule.ts

match-default-export-name: refactor to function

---

src/rules/forinRule.ts

forin: Rewrite to function

---

src/rules/interfaceOverTypeLiteralRule.ts
test/rules/interface-over-type-literal/test.ts.fix
test/rules/interface-over-type-literal/test.ts.lint

[new-fixer] `interface-over-type-literal`
Fixes: #2615

interface-over-type-literal: add fixer

---

src/linter.ts

Add trailing quote in error message

---

src/configuration.ts
src/rules/objectLiteralKeyQuotesRule.ts
yarn.lock

Remove "fixed in 5.2" disables

---

test/files/eofline.test.ts

Removes `eofline.test.ts` which is no longer used. Seems like this has been forgotten when `eoflineTests.ts` was removed.
[no-log]

Remove unnecessary eofline.test.ts

---

src/configs/all.ts
tslint.json

Add align options "elements" and "members" to tslint:all

---

src/rules/noInferrableTypesRule.ts

Just a refactor. Pulls out different concerns into their own functions.

No-inferrable-types: Clean up code

---

src/configuration.ts
src/rules/banRule.ts
src/rules/maxFileLineCountRule.ts
src/rules/maxLineLengthRule.ts
src/rules/noInferrableTypesRule.ts
src/rules/noInferredEmptyObjectTypeRule.ts
src/rules/noParameterPropertiesRule.ts
src/rules/noShadowedVariableRule.ts
src/rules/objectLiteralKeyQuotesRule.ts
src/rules/objectLiteralSortKeysRule.ts
src/rules/orderedImportsRule.ts
src/rules/preferConstRule.ts

Replace unnecessary arrow functions with regular functions / methods.
[no-log]

Convert unnecessary arrow functions to regular functions

---

src/language/walker/blockScopeAwareRuleWalker.ts
src/language/walker/ruleWalker.ts
src/rules/deprecationRule.ts
src/rules/noShadowedVariableRule.ts
src/rules/noVarRequiresRule.ts
tslint.json

Just enables the rule and fixes failures.

Enable 'deprecation' rule

---

src/rules/unifiedSignaturesRule.ts

unified-signatures: Convert to function

---

src/rules/noMergeableNamespaceRule.ts
test/rules/no-mergeable-namespace/test.ts.lint

[bugfix] `no-mergeable-namespace`: display correct line in error message

no-mergeable-namespace: refactor to AbstractWalker and fix error message

---

src/rules/typeofCompareRule.ts

typeof-compare: Convert to function

---

src/configuration.ts

[configuration] deprecate mixed case tslint.json
Ref: #2702

Deprecate mixed case tslint.json

---

src/rules/noObjectLiteralTypeAssertionRule.ts
test/rules/no-object-literal-type-assertion/test.ts.lint

Wordsmith docs for no-object-literal-type-assertion

---

src/rules/commentFormatRule.ts
src/test.ts
tslint.json

Enables the lint rule and fixes failures.

Enable "no-inferrable-types"

---

src/rules/noRequireImportsRule.ts

no-require-imports: Rewrite as function

---

src/rules/promiseFunctionAsyncRule.ts

promise-function-async: Rewrite to function walker

---

src/rules/memberOrderingRule.ts

member-ordering: Covert to AbstractWalker

---

src/rules/noNamespaceRule.ts
tslint.json

Starts using the default configuration from `tslint:all` which is slightly stricter.

Enable strictest settings for "whitespace"

---

src/configs/all.ts
src/configs/recommended.ts
src/rules/indentRule.ts
src/rules/memberOrderingRule.ts
src/rules/noUnusedVariableRule.ts
src/rules/semicolonRule.ts
src/rules/trailingCommaRule.ts
test/executable/executableTests.ts
test/formatters/jsonFormatterTests.ts
tslint.json

Enables a slightly stricter setting for the "align" rule.
View the diff with [`?w=1`](https://github.com/palantir/tslint/pull/2755/files?w=1) for easier reading.

Enable "align" for array elements

---

docs/usage/library/index.md

Fix sample code for recent changes, show ES5 JavaScript code that will run with node (#2768)
Not sure if we really need TypeScript AND JavaScript examples
[docs] Fix code on Library Usage page, give JavaScript example

Documentation - library page - fix and enhancement 

---

src/rules/noNonNullAssertionRule.ts

no-non-null-assertion: Refactor to walker function

---

src/rules/noReferenceImportRule.ts

Rewrite as AbstractWalker to avoid closures.
Only search imports if there are reference directives.
[no-log]

Refactor no-reference-import

---

src/language/rule/rule.ts
src/rules/preferObjectSpreadRule.ts

Fixes lint errors that came from merging `prefer-object-spread`
[no-log]

Fix lint errors on master

---

tslint.json

We must have fixed this at some point.

Enable "no-inferred-empty-object-type"

---

src/test/lines.ts
src/test/parse.ts
src/utils.ts

Clean up combineCodeTextAndErrorLines

---

src/rules/noObjectLiteralTypeAssertionRule.ts

Remove some duplicated code
[no-log] just refactoring

Simplify no-object-literal-type-assertion

---

src/rules/noParameterPropertiesRule.ts
test/rules/no-parameter-properties/test.ts.lint

no-parameter-properties: Rewrite to walker function

---

CHANGELOG.md
README.md
package.json
src/linter.ts

Companion docs PR: https://github.com/palantir/tslint/pull/2850

Prepare release 5.4.0

---

_data/rules.json
develop/testing-rules/index.md
rules/ban/index.html
rules/binary-expression-operand-order/index.html
rules/comment-format/index.html
rules/completed-docs/index.html
rules/curly/index.html
rules/deprecation/index.html
rules/no-consecutive-blank-lines/index.html
rules/no-duplicate-variable/index.html
rules/no-unbound-method/index.html
rules/strict-boolean-expressions/index.html
rules/strict-type-predicates/index.html
rules/switch-final-break/index.html
rules/type-literal-delimiter/index.html
rules/use-default-type-parameter/index.html
usage/type-checking/index.md

Companion release PR: https://github.com/palantir/tslint/pull/2849

Update docs for v5.4.0

---

CHANGELOG.md
package.json
src/linter.ts

Includes fixes for #2855, #2857

Prepare release v5.4.2

---

src/configs/all.ts
src/configs/latest.ts

Adds the recently added option `check-parameters` to `no-duplicate-variable` in tslint:lastest and tslint:all

config: enable stricter config for "no-duplicate-variable" in latest and all

---

src/rules/noAnyRule.ts

Fix metadata about the no-any rule - it no longer has an autofixer

no-any rule no longer has autofixer

---

src/rules/encodingRule.ts

[bugfix] `encoding` closes files correctly
Fixes: #2954

encoding: close file handle

---

test/rules/no-unnecessary-qualifier/arguments.ts.lint
test/rules/no-unnecessary-qualifier/test-global.ts.lint
test/rules/no-unnecessary-qualifier/test.ts.lint

CI is failing when testing with typescript@next for a few days now.
This PR disables the failing tests until someone can fix it. I'll open an issue to track this.

Fix build failures cause by typescript@next

---

package.json
yarn.lock

Update tslint dependency
[no-log]

Update tslint and tsutils dependencies

---

src/language/rule/typedRule.ts

Fixed typo on warning message

---

src/language/walker/walker.ts

IWalker is declared in this file, so it's accessible even without importing.

Remove unnecessary import

---

src/rules/orderedImportsRule.ts
test/rules/ordered-imports/named-imports-any/test.ts.fix
test/rules/ordered-imports/named-imports-any/test.ts.lint

add missing check
@adidahiya Sorry, I forgot to add this check in #3102. 😅
[no-log]

fix(ordered-imports): add missing check

---

src/rules/quotemarkRule.ts

Add `avoid-template` to quotemark rule schema.
No.

Add `avoid-template` to quotemark rule schema.

---

src/rules/noInvalidTemplateStringsRule.ts
test/rules/no-invalid-template-strings/test.ts.lint

Addresses nodes w/ multiple template strings

no-invalid-template-strings logic errors

---

package.json
src/configuration.ts
src/language/utils.ts
src/language/walker/blockScopeAwareRuleWalker.ts
src/linter.ts
src/rules/noUnsafeFinallyRule.ts
src/rules/noVarRequiresRule.ts
src/rules/objectLiteralSortKeysRule.ts
src/rules/orderedImportsRule.ts
src/rules/strictBooleanExpressionsRule.ts
src/rules/trailingCommaRule.ts
src/tslint-cli.ts
yarn.lock

Update tslint dependency and remove unnecesary disables

---

docs/usage/type-checking/index.md

This is similar to my other PR (https://github.com/palantir/tslint/pull/1838). The Node API example is outdated.
I followed the current ES6 Node API example (from [here](https://palantir.github.io/tslint/usage/library/)) and updated it to use the type checker.
[no-log]

fixed type checking Node API example

---

docs/usage/type-checking/index.md

Update docs - fixes #3188

---

src/formatters/index.ts
src/formatters/junitFormatter.ts
test/formatters/junitFormatterTests.ts

JUnit formatter added.
[feature] New formatter: JUnit

JUnit formatter added.

---

docs/usage/type-checking/index.md
src/rules/orderedImportsRule.ts

Fix minor docs typo

---

docs/develop/custom-rules/index.md

Adds mention of [astexplorer.net](http://astexplorer.net/) to the 'Develop' page.

[Documentation] adds mention of astexplorer.net to 'Develop' page

---

src/formatters/stylishFormatter.ts

Fix typos in the styish formatter documentation

---

package.json
test/rules/whitespace/all/bom.ts.lint
yarn.lock

The real bug fix was published with tsutils@2.12.1
[bugfix] `whitepace` handles files with BOM and other irregular whitespace

whitespace: add regression test for #2506

---

docs/usage/configuration/index.md

Small change - I think it is helpful to show how to set severity in the example config.

Provide example of setting rule severity

---

src/rules/completedDocsRule.ts

completed-docs: document that it needs the type checker

---

src/rules/whitespaceRule.ts

Document that `whitespace` has a fixer.
Fixes: #3259
[no-log]

whitespace: document fixer

---

src/formatters/msbuildFormatter.ts

Remove outdated sentence from the docs.
Fixes: #3289
[no-log]

msbuild-formatter: remove note that all failures are warnings

---

src/rules/noRedundantJsdocRule.ts

Follow-up on #2754 with a performance optimization.
[no-log] just a performance optimization

no-redundant-jsdoc: only check nodes that can have JSDoc

---

CHANGELOG.md
package.json
src/configs/latest.ts
src/linter.ts

Prepare release 5.8.0

---

docs/usage/cli/index.md
src/tslint-cli.ts

docs: fix typos

---

src/rules/noDuplicateVariableRule.ts

Fixed doc typo for noDuplicateVariableRule.
Fixed doc typo for noDuplicateVariableRule.

Fixed doc typo for noDuplicateVariableRule

---

src/rules/curlyRule.ts
test/rules/curly/defaults/test.ts.fix
test/rules/curly/defaults/test.ts.lint
test/rules/curly/ignore-same-line/test.ts.fix

[bugfix] `curly` fixer now correctly handles comments
Fixes: #3472
The bug was introduced in #3262. We even tested these invalid fixes. That's embarassing I missed that during review.

curly: don't put opening curly inside comment

---

test/rules/await-promise/for-await-of/test.ts.lint
test/rules/no-unnecessary-class/allow-constructor-only/test.ts.lint

The tests were wrong all the time, but only a recent change in typescript@next revealed these bugs.
[no-log]

Fix syntax errors in tests

---

test/rules/curly/defaults/test.ts.fix
test/rules/curly/defaults/test.ts.lint

Issue was already fixed by #3473
Fixes: #3493
[no-log]

Add regression test for #3493

---

package.json
src/rules/noInvalidTemplateStringsRule.ts
src/rules/noUnusedVariableRule.ts
yarn.lock

and try to get rid of some disable comments
[no-log]

update tslint devDependency

---

src/rules/awaitPromiseRule.ts

Fixes #3512
[docs] Enhance `await-promise` options documentation

Update await-promise docs

---

src/configuration.ts

Removes some unnecessary code by using `os.homedir()`.
[no-log]

configuration: use os.homedir

---

README.md

We are developing a set of rules and underlying code models to find bugs in TypeScript. Could you add us to your list of community rule-sets?

Mention tslint-sonarts in community rule-sets

---

README.md

https://github.com/Glavin001/tslint-clean-code
Add `tslint-clean-code` to list of community rules.
No. Unless you have any comments on https://github.com/Glavin001/tslint-clean-code 😄 . Thank you for developing TSLint!!!
N/A.

Add tslint-clean-code to list of community rules

---

README.md

[README] Add link to TSLint rules for RxJS

---

src/rules/noIrregularWhitespaceRule.ts

Updated no-irregular-whitespace documentation to clarify irregular whitespace is not permitted in strings and comments
Verbiage, ensuring it's as clear & concise as possible

[docs]Updated no-irregular-whitespace documentation

---

CHANGELOG.md

docs(changelog): fix wrong description

---

docs/usage/configuration/index.md

Update for docs/usage/configuration/index.md

---

src/verify/lines.ts
src/verify/lintError.ts
src/verify/parse.ts

`@license` JSDoc tag was missing in these files.

Fix Copyright

---

src/test.ts

Minor fix which addresses point #1 of https://github.com/palantir/tslint/issues/3967.

Output +/- on diff so added/removed empty lines are visible.

---

CHANGELOG.md
package.json
src/linter.ts

Prepare release 5.11.0

---

.circleci/config.yml

Add tests for typescript@2.9 and typescript@3.0
[improvement] Add tests for typescript@2.9 and typescript@3.0

Add tests for ts2.9 and 3.0

---

.circleci/config.yml

Add new tests to workflows

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/rule-suggestion.md

I created some basic issue templates. We may want to change them/fix up the text as its pretty basic right now - but its a start!
Fixes #4000

Add issue templates

---

package.json

Set the `homepage` field in the package.json (see [documentation](https://docs.npmjs.com/files/package.json#homepage)).
This field allows applications to add a link when the package is referenced. See this example from VSCode:
[enhancement] Add `homepage` to package.json

Add the homepage to the package.json

---

src/formatters/stylishFormatter.ts

#1738 added support for rule severity but forgot to update the example for the stylish formatter.
Do I need to run an additional doc script or is this something only someone with publishing rights can do?
Maybe other formatters also have outdated examples.

docs(formatters): Update stylish example

---

src/rules/banRule.ts

Just a small typo.
[docs] Fix docs typo

Fix typo in ban docs

---

src/formatters/checkstyleFormatter.ts
src/formatters/junitFormatter.ts
src/formatters/pmdFormatter.ts

Fix typos in formatter descriptions

---

src/rules/code-examples/onlyArrowFunctions.examples.ts
src/rules/onlyArrowFunctionsRule.ts

Updated documentation to reflect changes made in #2229 to only-arrow-functions rule.
This was requested by @JoshuaKGoldberg [here](https://github.com/palantir/tslint/issues/4314#issuecomment-441118747).  This is the first time for me on tslint, how have I done?
Documentation updated to reflect earlier change to only-arrow-functions rule

Documentation updated to reflect earlier change to only-arrow-functions rule

---

README.md

Added three badges for not losing sight of dependecies status.
Only lines three to five are relevant. The others are code formatting changes made by prettier.
-

Badges for dependencies status

---

docs/usage/configuration/index.md

Fixes #3694 
- Add section on array syntax
- Mark boolean syntax as legacy
[documentation] Update configuration documentation to include array syntax

Update Configuration Documentation

---

src/rules/noInvalidThisRule.ts

Stylistic: update an enum to UpperCamelCase: https://github.com/palantir/tslint/pull/4034#discussion_r241066080
[no-log] Nit: UpperCamelCase enum in noInvalidThisRule

Nit: UpperCamelCase enum in noInvalidThisRule

---

docs/usage/third-party-tools/index.md

Gitpod comes with TSLint support.
You can try it on this PR:
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/palantir/tslint/pull/4299)
Also thank you for this great project. We use it in every TS project. :heart:

Added Gitpod to third-party tools

---

src/rules/orderedImportsRule.ts

Fix description details of ordered-imports rule.

fix ordered imports description details

---

docs/usage/third-party-tools/index.md

The link pointed to Webstorm docs from 2016; replaced with the latest.

Updating Webstorm link

---

rules/index.md

Fixes rendering of "Formatting" section on Rules documentation page.

Documentation: fix index page to include Formatting rules

---

.github/PULL_REQUEST_TEMPLATE.md

I keep forgetting to edit PR submissions to say "Fixes #...", and most folks don't add it in. It's nice to have issues auto-closed...

Added "fixes" to PR template

---

.vscode/settings.json

I'd mistakenly added it in merging #3583. Whoops.

Remove .vscode/settings.json git.ignoreLimitWarning

---

package.json
yarn.lock

Upgrades `diff` to `3.5.0` to address a security vulnerability.
- [enhancement] Upgrades `diff` to `3.5.0` to address a security vulnerability (#4783)

Upgrade `diff` to 3.5.0

---

README.md

Chore: Use https in Readme

---

CHANGELOG.md

fix a broken link to `/rules/strict-comparisons` in CHANGELOG.md

fix a broken link in CHANGELOG.md

---

src/rules/code-examples/radix.examples.ts

The example code of radix rule is simply wrong

Fix example code of Radix rule

---

README.md

- ~[ ] New feature, bugfix, or enhancement~
- ~[ ] Includes tests~
Addresses #490 and other user confusion a bit, I hope.

docs: More prominent deprecation notice in README.md
