palantir/tslint

lib/tslint.d.ts
src/language/walker/syntaxWalker.ts
src/rules/memberOrderingRule.ts
test/files/rules/memberordering-private.test.ts
test/rules/memberOrderingRuleTests.ts

Member ordering rule should not be considering type literals. So
skip them.

Fixes #292

---

src/rules/typedefRule.ts
test/files/rules/typedef.test.ts

This fix prevents tslint from issuing the typedef variable-declaration warning when declaring an iteration variable within for-in statements. 
e.g
```typescript
for (var p in [1, 2]) {
// "p" cannot have a type annotation.
}
```
Type annotations cannot be used for variable declarations within a for-in statement.

bug fix: don't issue typedef variable-declaration warning with for-in statements

---

src/rules/memberOrderingRule.ts
test/files/rules/memberordering-method.test.ts
test/rules/memberOrderingRuleTests.ts

This change introduces resetting the previous `IModifiers` state when
visiting an interface declaration.  Without doing so, subsequent
interface declarations would be conflated as if they were the same
interface when using the `variables-before-functions` rule option.
Version `1.2.0` did not have this problem and `2.1.0` introduced this
regression.  The `memberordering-method.test.ts` has been updated
appropriately to test for this regression and an additional test has
been provided to ensure that interface declarations should trigger
similarly to class declarations.

walk interface and reset previous state for member-ordering rules

---

lib/tslint.d.ts
src/language/walker/syntaxWalker.ts
src/rules/commentFormatRule.ts
src/rules/whitespaceRule.ts
test/files/rules/comment.test.ts

Comment format rule should skip templates (and other things). And the
whitespace rule should skip templates too.

Fixes #293

---

README.md
docs/sample.tslint.json
src/rules/alignRule.ts
test/files/rules/align.test.ts
test/rules/alignRuleTests.ts

This is a new rule that checks for vertical alignment for one of the three options: "parameters", "arguments" and "statements".

Added rule to enforce vertical alignment

---

src/rules/typedefRule.ts
test/files/rules/typedef.test.ts

This change prevents tslint from reporting a defect for the absence of a return type in a set accessor signature.

Do not check return type for set accessors since they don't have one.

---

src/rules/noDuplicateVariableRule.ts
test/files/rules/duplicate-variable.test.ts
test/rules/noDuplicateVariableRuleTests.ts

This way we can detect duplicate arguments in function declarations, or
if a var/let shadows one of the function arguments.

no-duplicate-variable: treat function arguments as vars

---

README.md
docs/sample.tslint.json
src/rules/switchDefaultRule.ts
test/files/rules/switchdefault.test.ts
test/rules/switchDefaultRuleTests.ts

This new rule checks that a 'default' case is present in a 'switch'.
I made it a new rule but it could be an option of a "switch" rule with "no-switch-case-fall-through" made also an option of "switch".

Added rule for enforcing 'default' case in 'switch' statement.

---

src/rules/noUnusedVariableRule.ts
test/files/rules/nounusedvariable-parameter.test.ts

I ran into a false positive when `no-unused-variables` is enabled together with the `check-parameters` option.
```javascript
function func(f: (x: number) => void) {
f(42);
}
```
tslint claimed that `x` is unused. That is a correct observation, though in such cases we actually want to ignore these warnings.

Ignore unused variables in type literals

---

src/rules/useStrictRule.ts
test/files/rules/semicolon.test.ts
test/files/rules/usestrict.test.ts
test/rules/semicolonRuleTests.ts

(bugfix) use strict statement should not always require semicolon #351

---

README.md

I noticed the custom rule example didn't work with the latest version of tslint. This is probably due to TypeScript compiler API changes.

Fix the custom rule example.

---

src/tslint-cli.ts

fixes #352 
Tested on Windows `cmd` and `powershell` and `msys`

Use template strings for cli-docs

---

src/rules/noEmptyRule.ts
test/files/rules/noempty.test.ts
test/rules/noEmptyRuleTests.ts

```typescript
class testClass {
constructor(protected allowed: any) {
}
}
```
^^
Access modifier : `protected`
is not allowed to have empty blocks.
So I created function : `isAccessModifier(modifier: string)`. 
As a result, empty blocks will be ignored when using `protected` .
- tslint
2.2.0-beta
- typescript
1.5.0
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/402)

Update noEmptyRule for AccessModifier

---

src/rules/jsdocFormatRule.ts
test/files/rules/jsdoc-windows.test.ts
test/rules/jsdocFormatRuleTests.ts

I came across this issue today as I was putting tslint rules into place on our code base. All of our development occurs on windows, and I was surprised to see so many jsdoc formatting errors. I dug in and found that #324 exactly described what was happening.
After digging further I found that the `jsdocFormatRule` did not support windows line endings! How funny for a TypeScript library I thought :)
I've gone ahead and implemented a fix. The reason I'm solving this with a regular expression and not detecting the host OS with `require('os').EOL` or `process.platform`, is because the line ending is dependent on where the file was originally authored, not where tslint is running.
Let me know if you would like me to update any comments, test, code for this PR.
Cheers!

Fix issue #324 windows line endings not respected

---

package.json

I had an error in one of my (currently custom) rules but it wasn't working.
After some minutes testing I noticed a message from grunt-ts with the following:
> 1 non-emit-preventing type warning
> Type errors only.
So this PR updates grunt-ts so that it is an error now because of the `failontypeerrors` options (seems that the default has the right value)
https://github.com/TypeStrong/grunt-ts#grunt-ts-gruntfilejs-options
Feel free to close if this isn't something you want at this point :)
Edit: oops, let me rebase this... one commit shouldn't be here :( **done**
To clarify, after this PR errors like calling a method with invalid parameters is an error (which is not the case currently)

Update grunt ts

---

src/rules/noUnusedVariableRule.ts
test/files/rules/nounusedvariable-var.test.ts

fix #190 
`declare var x: any;`
^^ Above code isn't an error anymore wen x isn't used

Don't check `declared` vars in the unused-variable-rule

---

lib/tslint.d.ts
src/language/walker/syntaxWalker.ts
src/rules/noUnusedVariableRule.ts
test/files/rules/nounusedvariable-var.test.ts
test/rules/noUnusedVariableRuleTests.ts

Add destructuring syntax & support to nounusedvariable-var.test.ts

---

lib/tslint.d.ts
src/language/utils.ts
src/rules/noUnusedVariableRule.ts
test/files/rules/nounusedvariable-parameter.test.ts
test/rules/noUnusedVariableRuleTests.ts

Add destructuring syntax & support to no-unused-variable rule for parameter declarations

---

src/rules/sortObjectLiteralKeysRule.ts
test/files/rules/sortedkey.test.ts
test/rules/sortObjectLiteralKeysRuleTests.ts

This rule lints an object literal's keys and validates that the user has declared them in alphabetical order.

Added rule to sort object literal keys alphabetically

---

test/files/rules/nounusedvariable-var.test.ts
test/files/rules/typedef.test.ts
test/files/rules/varname.test.ts
test/rules/noUnusedVariableRuleTests.ts
test/rules/typedefRuleTests.ts
test/rules/variableNameRuleTests.ts

Add test cases that make sure the TypeDef, UnusedVariable and VariableName rules work with spread syntax. This should allow us to close #369.
I haven't added tests for DuplicateVariable because DuplicateVariable doesn't support destructuring yet (#425).

Spread tests

---

Gruntfile.js
package.json
test/check-bin.sh

This fixes issue #424. 
The code generated by grunt tried to derive RuleWalker from SyntaxWalker before
loading SyntaxWalker. This was causing tslint-cli to crash.
The fix simply explicitly references syntaxWalker.ts from ruleWalker.ts.

Restore CLI functionality

---

src/configuration.ts

The default options enabled are:
curly: true,
indent: [true, 4],
no-duplicate-key: true,
no-duplicate-variable: true,
no-empty: true,
no-eval: true,
no-trailing-whitespace: true,
no-unreachable: true,
no-use-before-declare: true,
quotemark: [true, "double"],
semicolon: true

tslint-cli uses a default configuration if none is found

---

src/rules/noSwitchCaseFallThroughRule.ts
src/rules/noVarKeywordRule.ts

- the no-var-keyword error is too verbose, the convention
elsewhere is "forbidden blah" (no-eval, no-bitwise) which is
succint enough. detailed rule information is available on the
readme.

shorten error string

---

test/files/rules/semicolon.test.ts
test/rules/semicolonRuleTests.ts

This prevents regressions on #441

Add tests for semicolon rule on ES6 module syntax

---

.settings/settings.json
.settings/tasks.json
scripts/tsc-wrapper.js
test/formatters/externalFormatterTest.ts
test/ruleDisableEnableTests.ts
test/rules/noVarKeywordRuleTests.ts
test/tsconfig.json

- tsc-wrapper.js is just a wrapper on top of tsc for VS Code,
that walks up the dirtree until a tsconfig.json is found and
compiles at that path. necessary for tasks.json configuration
- test compilation will also work with this, but there's an issue with
test/tsconfig.json

compile all files using the right tsconfig.json

---

lib/tslint.d.ts
src/language/utils.ts
src/rules/noDuplicateVariableRule.ts
src/rules/noVarKeywordRule.ts
test/files/rules/no-duplicate-variable.test.ts
test/rules/noVarKeywordRuleTests.ts

Lint.isBlockScopedVariable now supports VariableStatements.

Style improvements to no-var-keyword rule

---

src/rules/noUnusedVariableRule.ts
src/rules/noUseBeforeDeclareRule.ts
test/files/rules/nounusedvariable-imports.test.ts
test/files/rules/nousebeforedeclare.test.ts
test/files/rules/whitespace.test.ts

Fixes #451
This affects the following rules:
- `no-unused-variable`
- `no-use-before-declare`
- `whitespace` (it was already handled here, but I added a regression test)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/468)

Add support for ES6 bare imports

---

src/rules/noDuplicateVariableRule.ts
src/rules/noUseBeforeDeclareRule.ts
test/files/rules/nousebeforedeclare.test.ts
test/rules/noUseBeforeDeclareRuleTests.ts

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/472)

Add support for var destructuring & named exports to no-use-before-declare rule

---

test/files/rules/jsdoc.test.ts

Adds verification for #332
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/482)

Add a test for templated strings in jsdoc rule

---

.travis.yml
src/rules/noDuplicateVariableRule.ts
src/rules/noShadowedVariableRule.ts
test/files/rules/no-duplicate-variable.test.ts
test/files/rules/no-shadowed-variable.test.ts
test/rules/noDuplicateVariableRuleTests.ts
test/rules/noShadowedVariableRuleTests.ts

Turns out we don't need to look at node.dotDotToken for BindingElements.
It's literally just a text token. We don't need it for any linting rule
right now, but might in the future.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/486)

Resolve #471, add tests for spread operator

---

src/rules/classNameRule.ts
src/tslint-cli.ts
test/files/rules/classname.test.ts
test/references.ts

- add a variable declaration for "assert" to fix atom-typescript compilation
- small indentation fix in tslint-cli.ts
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/494)

Fix #493: avoid checking class names for default exports

---

src/rules/noSwitchCaseFallThroughRule.ts
test/files/rules/switchdefault.test.ts

Fix #509
NoSwitchCaseFallThroughWalker didn't realize continue statements
would break out of case block.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/510)

Fix false positive on no-switch-case-fall-through

---

src/rules/indentRule.ts
test/files/rules/indentwith_tabs.test.ts
test/rules/indentRuleTests.ts

Eventually a full implementation of [smart-tabs](http://www.emacswiki.org/emacs/SmartTabs) would be nice, but the only case I've seen failing so far is using an initial space to align the asterisks in a multi-line comment. This allows that use-case (along with other multi-line comment formats) by simply turning off indentation checking inside multi-line comments.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/323)

Skip checking indentation inside multi-line comments

---

README.md

Reading over the rules themselves, these arguments seem required (since November 2014!) but are never mentioned in the doc.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/523)

Update README docs for quotemark and indent

---

appveyor.yml

This will allow appveyor to run the tests on both node 0.10 and 0.12 just like they do on travis

Use node 0.12 in AppVeyor

---

docs/sample.tslint.json

The indent rule in the sample is incorrect as of `2.4.2` and `master`
Valid options are:
```
"indent": [true, "spaces"]
OR
"indent": [true, "tabs"]
```
I guess in future the third option would be a number? But hopefully this fixes things for now.

Fix indent rule in sample tslint.json

---

Gruntfile.js
src/language/languageServiceHost.ts
typings/typescriptServices.d.ts

Typescript moved all their files from bin to lib. So use the file in lib.
Also, update typescriptServices.d.ts to match latest nightly, and fix
bug that tighter compiler caught.

Change reference in gruntfile from bin->lib

---

src/language/languageServiceHost.ts
typings/typescriptServicesScanner.d.ts

computeLineStarts is an impl detail we shouldn't be using:
https://github.com/Microsoft/TypeScript/issues/4057#issuecomment-130120572

Cleanup language service host

---

test/check-bin.sh
test/rules/classNameRuleTests.ts

Fix the indentation from PR #579, also fix  a few other typos in `check-bin.sh`.

Fix indentation/typos

---

src/rules/variableNameRule.ts
test/files/rules/varname.test.ts
test/rules/variableNameRuleTests.ts

When implementing AngularJS tests the inject methods recommends parameters to follow the convention "\_paramName\_", eg "\_$httpBackend\_".
The respective rule was missing in TSLint, which is now implemented by adding the option "allow-trailing-underscore" to "variable-name".
Cheers

Implemented optional trailing underscore for variableNameRule.ts

---

lib/tslint.d.ts
src/language/languageServiceHost.ts
src/rules/noUnusedVariableRule.ts
src/rules/noUseBeforeDeclareRule.ts
test/tsxTests.ts

Use .tsx extensions when interacting with language services when appropriate

---

src/rules/alignRule.ts
test/files/rules/align.test.ts

* Align rule won't crash on new expression without parens
* Align rule now checks constructor and method declarations
* Align rule test file now uses valid/normal TS syntax

Fix various bugs with align-rule

---

src/rules/noUnusedVariableRule.ts
test/files/rules/nounusedvariable-parameter.test.ts

unused variable rule shouldn't error on abstract methods with parameters

---

README.md
docs/sample.tslint.json
src/rules/quotemarkRule.ts
test/files/rules/quotemark.test.ts
test/rules/quotemarkRuleTests.ts

This rule allow to use "other" quote mark for escaping.
It is similar to the "escape" option of JSCS or the "avoid-escape" option of ESLint.
This option is explained on [JSCS - validateQuoteMarks rule](http://jscs.info/rule/validateQuoteMarks.html):
> Allow the "other" quote mark to be used, but only to avoid having to escape.
and also on [Rule quotes - ESLint - Pluggable JavaScript linter](http://eslint.org/docs/rules/quotes):
> The third parameter enables an exception to the rule to avoid escaping quotes.
Related #543

Add a relax option "escape" for quotemark

---

README.md
docs/sample.tslint.json
src/rules/noInferrableTypesRule.ts
src/rules/tsconfig.json
test/files/rules/noinferrabletypes.test.ts
test/rules/noInferrableTypesRuleTests.ts
test/tsconfig.json
tslint.json

Resolves https://github.com/palantir/tslint/issues/676

New Rule: no-inferrable-types

---

lib/tslint.d.ts
src/language/formatter/abstractFormatter.ts
src/language/rule/abstractRule.ts
src/language/walker/blockScopeAwareRuleWalker.ts
src/language/walker/scopeAwareRuleWalker.ts

refs #631
Don't think this breaks custom rules. Feel free to close if this isn't something you want:)
**edit: I did keep the `Lint.abstract();` in `utils.ts` because removing that would change the api**; it isn't used though

AbstractFormatter and AbstractRule are now abstract classes

---

docs/sample.tslint.json

This doesn't address the issue of the presence of conflicting rules, but anyone using the sample config be default will have a workable config.

Switch off conflicting rules in sample.json

---

src/configuration.ts

(This includes slightly refactoring the `findConfiguration` method so that the file is only read in one place instead of two.)

remove BOM from utf8 files if present

---

src/rules/variableNameRule.ts

See #748 
(No tests added because we don't really need to test that every term in the list is banned)

Add Undefined to List of Banned Var Names

---

src/lint.ts
src/tslint-cli.ts
src/tslint.ts

Reverts 'tslint' back to being an old-style module so it works better with CommonJS.

Make src/tslint.ts a commonjs-style module instead of an ES6 module.

---

README.md
src/rules/noUnusedVariableRule.ts
test/files/rules/nounusedvariable-react1-react.test.tsx
test/files/rules/nounusedvariable-react1-react_addons.test.tsx
test/files/rules/nounusedvariable-react2-react.test.tsx
test/files/rules/nounusedvariable-react2-react_addons.test.tsx
test/files/rules/nounusedvariable-react3-react.test.tsx
test/files/rules/nounusedvariable-react3-react_addons.test.tsx
test/rules/noUnusedVariableRuleTests.ts

Addresses #698 
```
"no-unused-variable", [true, "react"],
```
With such a valid option, the following is __not__ an error:
```typescript
import * as React from "react";
let x = <span></span>;
console.log(x);
```
Thoughts/comments?

Implement a "react" option for the no-unused-variable rule

---

src/rules/useStrictRule.ts
test/files/rules/usestrict.test.ts
test/rules/useStrictRuleTests.ts

This will make it work for code like this:
```
module A.B.C {
// use strict required here
}
```
Fixes #544

Improve use-strict rule to work for module declarations with more than one identifier

---

src/rules/noUnusedVariableRule.ts
test/files/rules/nounusedvariable-react4-react.test.tsx
test/rules/noUnusedVariableRuleTests.ts

Also reorder some methods in NoUnusedVariableWalker.

Fix no-unused-variable "react" option to support self-closing JSX elements

---

package.json

Accept all versions of 1.7.0-dev after the jsx spread bugfix, accept all versions of 1.8.0-dev, accept any release versions >= 1.7.0

Move to a peer dependency for typescript

---

Gruntfile.js
test/tsxTests.ts

will fix #832 because `tslint` distribution will now be built with the latest compiler

Small updates for TypeScript 1.7.3

---

README.md
src/rules/noRequireImportsRule.ts
test/files/rules/norequireimports.test.ts
test/rules/noRequireImportsRuleTests.ts

Only lint call expressions and external module references in no-require-imports rule

---

CHANGELOG.md
package.json
src/tslint.ts

I tested locally and we no longer work with 1.6.2, so I bumped the typescript peer dependency to >= 1.7.3

Prepare release 3.1.1

---

src/configuration.ts
src/enableDisableRules.ts
src/formatters.ts
src/formatters/index.ts
src/formatters/jsonFormatter.ts
src/formatters/pmdFormatter.ts
src/formatters/proseFormatter.ts
src/formatters/verboseFormatter.ts
src/language/formatter/abstractFormatter.ts
src/language/formatter/formatter.ts
src/language/languageServiceHost.ts
src/language/rule/abstractRule.ts
src/language/rule/rule.ts
src/language/utils.ts
src/language/walker/index.ts
src/language/walker/ruleWalker.ts
src/language/walker/skippableTokenAwareRuleWalker.ts
src/ruleLoader.ts
src/rules.ts
src/tslint.ts

This change reduces usage of `import * as Lint` in favor of more granular imports. This reduces cyclical dependencies between our modules.

Tighten imports across core sources

---

src/tslint.ts

Relative path to `--rules-dir` is getting two times the number of `'..\\'` prefixes that it needs.
`getRulesDirectories()` is already called inside `ruleLoader.ts::loadRules()` and each call is currently calling `getRelativePath()`.

Don't double-call getRulesDirectories()

---

package.json
src/tslint-cli.ts
tsd.json
typings/glob/glob.d.ts
typings/tsd.d.ts

Related to #692. Potentially fixed glob issues in windows.
This makes the cli accept a glob as a string and expand it.
It solves a problem with "arguments list is too large" when using regular globs.

Better support for globs in cli

---

src/formatters/index.ts

Since all of the formatters are named `Formatter`, this is going to break in TypeScript 1.8 and we noticed it when nightlies weren't getting published.

Use explicit exports for formatters.

---

package.json

This allows tools like tsd to auto-pull definition files from the node_modules folder

Add typescript definition info to packages.json

---

src/configuration.ts
src/tslint-cli.ts
test/check-bin.sh
tslint.json

Implements #717 
A simple implementation of a feature to generate a tslint.json file for users. This PR is very limited in scope - there are lots of ways for this to be improved in the future.
This feature intentionally isn't added to the README yet, that can be done once a better default configuration is settled on.

Automatic tslint.json generation with --init command

---

src/rules/noVarKeywordRule.ts
test/files/rules/novarkeyword.test.ts
test/rules/noVarKeywordRuleTests.ts

no-var-keyword currently only prevents the `var` keyword in a block. This PR ensures var keywords are also correctly forbidden in for loop initializers.

Forbid var keyword in for, for-in, and for-of loops

---

src/rules/noUnusedExpressionRule.ts
test/files/rules/unused.expression.test.ts
tslint.json

Fix bug where await expressions were marked as unused

---

src/rules/quotemarkRule.ts
test/files/rules/quotemark.test.tsx
test/rules/quotemarkRuleTests.ts

I want to enforce double quotes in jsx attributes, but single quotes in strings. 
So I add options `jsx-single` and `jsx-double` to quotemark for enforcing quotes in jsx.
Fixes #673

Enforce quote mark in JSX attributes.

---

src/configuration.ts
src/tslint-cli.ts
test/check-bin.sh
test/config/tslint-custom-rules-with-dir.json
test/config/tslint-custom-rules.json
test/files/custom-rules/alwaysFailRule.js
test/ruleLoaderTests.ts

New behavior:
* Throw an error if the rules directory supplied does not exist
* If rules directory is supplied in a tslint.json or package.json file, look for directory relative to .json file.
* If rules directory is supplied via CLI, look for directory relative to CWD.
Fixes #910

Improve handling of paths to custom rules directories

---

src/rules/oneLineRule.ts
test/files/rules/oneline.test.ts

Correctly find = token for variable declarations in one-line rule.

---

_includes/header.html

Update href to be coherent with the "the full usage guide" link.

'learn more' button goes to 404

---

src/rules/trailingCommaRule.ts
test/rules/trailing-comma/multiline-always/test.ts.lint
test/rules/trailing-comma/multiline-never/test.ts.lint
test/rules/trailing-comma/singleline-always/test.ts.lint
test/rules/trailing-comma/singleline-never/test.ts.lint

This PR addresses https://github.com/palantir/tslint/issues/856. It's only a one line fix, but quite a few test cases were added to cover the various flavors of multiline literals.

Identify multiline literals with single property correctly.

---

README.md
docs/sample.tslint.json
src/rules/oneLineRule.ts
test/rules/one-line/all/test.ts.lint
test/rules/one-line/all/tslint.json
test/rules/one-line/none/test.ts.lint
tslint.json

* Correctly check for space between catch and opening brace (fixes #925)
* Add `check-finally` option
* Check opening brace of finally blocks

Various fixes to one-line rule

---

src/rules/typedefWhitespaceRule.ts
test/rules/typedef-whitespace/none/test.ts.lint
test/rules/typedef-whitespace/nospace/test.ts.lint
test/rules/typedef-whitespace/space/test.ts.lint

This PR addresses https://github.com/palantir/tslint/issues/955.
There are some bugs related to looking for spaces before and after the colon on a function's return type caused by assuming that the colon comes exactly one character after the end of the parameter list. Instead of assuming, search the AST for the actual colon token.
The only thing I don't like about this solution is that there might not be a colon after the parameter list in which case I return `0` as a sentinel. I could make sure there is a return type before calling my new helper function, but that logic is already happening inside the `checkSpace()` function which is overgeneralized to handle all "check space" logic even for non-function-like cases.
I also noticed that some function types like setter methods and regular …

Identify spaces before function return type colons correctly.

---

README.md
docs/sample.tslint.json
src/rules/typedefRule.ts
test/rules/typedef/all/tslint.json
test/rules/typedef/arrow-parameter/test.ts.lint
test/rules/typedef/arrow-parameter/tslint.json
test/rules/typedef/parameter/test.ts.lint
test/rules/typedef/parameter/tslint.json

See https://github.com/palantir/tslint/issues/333 for discussion.
This was a quick fix this for me to use personally, but I am happy to make any changes required for this PR to be merged if the functionality is desired.

Add new typedef rule: "arrow-parameter", to check typedefs are supplied for arrow function parameters separately from other functions

---

README.md
src/rules/memberOrderingRule.ts
test/rules/member-ordering/method/test.ts.lint

Treat member variables initialized to a function as a function for ordering purposes

---

src/language/walker/blockScopeAwareRuleWalker.ts
test/rules/no-shadowed-variable/test.ts.lint

fix #1021
If node is a alone block, e.g.
```
{
const a = 3
}
```
`isBlockScopeBoundary()` should return true

fix isBlockScopeBoundary, add test case for no-shadowed-variable.

---

src/rules/noAngleBracketTypeAssertionRule.ts
src/tsconfig.json
test/rules/no-angle-bracket-type-assertion/test.ts.lint
test/rules/no-angle-bracket-type-assertion/tslint.json
test/tsconfig.json

Checks for uses of the `<>` type assertion syntax and suggests changing it to the `as` syntax.
Fixes #639 
---
The name of the rule comes from TS - the `<>` syntax is called a TypeAssertionExpression and the `as` syntax is called an AsExpression. But I can imagine it'll be confusing to tslint users because functionally they're both type assertion expressions. I'm open to suggestions for the name. (`no-angle-bracket-type-assertions` ? I'm hesitant about calling it `old` or `legacy`.)
I also didn't make this a tri-state (disabled, enforce `as`, enforce `<>`) because I'm not sure anyone will care for the last one.
For the test case - I wrote it initially without the errors, then ran `grunt` and accepted its output that contained the errors. Is there anything else I need to do?

Add no-type-assertion-expression rule.

---

tslint.json

Update tslint.json file in root to use extended semicolon rule format
that includes “always”/“never” option

Update tslint.json to use extended semicolon rule format

---

package.json
src/configuration.ts
test/configurationTests.ts

Allows one to provide directories to custom rules living in a node module using the "node_module:" prefix:
```
{
rulesDirectory: "node_module:tslint-eslint-rules/dist/rules"
rules: { ... }
}
```
This is better than relative paths to node modules, which can behave funky depending on where the node module gets installed. Internally, this uses `require.resolve` to find the location of the node module, which means that it's using node's package finding algorithm, which is good.

Add `node_module:` prefix for loading rules from a node module

---

src/rules/objectLiteralSortKeysRule.ts
test/rules/object-literal-sort-keys/test.ts.lint

Adding TSLint to our projects has been a huge benefit, but nearly every developer who has encountered the `unsorted key 'a'` message has come to me and asked "I understood how to fix the other errors I saw, but I have no idea what this one means."  
I think just saying "unsorted key" is not enough information to give someone who has never encountered this error before.  So i'm proposing just a small text change to help clarify this.
**Before** :-1: 
>unsorted key 'a'
**After** :+1: 
>The key 'a' is not sorted alphabetically

Clarify the "unsorted key" failure message

---

custom-typings/path-is-absolute.d.ts
package.json
src/configuration.ts
src/tsconfig.json
test/config/tslint-extends-package-array.json
test/config/tslint-extends-package-no-mod.json
test/config/tslint-extends-package-two-levels.json
test/config/tslint-extends-package.json
test/config/tslint-extends-relative.json
test/configurationTests.ts
test/tsconfig.json

I want to add some test in but don't know how. I have added a config.json file. Can you give me some pointers?
Also, please comment on the name and location of the functions.
I can adjust accordingly.
---
edit from @adidahiya: closes #997

Add extends support

---

src/rules/noUnusedExpressionRule.ts
test/rules/no-unused-expression/test.ts.lint

JS directives are not unused expressions

---

src/configuration.ts

This ensures that it is handled correctly by loadConfigurationFromPath.
Helps solve #1092

Make findConfigurationPath always return an absolute path

---

package.json

This reverts commit 8ecaf3ee636da9c6f70896e33e807594849ac71c.
Fixes #1106.
See also https://github.com/js-cli/node-findup-sync/issues/31
This shouldn't break #1080, as we still upgrade to a slightly newer version of findup-sync which uses the newer version of glob.

Revert "Update findup-sync"

---

package.json
test/config/tslint-extends-package-array.json
test/config/tslint-extends-package-no-mod.json
test/config/tslint-extends-package-two-levels.json
test/config/tslint-extends-package.json
test/configurationTests.ts
test/external/tslint-test-config/package.json
test/external/tslint-test-config/tslint.json
test/external/tslint-test-custom-rules/package.json
test/external/tslint-test-custom-rules/tslint.json

This helps avoid weird dependency bugs that cause builds to fail

"extends" tests now use code inside this project

---

src/rules/noVarKeywordRule.ts
test/rules/no-var-keyword/test.ts.lint

Instead of just telling someone what they can't do, give suggestions about how to fix it and what they should do as an alternative.
Currently the rule `no-var-keyword` complains with 
>forbidden var keyword
But that really doesn't help, especially if someone is new to TypeScript and is not even aware that `let` and `const` are possibilities.
Now it will complain with this message
>forbidden 'var' keyword, use 'let' or 'const' instead

Clearer message for `no-var-keyword` rule

---

src/rules/semicolonRule.ts
test/rules/semicolon/always/test.ts.lint
test/rules/semicolon/enabled/test.ts.lint
test/rules/semicolon/never/test.ts.lint

Methods declared like:
```ts
class Foo {
bar = () => { }
}
```
shouldn't be marked as requiring a trailing semi-colon for the closing `}`
Addresses: #1076

Make semi-colon rule laxer with bound-method properties

---

src/configuration.ts
src/utils.ts

And strip comments. i.e. now allows user to add comments on `tslint.json`
Fixes #1128

Fix config cache issue

---

docs/sample.tslint.json

A few options were missing form the sample `tslint.json` file.  I've added them now.
----
:question: **Question**, should the `ban` option also have an example of how to ban a method call?  Perhaps this would be a good sample? Maybe just a subset of this?
```json
"ban": [
true,
[ "_", "forEach" ],
[ "_", "each" ],
[ "$", "each" ],
[ "angular", "forEach" ]
]
```
*(We ban these library loops in our apps since in most cases when devs want to use this, they are just looping over a flat JS array and a standard `for` loop would perform faster)*

Adding missing sample options

---

src/language/walker/scopeAwareRuleWalker.ts
src/rules/noInvalidThisRule.ts
src/tsconfig.json
test/rules/no-invalid-this/enabled/test.ts.lint
test/rules/no-invalid-this/enabled/tslint.json
test/tsconfig.json

This PR adds a rule that flags usage of the `this` keyword outside of class-body scopes.
Often I find myself refactoring code that looks like:
```ts
class Foo {
private aMethod() {
doWorkOn(this.someState.x);
}
}
```
to pull `aMethod` out into a function that looks like:
```ts
function(someState) {
doWorkOn(someState.x);
}
```
When I make this change by hand I find that I screw up a lot and accidentally write:
```ts
function(someState) {
doWorkOn(this.someState.x); /* note `this` */
}
```
which does not cause a compile error because typescript unhelpfully infers `this` with type `any`.
I've found that `this` outside of a `class` in code that is using ES6-class syntax is almost always a mistake. I wouldn't turn this on by default for all users of tslint, but it'd be very useful in my case …

Add "no-invalid-this" rule

---

src/enableDisableRules.ts
test/files/enabledisable.test.ts

Quite some people prefer using single line comments for implementation comments (as opposed to documentation comments e.g. on function headers). This change allows them.

Allow enabling/disabling tslint using single line comments.

---

README.md
src/rules/noReferenceRule.ts
src/tsconfig.json
test/rules/no-reference/test.ts.lint
test/rules/no-reference/tslint.json
test/tsconfig.json

The reasoning is that these are superseded by ES6 style imports, and the syntax
overall isn't too pleasant.

Support outlawing `/// <reference>` style imports.

---

src/rules/trailingCommaRule.ts
test/rules/trailing-comma/multiline-always/test.ts.lint
test/rules/trailing-comma/multiline-never/test.ts.lint
test/rules/trailing-comma/singleline-always/test.ts.lint
test/rules/trailing-comma/singleline-never/test.ts.lint

Fixes #1122 
When linting constructs like such:
```ts
[{
a: 5,
b: 6,
}]
```
The array is now handled by the _singleline_ option instead of the multiline option. The object inside the array is still handled with the multiline option.
Constructs are treated as singleline if the last list item ends on the same line as the closing token of the construct. Otherwise, they are considered multiline.
Handled by the singleline option:
```ts
import { a, b, c,
g, h, i, j } from "wherever";
```
Handled by the multiline option:
```ts
import {
a,
b,
c,
j,
} from "wherever";
```

Tweak trailing-comma rule classification of singleline vs. multiline

---

src/rules/noUnusedExpressionRule.ts
test/rules/no-unused-expression/test.ts.lint

This builds on work in #1094 (related to #1050) by improving no-unused-expression rule to recognize directives in class constructors and property getters and setters.

Recognize directives in class constructors and properties.

---

README.md
src/language/utils.ts
src/rules/noInternalModuleRule.ts
src/rules/noNamespaceRule.ts
src/tsconfig.json
test/rules/no-namespace/allow-declarations/test.ts.lint
test/rules/no-namespace/allow-declarations/tslint.json
test/rules/no-namespace/default/test.ts.lint
test/rules/no-namespace/default/tslint.json
test/tsconfig.json

This allows code bases to outlaw pre-ES6 modules and namespaces. It's often
still useful to declare namespaces when interacting with non-TypeScript code, so
this has an option to allow "declare namespace" style usage.

Support disallowing namespaces (noNamespace).

---

Gruntfile.js
custom-typings/path-is-absolute.d.ts
custom-typings/resolve.d.ts
package.json
src/configuration.ts
src/tsconfig.json
test/check-bin.sh
test/config/package.json
test/configurationTests.ts
test/external/tslint-test-config-non-relative/package.json
test/external/tslint-test-config-non-relative/tslint.json
test/external/tslint-test-config/package.json
test/external/tslint-test-custom-rules/package.json
test/external/tslint-test-custom-rules/rules/ruleOneRule.js
test/external/tslint-test-custom-rules/rules/ruleThreeRule.js
test/external/tslint-test-custom-rules/rules/ruleTwoRule.js
test/tsconfig.json

Fixes #1171 by using [resolve](https://www.npmjs.com/package/resolve) to resolve package-based extension configuration files from the directory of the current configuration file.
I've modified the tests for extends so that they have their own node_modules (created by the `run:installTestDeps` task) in `./test/config`, so that `tslint-test-config` and `tslint-test-custom-rules` can't be accessed by tslint directly with `require()`.

Use `resolve` instead of Node.JS require for resolving configuration files

---

Gruntfile.js
test/check-bin.sh

* Remove test relying on `mktemp -d`
* Clean tests' node_modules so a clean install happens on each test run
related to #1172

Tweak tests/build so they more reliably pass on all machines

---

src/enableDisableRules.ts
test/files/enabledisable.test.ts
test/ruleDisableEnableTests.ts

This PR supports using ESLint style single line ignore switches by using `tslint:disable-line` and `tslint:disable-next-line`.
This PR resolves #144

Single line ignore switches

---

README.md
docs/sample.tslint.json
src/rules/noInvalidThisRule.ts
test/rules/no-invalid-this/enabled/test.ts.lint
test/rules/no-invalid-this/enabled/tslint.json

This PR extends the [no-invalid-this] with the option "in-function-in-method".
If it is enabled it complains about the usage of the `this` keyword inside of function expression within a method.
`this` in such function expressions is usually meant to refer the this outside of the functions scope.
This rule will not complain about this in arrow functions.
In our project, it happened often when migrating JS to TS. With an angular service written as
```javascript
angular.module('a',[]).factory('Service', function(Helper, Enhancer){
return {
getAllMapped: function(){
return Helper.getAll()
.map(function(item){
return Enhancer.enhance(item);
})
}
}
}); 
```
We often end up with
```javascript
class ServiceClass {
constructor(private Helper, private Enhancer){
}
public getAllMapped() {
return …
```

Extend no-invalid-this rule to disallow `this` in functions in methods

---

src/rules/noUnreachableRule.ts
test/rules/no-unreachable/test.ts.lint

no-unreachable: allow type alias after function return

---

docs/sample.tslint.json

rule was renamed in #1198, but the sample.tslint.json file was not updated, this PR renames accordingly

renaming, see #1198

---

README.md

Updated README.md to explain that no-unreachable rule is a compiler flag on the tsc compiler that is enabled by default.

README.md - no-unreachable is a tsc compiler flag

---

src/rules/memberOrderingRule.ts
test/rules/member-ordering/order/custom/test.ts.lint
test/rules/member-ordering/order/custom/tslint.json
test/rules/member-ordering/order/fields-first/test.ts.lint
test/rules/member-ordering/order/fields-first/tslint.json
test/rules/member-ordering/order/instance-sandwich/test.ts.lint
test/rules/member-ordering/order/instance-sandwich/tslint.json
test/rules/member-ordering/order/statics-first/test.ts.lint
test/rules/member-ordering/order/statics-first/tslint.json

Adds an optional new syntax for more explicit control of the `member-ordering` rule (see #1208).
This should resolve #1205 and #1186 by giving a user more power to define their own orderings. This keeps backwards-compatibility with the old rule options (which will be removed in TSLint 4.0). This also allows for the possibility of further fields, like an `alphabetical: true` option.

Next-gen member-ordering rule

---

src/rules/memberOrderingRule.ts
test/rules/member-ordering/order/custom/test.ts.lint

Fixes #1243 
Object literals can have "methods" in them, this makes sure we don't check them.
We could do a check in `pushMember` to make sure `memberStack.length > 0`, but this would be treating the symptom instead of the disease... do we want to do this anyways in addition?

Fix bug in member-ordering rule

---

src/language/walker/syntaxWalker.ts
src/rules/memberOrderingRule.ts
test/rules/member-ordering/order/custom/test.ts.lint

Should fix #1251 and #1250 
Also, only run code dealing with `order` option if it's specified. If there are any further bugs, this should prevent them for people using the old options

Fix member ordering bug

---

.gitattributes
src/rules/linebreakStyleRule.ts
src/tsconfig.json
test/rules/linebreak-style/emptyFile/tslint.json
test/rules/linebreak-style/failure/CRLF/test.ts.lint
test/rules/linebreak-style/failure/CRLF/tslint.json
test/rules/linebreak-style/failure/LF/test.ts.lint
test/rules/linebreak-style/failure/LF/tslint.json
test/rules/linebreak-style/success/CRLF/test.ts.lint
test/rules/linebreak-style/success/CRLF/tslint.json
test/rules/linebreak-style/success/LF/test.ts.lint
test/rules/linebreak-style/success/LF/tslint.json
test/tsconfig.json

initial attempt at the linebreak style rule. I used a manually created scanner because i need to tokenize the `NewLineTrivia` tokens, which aren't exposed in the standard rule framework. basically just walking the tokens until i see the new line token and checking its text content if it matches the configured linebreak type.
`CR` is not supported due to `CR` not really working properly at all. I left the `CR` code stubbed in and disabled for (potential) future use.
Tests are a bit funky because I can't create a mixed line endings file very easily (does git even allow such a thing via `.gitattributes`?). Right now I'm just testing that line endings are detected properly and success and failure scenarios work. But I cannot test a real world scenario where a paste with conflicting line …

adding linebreak-style rule

---

test/rules/semicolon/always/test.ts.lint

Add test for semicolons for readonly interface members

---

src/rules/noNullKeywordRule.ts
test/rules/no-null-keyword/test.ts.lint

Allow null keyword in a type position

---

README.md

README.md - explained that Formatter class must be named Formatter
I discovered this myself after working about 30 minutes to figure out why it was not found.

README.md - explained that Formatter class must be named Formatter

---

README.md

Flycheck is the most used Emacs package for on-the-fly syntax checking. And it supports [tslint](http://www.flycheck.org/en/latest/languages.html#typescript).

Mention Emacs support

---

src/language/walker/syntaxWalker.ts

Visit JsxExpression node.
I am going to port [jsx-curly-spacing](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-curly-spacing.js) rule and find no such node visitor function.

Visit JsxExpression node.

---

README.md

The existing sample in the README is invalid json.
The example used array braces for rules definition, but this should be an object.

correct example tslint.json

---

src/rules/memberAccessRule.ts
test/rules/member-access/accessor/test.ts.lint
test/rules/member-access/constructor/test.ts.lint
test/rules/member-access/default/test.ts.lint

:-1:  **Before**:
>default access modifier on member/method not allowed
:+1: **After**:
>The class method 'a' is missing an access modifier
or
>The class property 'i' is missing an access modifier
I always though a message about "default access modifier" was never very clear, especially for those new to TypeScript.  It doesn't **have** a default modifier, the issue is that it **does not have** a prefixed keyword that the rule requires.
Hopefully these changes will make this message easier to understand.
---
I considered making the message something like:
>The class method 'a' must be marked as either 'private', 'public', or 'protected'
I do like that it's more specific about what needs to be added, but I was unsure if it was too much.  What do you think, should I change it to be more like …

Improving failure messages for the member-access rule to be more specific about what failed

---

src/rules/memberAccessRule.ts
test/rules/member-access/default/test.ts.lint

I recently made PR #1303 (which was _just_ merged in!), but I realized a few moments ago that it did not properly get the member name in instances where the `static` keyword was used.  The tests never made use of this keyword, so I added some usages and updated the rule to properly get the member name regardless if the `static` keyword is used or not.
I like this way better anyway since it no longer assumes the hard-coded index of the identifier

member-access: fix to correctly report the name for static methods/properties

---

src/rules/noConsecutiveBlankLinesRule.ts
test/rules/no-consecutive-blank-lines/test.ts.lint

Related: #1249
Now this rule will consider lines that only contain whitespace as "blank" lines.
NOTE: Currently the tests for this rule fail, but it's because I'm not fully understanding the test file syntax.  All the failures appear to be reported correctly, except for that it reports some extra failures that I can't figure out.  It seems to report an incorrect failure at the beginning for every failure that exists afterwards. Any help here would be appreciated!  Below is a screenshot of the console output.  Note the debug output at the beginning.

Fix for no-consecutive-blank-lines to also see whitespace

---

src/rules/noConsoleRule.ts

Fixing example of no-console rule

fix: no-console documentation example

---

usage/tslint-json/index.md

The [tslint.json format documentation](https://palantir.github.io/tslint/usage/tslint-json/) says:
> tslint.json configuration files may have comments in them (even though this is technically invalid JSON).
This PR documents what comment formats are allowed.

Fixed #1331: Documentation - comments in tslint.json files

---

package.json

TypeScript Compiler updates it version for release-2.0.0 [here](https://github.com/Microsoft/TypeScript/blob/master/package.json#L5) Update the peer dependency, so older node can install peer dependency correctly as this is currently broken TypeScript build

Update peer dependency for TypeScript nightly version of 2.0.0-dev

---

src/rules/orderedImportsRule.ts
test/rules/ordered-imports/case-insensitive/test.ts.lint
test/rules/ordered-imports/case-insensitive/tslint.json
test/rules/ordered-imports/lowercase-first/test.ts.lint
test/rules/ordered-imports/lowercase-first/tslint.json
test/tsconfig.json

Fixes #771
See test & rule metadata for how this works. No options for now, but I could imagine many different ways to order & group imports.

ordered-imports rule

---

src/tslint-cli.ts

MPEG transport streams also use the `.ts` file extension. Linting causes odd
effects, either by reporting spurious errors, or by timing out because the files
are commonly too large.

Ignore MPEG transport streams in tslint

---

src/enableDisableRules.ts
test/rules/_integration/enable-disable/test.ts.lint

Allow for tslint enable/disable rules to be specified without requiring a colon (':') delimiter before the list.

Fix #1269 - Too easy to disable all rules accidentally

---

src/language/rule/abstractRule.ts
src/language/rule/rule.ts
src/language/walker/ruleWalker.ts
src/rules/memberAccessRule.ts
src/rules/noMergeableNamespaceRule.ts
src/rules/noUnusedVariableRule.ts
src/rules/noUseBeforeDeclareRule.ts
src/rules/noVarRequiresRule.ts
src/tslint.ts

Small refactoring of constructors across code base to use parameter properties.
There was also a couple of places where constructors on derived classes were just passing arguments through to a base class with no additional logic, so i have removed those where I could see them.
Fixes #619

Use parameter properties to simplify constructors across codebase

---

src/configuration.ts
typings/findup-sync/findup-sync.d.ts

Now that TS propertly supports module targets.
@alexeagle needs this for angular licensing reasons.

Revert changes made to findup-sync during refactoring

---

package.json

We are updating our nightly version to be 2.1.0 tonight. [(merged PR)](https://github.com/Microsoft/TypeScript/pull/9615)

Update peer dependency to 2.1.0 as TypeScript nightly will be 2.1.0

---

src/configuration.ts
src/test.ts
test/rules/restrict-plus-operands/tslint.json

- only enable type checking during tests when `typeCheck: true` is configured
- fixes #1402 
I haven't documented this as a public API yet; we're only using it internally for tests. If we did want to make it public, we'd have to refactor tslint-cli.ts to read the configuration file before it tries to run the type checker on a program.

Add linterOptions to tslint.json

---

src/rules/noForInArrayRule.ts
src/tsconfig.json
test/rules/no-for-in-array/test.ts.lint
test/rules/no-for-in-array/tslint.json
test/tsconfig.json

Fixes #1380 
I would be interested in feedback on whether this is accurate:
```ts
const isArrayType = (type.flags & ts.TypeFlags.Reference) !== 0;
```
The `typescript.d.ts` file is quite terse about what a "Generic type reference" is, but in my testing it seems to correspond precisely to array types.

no-for-in-array rule

---

src/utils.ts

This allows the code to compile correctly with TS 1.8.x and TS 2.x
See https://github.com/Microsoft/TypeScript/pull/9855 also

Use correct type for tagged string function parameter

---

src/utils.ts

This allows the code to compile correctly with TS 1.8.x and TS 2.x
See https://github.com/Microsoft/TypeScript/pull/9855 also

Use correct type for tagged string function parameter (#1433)

---

src/formatterLoader.ts
src/lint.ts

I've added added additional type constraint for `formatter` in ILinterOptionsRaw interface and `findFormatter` function parameter name as it accepts the type Function, but was constrained to `string` only.

Added additional type constraint for findFormatter function parameter

---

src/language/rule/rule.ts
src/language/walker/ruleWalker.ts
src/rules/semicolonRule.ts
src/test.ts
test/check-bin.sh
test/files/fixes-test/test.ts.fix
test/files/fixes-test/test.ts.lint
test/files/fixes-test/tslint.json
test/files/incorrect-fixes-test/test.ts.fix
test/files/incorrect-fixes-test/test.ts.lint
test/files/incorrect-fixes-test/tslint.json
test/formatters/jsonFormatterTests.ts
test/rules/semicolon/always/test.ts.fix
test/rules/semicolon/enabled/test.ts.fix
test/rules/semicolon/ignore-interfaces/test.ts.fix
test/rules/semicolon/never/test.ts.fix

* Created IFix and IReplacement structures for representing fixes
* programWalker includes createFix and createReplacement
* Added optional parameter to createFailure for suggesting fixes
* Modified semicolon rule to suggest fixes (add / remove semicolon)
* Modified testing to check against a file with fixes applied
* If there is a ".ts.fix" file, then the test will take the first suggested fix and apply to the test file (without markup) and compare
Addresses #561

Add text replacement fixes for rules

---

src/rules/arrowParensRule.ts
test/rules/arrow-parens/test.ts.lint

arrow-parens rule shouldn't warn against generics

---

src/rules/whitespaceRule.ts

This change fixes a typo in `check-separator` option of whitespace rule.

Fix typo in whitespace rule enum

---

src/rules/commentFormatRule.ts
test/rules/comment-format/upper/test.ts.lint

Update comment-format/check-uppercase to ignore rule flags (fixes #1417)

---

src/language/walker/syntaxWalker.ts
src/rules/semicolonRule.ts
test/rules/semicolon/always/test.ts.lint
test/rules/semicolon/enabled/test.ts.lint
test/rules/semicolon/ignore-interfaces/test.ts.lint
test/rules/semicolon/never/test.ts.lint

This would require all `type t = foo;` to end with a semicolon.

Require semicolon for type alias

---

src/language/walker/syntaxWalker.ts
src/rules/semicolonRule.ts
test/rules/semicolon/always/test.ts.lint
test/rules/semicolon/enabled/test.ts.lint
test/rules/semicolon/ignore-interfaces/test.ts.lint
test/rules/semicolon/never/test.ts.lint

Reverts palantir/tslint#1475
Reverting this temporarily, as #1475 was a breaking change and we're experiencing some weirdness with tests.

Revert "Require semicolon for type alias"

---

src/tslint.ts

When input file is not a TypeScript code, `getSourceFile()` returns`undefined` but tslint doesn't handle it properly.  As the result, tslint raises an error which is not easy to understand when invalid soruce file is passed.
```
$ tslint mocha.opts
```
It raised below error:
```
/path/to/node_modules/tslint/lib/language/walker/ruleWalker.js:18
this.limit = this.sourceFile.getFullWidth();
```
I improved this error message by checking returned value from `getSourceFile` is valid or not. Improved error message is below:
```
Error: Invalid source code: test/mocha.opts
```
I didn't write a test for this yet because I couldn't find where I should add tests for `src/tslint.ts`.

Improve an error message on invalid source file

---

src/rules/noShadowedVariableRule.ts
test/rules/no-shadowed-variable/test.ts.lint

Fixes #1258 
Also I'm working on fix for #1099. Is it appropriate to send several fixes for one rule in one PR?

Fixes for no-shadowed-variable rule

---

.gitignore
src/rules/orderedImportsRule.ts
test/rules/ordered-imports/case-insensitive/test.ts.lint
test/rules/ordered-imports/lowercase-first/test.ts.lint
test/rules/ordered-imports/lowercase-first/tslint.json

Allow source imports to be evaluated similar to named imports

---

src/rules/arrowParensRule.ts
test/rules/arrow-parens/test.ts.lint

fix #1458 
I resolve following case.
```ts
const validAsync = async (param: any) => {};
const validAsync = async (param) => {};
```
I think should warn following case, but I have no idea to validate this. 
Do you have any Idea?
`const invalidAsync = async param => {};`

arrow-parens: fix async case

---

docs/_data/rules.json
docs/rules/adjacent-overload-signatures/index.html
docs/rules/file-header/index.html
docs/rules/object-literal-shorthand/index.html
docs/rules/only-arrow-functions/index.html
docs/rules/ordered-imports/index.html
docs/rules/typedef/index.html
docs/rules/whitespace/index.html

All changes are automatically generated from the rule metadata via the `grunt docs` command.

[docs] 3.15.0 docs update

---

src/rules/noVarKeywordRule.ts
test/rules/no-var-keyword/test.ts.lint

Fixes #1256
Test cases with extra whitespaces and comment added to ensure that new way to determine start of `var` keyword works correctly.
Also this is breaking changes and required update to mark one of previously existing test as failure ([line 35](https://github.com/palantir/tslint/commit/b4c2264e8e5dccb100b725a1cb96b3a3206de984#diff-94e704c2977ef54f582abd0ea7f9599dR35)).
One possible solution is to add argument `"allow-in-exports"` which will provide backward compatibility.

Update no-var-keyword to dissalow var in export statements (fixes #1256)

---

src/language/walker/syntaxWalker.ts
src/rules/arrayTypeRule.ts
src/tsconfig.json
test/rules/array-type/array/test.ts.fix
test/rules/array-type/array/test.ts.lint
test/rules/array-type/array/tslint.json
test/rules/array-type/generic/test.ts.fix
test/rules/array-type/generic/test.ts.lint
test/rules/array-type/generic/tslint.json
test/tsconfig.json

* Add ArrayType / ArrayTypeNode to SyntaxWalker
This rule doesn't use type checking to detect array aliases because the alias was likely defined purposefully.
cc: @alexeagle

Add ArrayType rule to enforce 'T[]' or 'Array<T>'

---

src/language/walker/syntaxWalker.ts

Added JSX Spread Attribute case statement

---

src/rules/arrayTypeRule.ts
test/rules/array-type/array/test.ts.fix
test/rules/array-type/array/test.ts.lint
test/rules/array-type/generic/test.ts.fix
test/rules/array-type/generic/test.ts.lint

Fixes now parenthesize union, intersection and function types.
Fixes #1523, will produce another PR for #1526.

Fix ArrayType to produce correct fixes

---

src/rules/commentFormatRule.ts
test/rules/comment-format/lower/test.ts.lint

JetBrains IDE’s (IntelliJ IDEA, WebStorm, PhpStorm, etc.) disabling
inspections by adding `//noinspection [rulenames]` before the
expression. This violates the rule of single-line comments must start
with a space.

JetBrains //noinspection whitelisted in comment-format space rule

---

docs/rules/file-header/index.html
src/rules/fileHeaderRule.ts

Old example was wrong (braces missing, regex wrong) and therefore misleading
Old example for file-header: `"file-header": "true", "Copyright \d{4}"`
New example for file-header: `"file-header": [true, "Copyright \\d{4}]"`

Fix misleading example for 'file-header'

---

src/rules/variableNameRule.ts
test/rules/variable-name/default/test.ts.lint

This option allows aliasing symbols, as long as the left hand side name
is identical to the right hand side name.
The use case is interoperating with legacy code that uses namespaces,
but still being able to abbreviate long namespaces in an ES6 module:
const SomeClass = some.long.namespace.SomeClass;
Another use case is exposing enums or other PascalCased objects to a
template in an Angular application (or similar environments):
class MyCtrl {
SomeEnum = SomeEnum;
}

variable-names: allow-aliases.

---

src/rules/jsdocFormatRule.ts
test/rules/jsdoc-format/jsdoc.ts.lint

There are 2 prime examples of comments that confuse tslint JSDoc detection regex:
A separator:
```typescript
class MyClass {
public prop1;
public prop2;
/********************************************/
constructor() { ... }
public method1() { ... }
public method2() { ... }
/********************************************/
private internal1() { ... }
}
```
and
```typescript
/**************
* my-file.ts *
**************/
```
These can be used as visual separator or guides, and are definitely not JSDocs.
Was also reported in issue #1121 several months ago.
Instead of matching any `/^\s*\/\*\*/`, I suggest that when there are more than 2 asterisks in a row, it should not be tested as a JSDoc comment.
Thus, the regex is updated to `/^\s*\/\*\*([^*]|$)/` which would accept `/**` followed by anything …

JSDoc rule should not block arbitrary comments like /********/

---

src/language/walker/syntaxWalker.ts
src/rules/trailingCommaRule.ts
test/rules/trailing-comma/multiline-always/test.ts.lint
test/rules/trailing-comma/multiline-never/test.ts.lint
test/rules/trailing-comma/singleline-always/test.ts.lint
test/rules/trailing-comma/singleline-never/test.ts.lint

Trailing comma rule now encompasses function decls, exprs and types

---

src/rules/curlyRule.ts

I noticed that some parts of `CurlyWalker::visitForOfStatement()` have typos pointing to the wrong type/method.

fix ForOf/ForIn typos in the CurlyWalker

---

src/formatters/proseFormatter.ts
test/formatters/proseFormatterTests.ts

https://github.com/palantir/tslint/pull/1472/commits/8fd8723586480f2396574072e5b467f8c096240e introduced a change
where the proseFormatter writes a single newline to stdout when there are no failures

print nothing when no failures

---

src/formatters/stylishFormatter.ts

Currently the stylish formatter prints *only* the first fileName, and then a list of lint errors from all files without specifying to which file they belong.
After this fix, each time a new file is reached, a new-line will be added, and then the name of the file, so each group of lint failures will be group with their fileName.

Stylish Formatter: output all file names

---

src/rules/arrayTypeRule.ts
test/rules/array-type/array-simple/test.ts.fix
test/rules/array-type/array-simple/test.ts.lint
test/rules/array-type/array-simple/tslint.json
test/rules/array-type/array/test.ts.fix
test/rules/array-type/array/test.ts.lint
test/rules/array-type/generic/test.ts.fix
test/rules/array-type/generic/test.ts.lint

Only use '[]' notation for 'simple' types.
Fixes #1526

Add array-simple option to array-type rule

---

README.md
package.json
src/language/utils.ts
src/test.ts
src/tslintMulti.ts

Breaking changes in compiler APIs broke the master branch. This is a simple workaround to get compilation working, but it forces us to depend on TS 2.0 (it doesn't compile with TS 1.8).
What do you think about bumping the peer dependency @JKillian?

Compile with TypeScript 1.8.10

---

docs/usage/tslint-json/index.md
src/configuration.ts

Drop support for configuration via package.json

---

src/rules/onlyArrowFunctionsRule.ts
test/rules/only-arrow-functions/allow-declarations/test.ts.lint
test/rules/only-arrow-functions/default/test.ts.lint

Currently the only way to write a generator function is with the `function` keyword, so it makes sense to allow this without requiring a flag.
This also appears to be the behavior of [eslint](http://eslint.org/docs/rules/prefer-arrow-callback).

Make only-arrow-functions allow generator functions

---

src/tslint-cli.ts

This is probably the smallest change ever but currently as mentioned in issue #1381, if you attempt to run `tslint` with a glob that is not restricted by a file extension (e.g. `src/**/*`) you get the following error:
> Error: EISDIR: illegal operation on a directory, read
This can be confusing to the user as it is not expected behaviour that a command line tool that parses files would consider folders. It had me stumped for a bit.
I have made a small change to ignore folders in globs. After making the change, when I run `tslint` again with no file extension specified I get:
> Error: Invalid source file: src/components/DrawerSelector/DrawerSelector.js. Ensure that the files supplied to lint have a .ts or .tsx extension.
This makes it much clearer that I need to specify `.ts` in my glob. …

Only return actual files from CLI glob. This fixes #1381

---

src/rules/noUnusedVariableRule.ts
test/rules/no-unused-variable/default/import.ts.fix
test/rules/no-unused-variable/default/import.ts.lint

Add fix for no-unused-variable, only for imports

---

src/rules/noVarKeywordRule.ts
test/rules/no-var-keyword/test.ts.fix

Note, we just replace with `let` which can cause errors if the identifier is referenced before the declaration or outside the scope. TypeScript will catch these at type-check time

add auto-fix for no-var-keyword

---

package.json
src/language/utils.ts
src/test.ts

Tested out the compiled TSLint with a peer of TS 1.8 (using `npm link`) and it still works, so we don't need to update the peer dependency.

Update NPM dependencies, compile with typescript v2.0.3

---

src/configs/recommended.ts
src/language/rule/rule.ts
src/ruleLoader.ts
src/rules/noUnusedVariableRule.ts
src/tslintMulti.ts

Resolves #1481. Adds a `deprecationMessage` field to rule metadata.

Deprecate no-unused-variable rule

---

src/rules/orderedImportsRule.ts
test/rules/ordered-imports/import-sources-any/test.ts.lint
test/rules/ordered-imports/import-sources-any/tslint.json
test/rules/ordered-imports/named-imports-any/test.ts.lint
test/rules/ordered-imports/named-imports-any/tslint.json

`TRANSFORMS#any` transforms every input name to the empty string, so that they always equal to each other, thus all names are always sorted.
Fixes #1600

Add "any" order transform for "ordered-imports" rule

---

README.md

Resolves #489 as a follow up to #1564
Unsure as to how much value there is having these two distinct sections for rules and formatters now seeing as both just point towards the gh-pages site. I can roll them into one section if that would be preferable.

Updated README.md Formatters

---

src/rules/noEmptyRule.ts
test/rules/no-empty/test.ts.lint

Fixing https://github.com/palantir/tslint/issues/1629

Fix no-empty rule on readonly modifier on parameters (#1629)

---

package.json

This PR adds `rimraf` module that makes `clean` task compatible with Windows.

Use rimraf to make clean task work on Windows

---

.gitignore

npm-debug.log file is generated by any npm tasks that returns with an error-code.
This file should not remain in git.

npm-debug.log in .gitignore

---

.vscode/settings.json

By default, VSCode uses its bundled TypeScript version which may change depending on VSCode version.
Also, it shows warnings when the globally installed TS version differs from the bundled one.
The solution is to instruct VSCode to always use the local TS version that is installed from packages.json in node_modules.

Make sure vscode uses locally provided Typescript

---

src/ruleLoader.ts

Currently deprecation messages are shown for each file when deprecated rule is used.
Therefore on projects where `no-unused-variable` rule is enabled developers will see long list with same deprecation message.
For example output from tests:
```
test/rules/no-unused-expression/test.ts.lint: Passed
test/rules/no-unused-new/test.ts.lint: Passed
no-unused-variable is deprecated. Use the compiler options --noUnusedParameters and --noUnusedLocals instead.
test/rules/no-unused-variable/check-parameters/test.ts.lint: Passed
no-unused-variable is deprecated. Use the compiler options --noUnusedParameters and --noUnusedLocals instead.
no-unused-variable is deprecated. Use the compiler options --noUnusedParameters and --noUnusedLocals instead.
no-unused-variable is deprecated. Use the compiler …
```

Show rule deprecation warning only once

---

package.json

Unfortunately I've added `rimraf` as production dependency in previous PR, but it is used only during build process and not required for package consumers.
This PR moves `rimraf` to `devDependencies` section.

Move rimraf to devDependencies

---

src/rules/objectLiteralSortKeysRule.ts
test/rules/object-literal-sort-keys/test.ts.lint

`object-literal-sort-keys` will skip single line objects
closes #1642

Rule object-literal-sort-keys to check multiline objects only (#1642)

---

src/rules/maxClassesPerFileRule.ts
test/rules/max-classes-per-file/one/test.ts.lint
test/rules/max-classes-per-file/two/test.ts.lint

Just an update to #1656 that adds support & tests for checking class expressions to the new `max-classes-per-file` rule
( I wasn't quick enough in my last PR!)

Adding class expression checks to max-classes-per-file rule

---

src/formatters/msbuildFormatter.ts
test/formatters/msbuildFormatterTests.ts

I added camel-cased rule name to the output of msbuild formatter since every line should contain an error code composed of letters and numbers (as shown here: https://blogs.msdn.microsoft.com/msbuild/2006/11/02/msbuild-visual-studio-aware-error-messages-and-message-formats/)

Add rule name to msbuild formatter output

---

src/language/utils.ts
src/rules/noNamespaceRule.ts
test/rules/no-namespace/allow-declarations/test.ts.lint

Note: I've been unable to test this properly as on my machine grunt for some reason picks up tsc 2.0.3, which fails to compile tslint.

fix: do not flag nested or .d.ts namespaces.

---

src/rules/semicolonRule.ts
test/rules/semicolon/always/test.js.lint
test/rules/semicolon/always/test.ts.fix
test/rules/semicolon/always/test.ts.lint
test/rules/semicolon/enabled/test.ts.fix
test/rules/semicolon/enabled/test.ts.lint
test/rules/semicolon/ignore-bound-class-methods/test.ts.fix
test/rules/semicolon/ignore-bound-class-methods/test.ts.lint
test/rules/semicolon/ignore-interfaces/test.ts.fix
test/rules/semicolon/ignore-interfaces/test.ts.lint
test/rules/semicolon/never/test.ts.fix
test/rules/semicolon/never/test.ts.lint

Only apply rule of arrows and semicolons on multiline functions
(optional)

Treat one-line arrow funcs like a normal statement regarding semicolons

---

src/rules/noUnusedVariableRule.ts
src/rules/orderedImportsRule.ts
test/rules/ordered-imports/case-insensitive/test.ts.fix
test/rules/ordered-imports/case-insensitive/test.ts.lint
test/rules/ordered-imports/import-sources-any/test.ts.fix
test/rules/ordered-imports/import-sources-any/test.ts.lint
test/rules/ordered-imports/lowercase-first/test.ts.fix
test/rules/ordered-imports/lowercase-first/test.ts.lint
test/rules/ordered-imports/named-imports-any/test.ts.fix
test/rules/ordered-imports/named-imports-any/test.ts.lint

_need a place to list fixers in docs_
Auto-fixer for import declarations, and the named declarations inside of them.
(optional)

Implement fixer for ordering import declarations

---

.vscode/tasks.json

previous file wasn't doing anything anyways, helps to make tslint debuggable in vscode

Update .vscode/tasks.json to use npm scripts

---

README.md

Also replaced `grunt` with some new `npm run` commands.
Cloning without endline config settings on Windows results in failed lint checks during tests because of different endline behavior. These are the same settings as https://github.com/microsoft/tslint-microsoft-contrib/#development.

Mentioned git --config settings in the README

---

test/executable/executableTests.ts
test/utils.ts

Currently build fails since normalized path returned from Node.js API (with `\` as path separator) is compared to deormalized one (with `/` as path separator, which is also valid on Windows) which was picked from TypeScript.
This PR fixes build on Windows by converting normalized path to denormalized and using it in comparison.
I've reviewed 3 possible solutions:
1. Normalize `fileName`'s when they are stored in `RuleFailure` class (used only in formatters) 
1. Normalize only absolute `fileName`'s when they are stored in `RuleFailure` class (probably rare case, but matches problem in test)
1. Use denormalized path in test
While first two solution fix problem, I think they bring almost no value and will lead to inconsistency in paths output between platforms.

Use denormalized path in test (fixes Windows build)

---

src/tslint-cli.ts
src/tslintMulti.ts
test/executable/executableTests.ts

There were three ways to pass globs in npm scripts were mentioned in #1639:
1. Without quotes `src/**/*.ts`
  - works on Windows (`src/**/*.ts` is passed to process and matching is done with `glob` module)
  - doesn't match all files on Linux (see #1678)
2. With single quotes `'src/**/*.ts'`
- works on Linux (`src/**/*.ts` is passed to process and matched with `glob` module)
- doesn't match anything on Windows since process receives quotes string as argument `'src/**/*.ts'` and `glob` returns no matches with quotes
3. With double quotes `"src/**/*.ts"`
- works both on Windows and Linux (`src/**/*.ts` is passed to process and matching is done with `glob` module)
  - requires escaping in `package.json file`  (e.g. `"lint": "tslint \"src/**/*.ts\""`) which hurts readability and might lead to …

Add support for glob patterns in single quotes for files and exclude arguments

---

src/formatters/stylishFormatter.ts
test/formatters/stylishFormatterTests.ts

I've updated the `stylish` formatter to have nicer looking colored output.
**Before**
**After**
🔹 Using a different color for the message and the file name helps to more easily distinguish them from each other
🔹 Using a grey color for the rule name de-emphasizes it since the file, position, and message are the most important pieces of information

Improve stylish formatter colors

---

package.json
src/tslint-cli.ts
src/updateNotifier.ts

I've added the functionality of the [update-notifier](https://github.com/yeoman/update-notifier) to have it display the update message when there is a new tslint version available. 
The functionality is inside a new file called 'updateNotifier.ts', to keep it separate and because I need to require the plugin as well as the package.json. The new function is implemented via the cli.
Do you think implementing the function call at this level is correct? 
My reasons for placing it here is because it then runs every time. The interval for checking a new version is set to three days (default is once a day).
I've tested it by setting the 'updateCheckInterval' to 0 and by lowering the version inside the package.json to '3.15.0', so it would trigger the check.
This triggers the image below:

Use update-notifier to notify of new versions #990

---

src/configuration.ts
src/utils.ts
test/config/tslint-custom-rules-with-two-dirs.json
test/configurationTests.ts
test/executable/executableTests.ts
test/ruleLoaderTests.ts

More intuitive configuration composition

---

src/language/rule/rule.ts
src/rules/adjacentOverloadSignaturesRule.ts
src/rules/cyclomaticComplexityRule.ts
src/rules/maxClassesPerFileRule.ts
src/rules/objectLiteralShorthandRule.ts
src/rules/preferForOfRule.ts

Make properties required to ensure that people think about them when adding new rules.

Make typescriptOnly and optionsDescription required on IRuleMetadata

---

src/rules/completedDocsRule.ts
test/rules/completed-docs/all/test.ts.lint
test/rules/completed-docs/all/tslint.json
test/rules/completed-docs/functions/test.ts.lint
test/rules/completed-docs/functions/tslint.json

Fixes https://github.com/Microsoft/tslint-microsoft-contrib/issues/162.
Enforces non-blank comments for any or all of classes, functions,
methods, and/or properties.

Added a completed-docs rule

---

src/rules/adjacentOverloadSignaturesRule.ts
test/rules/adjacent-overload-signatures/test.ts.lint

The adjacent-overload-signatures rule now works in situations other than interfaces and type literals.
I don't think this needs a documentation update, since the existing documentation doesn't say anything about being specific to just those.

Extend adjacent-overload-signatures to work in classes, source files, modules, and namespaces

---

src/ruleLoader.ts
src/tslintMulti.ts

This PR ensures that `jsRules` will be used for both `.js` and `.jsx` files. See https://github.com/palantir/tslint/pull/1634#pullrequestreview-8292214
Current `dedent` implementation isn't suitable for strings like `JS_ERROR_MESSAGE` since it calculates minimal indent for all lines and `.join("\n")` makes it 0.

Use jsRules for JSX files

---

src/updateNotifier.ts

error in `require` can happen if running outside of executable when `package.json` can't be found

ignore errors in update notifier

---

src/configs/recommended.ts
src/configuration.ts

Per the [docs](https://palantir.github.io/tslint/rules/no-duplicate-variable/) for `no-duplicate-variable` itself:
> This rule is only useful when using the var keyword - the compiler will detect redeclarations of let and const variables.
Given that `no-var-keyword` is already included in both configs, `no-deuplicate-variable` becomes redundant since `var` will never be allowed in those configs.

Removes `no-duplicate-variable` from the default & recommended configs

---

package.json
test/rules/trailing-comma/multiline-always/test.ts.fix
test/rules/trailing-comma/multiline-always/test.ts.lint
test/rules/trailing-comma/multiline-never/test.ts.fix
test/rules/trailing-comma/multiline-never/test.ts.lint

Upgrading TypeScript caused some test errors. I investigated, and it turns out the TypeScript in the test was invalid

Upgrade typescript to v2.0.10 and fix invalid typescript in comma tests

---

src/language/rule/typedRule.ts
src/linter.ts

Relax TypedRule detection:
- `TypedRule` exists to notify the consumer that they must implement the `applyWithProgram` method. 
- Checking `instanceof` is fragile, as is checking `constructor.name`.
- Checking [`isTypedRule`](https://github.com/palantir/tslint/issues/1637#issuecomment-254051190) makes the API bulkier, though it is more explicit, which is good. My rationale is if the consumer defined `applyWithProgram`, then the intention is to make the rule a typed rule, so an additional flag is probably not necessary.

Relax TypedRule detection (fix #1637, fix #1522)

---

src/index.ts

Changed the style of re-exporting variables.
This should provide better intellisense, since you're exporting a binding rather than a new variable. So you can now goto-definition on `AbstractRule` in every `extends Lint.Rules.AbstractRule`.

Simplify re-exports -- use `export { Foo }` syntax instead of `export var Foo = foo;`

---

package.json

Otherwise you see compilation errors on some of our d.ts files when installing tslint as a npm library

Need to add @types/node to reg dependencies since we use `Error` interface

---

.gitignore
docs/_posts/2016-11-17-new-for-4.0.md
docs/develop/custom-rules/index.md

Blog entry for 4.0

---

package.json

Revert "Need to add @types/node to reg dependencies since we use `Error` interface"

---

src/configuration.ts
src/test/lintError.ts

The problem: when using TSLint as an NPM library, you see error:
```
node_modules/tslint/lib/configuration.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
```
Why: @types/node augments the `Error` interface that was initially defined by TypeScript's `lib.d.ts`. Since the use of this interface is exported by TSLint, the app using TSLint must also include @types/node. Sadly, the property added by Node is currently already defined by `lib.d.ts`
The fix: Don't export the @types/node `Error` interface and define/use our own similar interface.

Create local Error interface so that node doesn't need to be externally referenced

---

src/rules/objectLiteralKeyQuotesRule.ts
test/rules/object-literal-key-quotes/as-needed/test.js.lint
test/rules/object-literal-key-quotes/as-needed/test.ts.lint

* The bug in #1761 appears to be rooted in `IDENTIFIER_NAME_REGEX` using a `*` instead of `+` repeat modifier. This has been addressed.
* I added a test case for `''` in the `"as-needed"` files.
I don't know enough about the spirit of "consistent" or "consistent-as-needed" to know if this case should be flagged as a failure or not:
```typescript
const uncertain = {
foo: 'bar',
'': 'baz',
};
```
Right now, this test fails in both cases. It seems like this is correct, but I welcome confirmation. Once I have it I'll update the tests.

Special case the empty string in object-literal-key-quotes rule

---

docs/_data/rules.json
docs/rules/no-unused-variable/index.html
src/configuration.ts
src/error.ts
src/test/lintError.ts
src/tslint-cli.ts

fixes #1759
3rd party apps should be able to see the fatal errors thrown by the API. #1686 changed it so that the error was caught and added as a property to IConfigurationLoadResult. It's not reasonable for 3rd party apps to be aware of this property, so we should follow convention and throw an unhandled exception that the app itself can handle.
This change creates a new FatalError class which is caught in `tslint.cli`.

Fatal errors from API should be unhandled and caught in tslint-cli

---

src/rules/preferForOfRule.ts
test/rules/prefer-for-of/test.ts.lint

fixes #1753
use walker instead of regex to determine usage of index variable
more validation, less fragile
more restrictive in suggesting `for-of` when multiple statements are in initializer, condition, or incrementer
allows for different ways of incrementing
old code had false positives:
```
for(let x = 0; NOTX < arr.length; x++) {}
for(let x = 0; x < arr.length; x--) {}
for(let x = 0; x <= arr.length; x++) {}
for(let x = 1; x < arr.length; x++) {}
for(let x = 0; x < arr.length; x+=11) {}
```
and crashes on:
```
for(let x = 0; true; x++) {}
for(let x = 0; x < arr.length;) {}
````

Rewrite `prefer-for-of` rule

---

src/rules/adjacentOverloadSignaturesRule.ts
test/rules/adjacent-overload-signatures/test.ts.lint

fix `adjacent-overload-signatures` to treat static as non-overload

---

src/rules/onlyArrowFunctionsRule.ts
test/rules/only-arrow-functions/allow-declarations/test.ts.lint
test/rules/only-arrow-functions/default/test.ts.lint

Fixes #1513
This requires TypeScript 2.0 to parse the `this` parameters.
Changes to `package.json`, `src/test.ts`, and `src/language/utils.ts` are quick fixes to get it working with 2.0.
Merging this should wait until tslint has been properly upgraded to 2.0.

[2.0] Make only-arrow-functions allow functions with a `this` parameter

---

src/runner.ts
src/tslint-cli.ts

Fixes #1675.
tslint-cli.ts takes in arguments using optimist and converts them to a friendlier object to pass to a CliRunner. The rest of the logic that used to be in tslint-cli.ts is now in the CliRunner.
Notes:
* I really wanted to make `CliRunner::run` return a `Promise<number>`, but didn't want to add new dependencies or change the output target.
* I tried to stick to the existing code style for the cut-and-pasted code. If you'd like it changed I'm up for that too.
* I'm not confident in `CliRunner` as a name. Alternate suggestions, anyone?

Split CLI into tslint-cli and a Runner class

---

src/rules/noInternalModuleRule.ts
test/rules/no-internal-module/test.ts.lint

Fixes #939.
A couple of notes:
* @adidahiya suggested also including the module name in the failure. This doesn't since IMO the failure is just on the `module` keyword, not the name... but I'm not opposed to also including the name if asked.
* This blindly uses `node.getText().indexOf("module")` to determine where to start the error, since the logic for parsing `declare ` and `declare    ` could get a little complex.

Narrowed no-internal-module failure to the keyword

---

src/rules/noUseBeforeDeclareRule.ts
test/rules/no-use-before-declare/test.ts.lint

As I stated in [comment](https://github.com/palantir/tslint/issues/1400#issuecomment-249458412) for issue #1400 - difference with TS 2.x because `languageService.getDocumentHighlights` highlights not only nodes for `ITest` but also for `unknown`. I don't know if it is regression in TS or how it is supposed to filtered in new way.
This fix tracks positions for imported properties and prevents errors if it is "highlighted" as use before declarations.
I'd be glad to improve fix if you have any suggestions.

Workaround for #1400. Excludes imported properties from error

---

src/language/utils.ts

Avoid compiler error with strictNullChecks.
hasModifier already checks for null and undefined.
This commit adds types null and undefined to the modifiers parameter.

Fix parameter type of hasModifier

---

src/runner.ts
src/tslint-cli.ts

CLI arguments that were actually boolean flags but weren't marked as such would swallow the next argument, even if it was another flag.
For example `tslint --type-check --project x` would set `type-check`="--project"
Marking these as boolean with *optimist* also ensures that the value is either true or false... and not undefined

Make CLI arg types stronger

---

src/rules/quotemarkRule.ts
test/rules/quotemark/double-avoid-escape/test.ts.fix
test/rules/quotemark/double/test.ts.fix
test/rules/quotemark/jsx-double/test.tsx.fix
test/rules/quotemark/jsx-single/test.tsx.fix
test/rules/quotemark/single-avoid-escape/test.ts.fix
test/rules/quotemark/single/test.ts.fix

Added fix for the `quotemark` rule.
(optional)

Implemented fix for quotemark rule

---

src/language/walker/blockScopeAwareRuleWalker.ts
src/language/walker/scopeAwareRuleWalker.ts

Treat `SourceFile` as scope boundary only if it is an external module

---

src/formatters/checkstyleFormatter.ts
test/formatters/checkstyleFormatterTests.ts

Found an issue when integrating tslint with jenkins (using checkstyle formatter), the formatter did not generate separate file nodes in the outputted XML, instead simply reporting all errors under the first file.
To fix this I:
- Modified checkstyleFormatter.ts to sort failures by filename, and generate file nodes for each unique filename
- Modified test case to test failures in multiple files
The checkstyleFormatter test was reusing another formatter's test input file, I've followed this pattern to add a second file in the test. It might be better to create two test input files specifically for the checkstyleFormatter...

Support multiple files in checkstyle formatter

---

src/rules/trailingCommaRule.ts
test/rules/trailing-comma/multiline-always/test.ts.fix
test/rules/trailing-comma/multiline-always/test.ts.lint
test/rules/trailing-comma/multiline-never/test.ts.lint
test/rules/trailing-comma/singleline-always/test.ts.fix
test/rules/trailing-comma/singleline-always/test.ts.lint
test/rules/trailing-comma/singleline-never/test.ts.lint

Typescript disallows trailing commas in type parameter lists, both on declaration and invocation. Linting should not flag this case as fixing the lint error would introduce a compiler error.
See https://github.com/palantir/tslint/issues/1769

Do not apply trailing comma rule to type parameter lists

---

docs/_data/formatters.json
docs/_data/rules.json
docs/formatters/codeFrame/index.html
docs/usage/cli/index.md
src/formatters/codeFrameFormatter.ts
src/formatters/index.ts
src/language/rule/rule.ts
src/tslint-cli.ts
test/files/formatters/codeFrameFormatter.test.ts
test/formatters/codeFrameFormatterTests.ts

Add the new `codeFrame` formatter.
This is how it looks on real code: 
A questions: Do you have a place to define modules for npm dependencies that don't have `@types` yet? I like to use `import` for babel-code-frame

Add CodeFrame Formatter

---

src/language/utils.ts
src/rules/preferConstRule.ts
src/rules/preferForOfRule.ts
test/rules/prefer-for-of/test.ts.lint

False positive in `prefer-for-of` rule when element assigned

---

src/language/utils.ts
src/rules/noInferredEmptyObjectTypeRule.ts
test/rules/no-inferred-empty-object-type/test.ts.lint
test/rules/no-inferred-empty-object-type/tslint.json

Introduced a rule which checks for type inference being {} (empty object type) and then throws an error, this PR is based on discussions in the issue mentioned above. @myitcv any comments on how we can improve this?

[WIP] empty object type inference

---

src/rules/strictBooleanExpressionsRule.ts
test/rules/strict-boolean-expressions/test.ts.lint
test/rules/strict-boolean-expressions/tslint.json

Introduced a rule to type check boolean expressions using type aware rules. This rule checks if the given binary expression, if statement, while statement or for statement comprises of correctly formed boolean expressions or literals. This is a first cut of the implementation and would like to get feedback on how to improve this and finally make this rule a part of the tslint rule set.
@myitcv tagging you here since we both discussed this rule offline, @adidahiya any feedback is welcome on how we can improve this.

strict boolean expressions

---

docs/_data/rules.json
docs/rules/no-magic-numbers/index.html
docs/rules/promise-function-async/index.html
src/rules/noMagicNumbersRule.ts
test/rules/no-magic-numbers/custom/test.js.lint
test/rules/no-magic-numbers/custom/test.ts.lint
test/rules/no-magic-numbers/custom/tslint.json
test/rules/no-magic-numbers/default/test.js.lint
test/rules/no-magic-numbers/default/test.ts.lint
test/rules/no-magic-numbers/default/tslint.json

Added a rule to prevent _magic numbers_.
See the added tests for examples.
Basic usage: `"no-magic-numbers": true` disallows all except 0 and 1/-1.
Custom allow list: `"no-magic-numbers": [true, 1337, 1338]"` Only 1337 and 1338 are allowed.
I am not very familiar with tslint and the TS API and it would love to get feedback on the filter method.

Added no-magic-numbers rule

---

src/rules/onlyArrowFunctionsRule.ts
test/rules/only-arrow-functions/allow-named-functions/test.js.lint
test/rules/only-arrow-functions/allow-named-functions/test.ts.lint
test/rules/only-arrow-functions/allow-named-functions/tslint.json

Fixes #1509
Added an `allow-named-functions` option that allows function expressions with names.

Add "allow-named-functions" option for only-arrow-functions

---

src/rules/completedDocsRule.ts

Explained in title -- solely documentation; no code changes.
---
If you assume (wrongly) as I did, that the implied format is `[true, ["classes", "methods"]]`, the rule will "run" with all check types disabled. Oops. :D

Remove extra bracket in completed-docs example

---

docs/_data/rules.json
docs/rules/cyclomatic-complexity/index.html
docs/rules/no-empty-interface/index.html
src/rules/noEmptyInterfaceRule.ts
test/rules/no-empty-interface/test.ts.lint
test/rules/no-empty-interface/tslint.json

Added the `no-empty-interface` rule. This forbids interfaces with no members.
If `docs` is generated from `src`, why is it checked in?
Also, should this be part of `tslint:latest`?

Add `no-empty-interface` rule

---

docs/rules/array-type/index.html
src/rules/arrayTypeRule.ts

The generated docs page for this rule is missing string quotes, so a copy/paste of the rule into `tslint.json` fails.
(optional)

Fix string quotes on docs rule array-type

---

src/rules/oneLineRule.ts
test/rules/one-line/all/test.js.lint
test/rules/one-line/all/test.ts.lint
test/rules/one-line/none/test.js.lint
test/rules/one-line/none/test.ts.lint

Fixes #400.
Stop `one-line` from reporting an error for `else` when there are no braces.

Don't error for misplaced braces for 'else' if there are no braces

---

src/language/walker/ruleWalker.ts
src/rules/alignRule.ts
src/rules/jsdocFormatRule.ts
src/rules/noEmptyRule.ts
src/rules/noMergeableNamespaceRule.ts
src/rules/noSwitchCaseFallThroughRule.ts
src/rules/objectLiteralSortKeysRule.ts
src/rules/oneLineRule.ts
src/rules/orderedImportsRule.ts

Made a minor change for performance. `getSourceFile` isn't good to call repeatedly from deep within a tree, especially when the source file is already a field of the class. https://github.com/Microsoft/TypeScript/blob/master/src/compiler/utilities.ts#L153

Replace `node.getSourceFile()`, which climbs ancestors, with the `sourceFile` field on a RuleWalker.

---

src/rules/objectLiteralKeyQuotesRule.ts
test/rules/object-literal-key-quotes/always/test.js.lint
test/rules/object-literal-key-quotes/always/test.ts.lint

Rewrote `object-literal-key-quotes` to process all properties at once instead of using state on the Walker object. It no longer stores failures in an array, instead adding them immediately.
The line `node.properties.filter(({ kind }) => kind !== ts.SyntaxKind.MethodDeclaration);` is just for backwards-compatibility. Not sure when it would be OK to introduce a breaking change of this kind, but I don't see why MethodDeclarations should be an exception to the rule. It seems like a result of the fact that the previous implementation used `visitPropertyAssignment`, skipping over MethodDeclarations implicitly.

Refactor object-literal-key-quotes rule

---

docs/rules/no-string-throw/index.html
src/rules/noStringThrowRule.ts
test/rules/no-string-throw/test.js.lint
test/rules/no-string-throw/test.ts.lint
test/rules/no-string-throw/tslint.json

I've added a rule that detects when a throw statement has a string literal, which does not produce a proper stack trace. The suggested fix is to change `throw 'string'` to `throw new Error('string')`. I didn't see an existing issue for this, but can create one if needed.

add rule to detect throwing of string literals

---

docs/_data/rules.json
docs/rules/arrow-parens/index.html
docs/rules/interface-over-type-literal/index.html
docs/rules/no-void-expression/index.html
src/rules/noVoidExpressionRule.ts
test/rules/no-void-expression/test.js.lint
test/rules/no-void-expression/test.ts.lint
test/rules/no-void-expression/tsconfig.json
test/rules/no-void-expression/tslint.json

Added the `no-void-expression` rule, which requires that any expression of type `void` go on its own line as a statement.

Add `no-void-expression` rule

---

docs/_data/rules.json
docs/rules/arrow-parens/index.html
docs/rules/interface-over-type-literal/index.html
src/rules/noNamespaceRule.ts
test/rules/no-namespace/allow-declarations/test.d.ts.lint
test/rules/no-namespace/allow-declarations/test.ts.lint
test/rules/no-namespace/default/test.d.ts.lint

Simplified the `no-namespace` implementation.
It no longer recurses through modules.
No need to recurse through declarations because they can only contain other declarations.
No need to recurse through non-declarations because we would have added a failure for the root namespace anyway.
**EDIT**: actually, it looks like this does *not* fix #1833. That was already fixed, probably by #1836.

Simplify no-namespace implementation and add tests for `declare global` and declaration files.

---

src/enableDisableRules.ts

To get the end of the `next-line` switch, tslint searches for the start of the line after the next line. If there is no such line, tslint crashed.
This change checks, if the line in question exists. You can now use the next-line switch without even having a next line (which doesn't make sense at first glance, but is useful when linting live during development)
(optional)

Handle eof in line switches

---

src/rules/preferConstRule.ts
test/rules/prefer-const/test.ts.fix
test/rules/prefer-const/test.ts.lint

Supported `({ x } = obj)` mutation statements in the `prefer-const` rule.

Support object-destructuring mutation in prefer-const

---

src/language/utils.ts
src/language/walker/blockScopeAwareRuleWalker.ts
src/rules/preferConstRule.ts
test/rules/prefer-const/test.ts.fix
test/rules/prefer-const/test.ts.lint

fixes error related to usage of forward references in `prefer-const` rule
After this change list of variable declarations in block scope is collected immediately after entering the scope. This prevents cases when variable is syntactically located after its usage

handle forward referenced in prefer-const rule

---

src/rules/adjacentOverloadSignaturesRule.ts
test/rules/adjacent-overload-signatures/test.ts.lint

Fixes  #1831
Previously we used the name of an overload as the key. This caused problems for static and non-static properties conflicting, so #1772 was necessary. But that solution would give ugly error messages for conflicting static overloads. The new solution passes the pretty name separately from the key, so it avoids that problem.
(#1831 occured because the solution in #1772 had a problem when `nameText` was undefined: it would compute `undefined + ""`, which isnt' itself undefined. This could be fixed by simply checking for `undefined` before adding `suffix`, but I think this more complex PR is a better solution in the long run.)

Properly handle computed/static property names

---

src/rules/noConsecutiveBlankLinesRule.ts
test/rules/no-consecutive-blank-lines/default/test.ts.lint

Find all template strings in AST and use their start and end position as disabled interval to filter failures.
Expressions inside the template string are still checked for consecutive blank lines. See added test cases.

Allow consecutive blank lines in template strings

---

src/rules/objectLiteralKeyQuotesRule.ts
test/rules/object-literal-key-quotes/as-needed/test.ts.lint
test/rules/object-literal-key-quotes/consistent-as-needed/test.ts.lint

Check an object's property has a name actually because property expanding with rest operator does not have a name.
nothing special

Consider rest operator in object literal in `object-literal-key-quotes` rule

---

src/rules/restrictPlusOperandsRule.ts
test/rules/restrict-plus-operands/test.ts.lint

Fix restrict-plus-operands for ternary ops

---

src/language/walker/blockScopeAwareRuleWalker.ts
src/rules/preferForOfRule.ts
test/rules/prefer-for-of/test.ts.lint

Make `prefer-for-of` block scope aware

---

src/rules/objectLiteralKeyQuotesRule.ts
test/rules/object-literal-key-quotes/always/test.js.fix
test/rules/object-literal-key-quotes/always/test.ts.fix
test/rules/object-literal-key-quotes/as-needed/test.js.fix
test/rules/object-literal-key-quotes/as-needed/test.ts.fix
test/rules/object-literal-key-quotes/consistent-as-needed/test.js.fix
test/rules/object-literal-key-quotes/consistent-as-needed/test.ts.fix

Added fixes for `object-literal-key-quotes` (except in `consistent` mode, where a fix would be ambiguous).
This always uses double quotes. Might it be possible to peer into the setting for `quotemark` and choose quotes accordingly?

Add fix for object-literal-key-quotes

---

src/rules/arrowParensRule.ts
test/rules/arrow-parens/ban-single-arg-parens/test.ts.fix
test/rules/arrow-parens/ban-single-arg-parens/test.ts.lint

Allowed binding patterns in `arrow-parens`.
Why are async functions excluded from this rule?
**EDIT**: Looks like that was a kludge (#1479). Added support for async functions.

arrow-parens: Allow binding patterns `([x, y]) => ...` and `({x, y}) => ...` to have parens

---

src/language/utils.ts
src/rules/curlyRule.ts
src/rules/memberAccessRule.ts
src/rules/oneLineRule.ts
src/rules/semicolonRule.ts
src/rules/spaceBeforeFunctionParenRule.ts
src/rules/trailingCommaRule.ts
src/rules/typedefWhitespaceRule.ts
src/rules/whitespaceRule.ts

Added a helper function for a common need.
Note that this function may be unperformant since it calls `getChildren`. But it's no worse than before. (At least it's better than `.filter(...)[0]`.)

Add `childOfKind` helper function

---

src/rules/eoflineRule.ts
test/rules/eofline/comment/test.js.lint
test/rules/eofline/comment/test.ts.lint
test/rules/eofline/comment/tslint.json
test/rules/eofline/disabled/test.js.lint
test/rules/eofline/disabled/test.ts.lint
test/rules/eofline/disabled/tslint.json
test/rules/eofline/empty/tslint.json
test/rules/eofline/invalid/test.js.lint
test/rules/eofline/invalid/test.ts.lint
test/rules/eofline/invalid/tslint.json
test/rules/eofline/only-whitespace/test.js.lint
test/rules/eofline/only-whitespace/test.ts.lint
test/rules/eofline/only-whitespace/tslint.json
test/rules/eofline/valid/test.js.lint
test/rules/eofline/valid/test.ts.lint
test/rules/eofline/valid/tslint.json
test/rules/eofline/whitespace/test.js.lint
test/rules/eofline/whitespace/test.ts.lint
test/rules/eofline/whitespace/tslint.json

Add tests.
Allow disabling the rule.
Use SourceFile's text instead of EndOfFileToken.
I'd like to get feedback, if checking for `\n` is a problem on systems where only `\r` is used (macOS?).
The original code was also checking for `\n`, but only if the line before EOF contained only comments or whitespace.

Rewrite eoflineRule

---

src/rules/objectLiteralKeyQuotesRule.ts
src/rules/semicolonRule.ts
test/rules/semicolon/always/test.ts.fix
test/rules/semicolon/always/test.ts.lint
test/rules/semicolon/enabled/test.ts.lint
test/rules/semicolon/ignore-bound-class-methods/test.ts.fix
test/rules/semicolon/ignore-bound-class-methods/test.ts.lint
test/rules/semicolon/ignore-interfaces/test.ts.fix
test/rules/semicolon/ignore-interfaces/test.ts.lint
test/rules/semicolon/never/test.ts.fix
test/rules/semicolon/never/test.ts.lint

This PR adds new error if interface member has comma instead of semicolon after it and proper fix that replaces comma.
Developers still can use `ignore-interfaces` option to skip commas in interfaces.
Thanks to @greglo for failing test case.

Semicolon comma fix (fixes #1856) 

---

src/rules/noEmptyRule.ts

Rewrite for performance:
Return early if block has statements.
Simplify skipping constructors with parameter properties.
Pass SourceFile as parameter to node.getChild* methods.

Rewrite noEmptyRule

---

src/rules/onlyArrowFunctionsRule.ts
test/rules/only-arrow-functions/allow-named-functions/test.js.lint
test/rules/only-arrow-functions/allow-named-functions/test.ts.lint
test/rules/only-arrow-functions/default/test.ts.lint

* Allow function declarations with `allow-named-functions`
* you could argue, that one could simply use `allow-declarations`, but function declarations are also _named_
* maybe this commit could just be replaced with a documentation update, as I was not expecting the current behaviour by reading the docs
* fix error location for `async` or `export`ed functions
* cache lookup of options
~~The ci failure will go away when #1960 get's merged and this branch is rebased~~ ... and it's gone

Fix only-arrow-functions

---

src/configs/latest.ts

Enabled additional rules in the `tslint:latest` config.

Update tslint:latest config

---

src/language/walker/ruleWalker.ts
src/rules/arrayTypeRule.ts
src/rules/arrowParensRule.ts
src/rules/noAngleBracketTypeAssertionRule.ts
src/rules/noStringThrowRule.ts
src/rules/noVarKeywordRule.ts
src/rules/objectLiteralKeyQuotesRule.ts
src/rules/orderedImportsRule.ts
src/rules/preferConstRule.ts
src/rules/quotemarkRule.ts
src/rules/semicolonRule.ts
src/rules/spaceBeforeFunctionParenRule.ts
src/rules/trailingCommaRule.ts

Simplify the usage of `RuleWalker.prototype.createFix` to use rest parameter instead of passing an array explicitly. Most of the time only one replacement is needed and it is really awkward to need to wrap it in brackets.
This method is not yet part of any release so it's not a breaking change.

Simplify RuleWalker.prototype.createFix

---

src/tslint-cli.ts

Otherwise a call stack is printed for the handled error, making it look like a crash

Throw a string, not Error, since Optimist expects a string

---

src/configs/latest.ts

Rule shows false positive in callbacks defined outside of a class and assigned methods (https://github.com/palantir/tslint/issues/1544)
Also, `--noImplicitThis` takes care of the problem the rule addresses

Disable `no-invalid-this` in tslint:latest

---

src/rules/noMagicNumbersRule.ts
test/executable/executableTests.ts
test/rules/no-magic-numbers/default/test.ts.lint

Allowed "magic" numbers to appear inside parameters.

no-magic-numbers: Allow default parameter values to be number literals

---

src/rules/whitespaceRule.ts
test/rules/whitespace/all/test.js.lint
test/rules/whitespace/all/test.ts.fix
test/rules/whitespace/all/test.ts.lint
test/rules/whitespace/all/tslint.json
test/rules/whitespace/none/test.ts.lint

Also added fixes for inserting spaces and updated tests
I added the option to verify there is whitespace immediately before the opening brace of a block node. I also added fixes for the missing whitespace characters.

Added "check-preblock" option to whitespace rule

---

docs/_data/rules.json
docs/rules/comment-format/index.html
src/rules/unifiedSignaturesRule.ts
test/rules/unified-signatures/test.ts.lint

Don't include anything with a `body` when checking `unified-signatures`.

unified-signatures: Don't count a function/method declaration as an overload if it has a body.

---

src/configs/latest.ts

`asyncArrow` to `always` for `space-before-function-paren` rule

Update space-before-function-paren in latest.ts (#2001)

---

docs/_data/rules.json
docs/rules/comment-format/index.html
src/rules/quotemarkRule.ts

Cleaned up `quotemarkRule.ts`.
`isEnabled()` is still ugly. We need a solution that allows us to declaratively describe the options and get back the parsed options, without calling `hasOptions` over and over again.

Clean up quotemarkRule.ts

---

src/rules/noInferrableTypesRule.ts
test/rules/no-inferrable-types/default/test.ts.lint
test/rules/no-inferrable-types/ignore-params/test.ts.lint

In particular, call out that only trivially inferred types of literals
should be left out, not every type that's inferrable.
Wordsmith the error message for no-inferrable-types to make it easier to understand for users why this is considered lint, and when they should use types that could be inferred.

Wordsmith the error message for no-inferrable-types a bit

---

docs/_data/rules.json
docs/rules/prefer-method-signature/index.html
src/rules/preferMethodSignatureRule.ts
test/rules/prefer-method-signature/test.ts.fix
test/rules/prefer-method-signature/test.ts.lint
test/rules/prefer-method-signature/tslint.json

Added the `prefer-method-signature` rule, which recommends to use `foo(): void` over `foo: () => void`.
It looks like these will be semantically equivalent in TS2.2. (And were in 2.0.) https://github.com/Microsoft/TypeScript/issues/13148#issuecomment-270204165

Add `prefer-method-signature` rule

---

docs/_data/rules.json
docs/rules/whitespace/index.html
src/rules/noMagicNumbersRule.ts
test/rules/no-magic-numbers/custom/test.ts.lint

Changed to avoid calling `node.getText()` for every number literal.

no-magic-numbers: Make condition lazy (don't call `.getText()` for every number literal in the file)

---

_sass/_cayman.scss
css/main.scss

This makes it easier, when reviewing rules doc, to see which rules you've seen and which ones you haven't (which is what I ran into). I calculated a color for visited links based on the normal link color using [the Adobe colors tool](https://color.adobe.com/create/color-wheel/?base=2&rule=Analogous&selected=1&name=My%20Color%20Theme&mode=rgb&rgbvalues=0.11764705882352941,0.4196078431372549,0.7215686274509804,0.48953863636362566,0.04550000000000004,0.91,1,0,0,0.91,0.5224758680556909,0.04550000000000004,1,0.9457325268814998,0.050000000000000044&swatchOrder=0,1,2,3,4).

Change color for visited links

---

src/enableDisableRules.ts
src/language/utils.ts
src/rules/commentFormatRule.ts
src/rules/jsdocFormatRule.ts
src/rules/noTrailingWhitespaceRule.ts
src/rules/whitespaceRule.ts
test/rules/_integration/enable-disable/test.tsx.lint
test/rules/_integration/react/test.tsx.lint
test/rules/comment-format/lower/test.tsx.lint
test/rules/whitespace/all/test.ts.fix
test/rules/whitespace/all/test.ts.lint

Scanning the whole source file is very fragile, because the grammar is not context free. You had to skip certain ranges, that were known to cause trouble. For example regex literals or template expressions.
This approach is prone to errors, as it didn't cover all cases and has to adopt new grammar as the language adds it.
The new function hands the scanning and parsing off to the parser and only iterates over the tokens of all AST nodes. Skipping ranges is no longer necessary.
This fixes #2007 and replaces #2009 (I took 2 commits from that PR to include the contained tests)
For more information please refer to the description of each individual commit.
This is a rather big PR. I could split it into several smaller ones if you want.
`WhitespaceRule` used to skip `TemplateExpression`, …

Introduce alternative to SkippableTokenAwareRuleWalker and scanAllTokens

---

docs/_data/rules.json
docs/rules/whitespace/index.html
src/language/utils.ts

This commit can be reverted once tslint drops support for typescript 2.0.10
Fixes #2054
(give an overview)
(optional)

Ensure backwards compatibility of #2036

---

src/rules/noEmptyInterfaceRule.ts
test/rules/no-empty-interface/test.ts.lint

Allow empty interfaces with 2 or more parents as they can be used like intersection types.

Allow empty interfaces with 2 or more parents

---

src/rules/noFloatingPromisesRule.ts
test/rules/no-floating-promises/jquerypromise/test.ts.lint
test/rules/no-floating-promises/jquerypromise/tslint.json
test/rules/no-floating-promises/promises/test.ts.lint
test/rules/no-floating-promises/promises/tslint.json

Promises must be stored or passed to a function.
The idea here is that floating (unhandled) Promises can cause unexpected behavior. For example, in tests, they might resolve at unexpected times (like after another test following their parent test has started).
Fixes https://github.com/Microsoft/tslint-microsoft-contrib/issues/174 (PRing here because I'm not sure they support the type checker).

New rule: no-floating-promises

---

README.md
src/runner.ts
src/test.ts
src/tslint-cli.ts

Used an extra `glob.sync` to allow for wildcards / general glob patterns from `--test`.
A couple of issues I think should be addressed before merge:

Changed --test to take multiple directories

---

src/rules/noTrailingWhitespaceRule.ts
test/rules/no-trailing-whitespace/test.js.fix
test/rules/no-trailing-whitespace/test.ts.fix
test/rules/no-trailing-whitespace/test.ts.lint

Detect trailing whitespace in comments.
Detect trailing whitespace before EOF.
Add fixer.
(optional)

Fix no-trailing-whitespace for comments and EOF

---

circle.yml
scripts/assertMinCircleNodes.js

We run using 4 nodes so that each node can test a different environment. Since forks default to 1 node, we don't get full coverage from PRs unless parallelism is set to 4 or more
Environments:
- node 4.2
- node 5.7
- node 6.1
- TypeScript 2.0.10

Fail build if CircleCI parallelism < 4

---

README.md

Updated the README example of using tslint as library. It basically explicitly calls `findConfiguration` before calling `lint` API so that `extends` key is resolved correctly.
(optional)
cc: @adidahiya

Fix README to correctly show example of using tslint as library

---

docs/usage/rule-flags/index.md
src/enableDisableRules.ts
src/linter.ts
test/rules/_integration/enable-disable/test.ts.lint
test/rules/_integration/enable-disable/tslint.json

* Add minor clarification to line switches documentation.
* Split up methods into maintainable chunks of code
* Fix bugs to make behaviour as described in the docs:
* `enable-line` and `disable-line` switched from the start of the line only to the end of the comment. That is correct for single line comments, but multiline comments can be followed by other statements.
* `enable-next-line` and `disable-next-line` switched from the start of the comment instead of the start of the next line.
* handling of multiline comment end
* `/*tslint:disable foo bar*/` removed `bar*/` resulting in swiching only `foo`
* `/*tslint:disable foo*/` removed `foo*/` resulting in switching **all rules**
* `/*tslint:disable:foo*/` tried to switch rule `foo*/`, which does not exist -> nothing changed
* add tests …

Rewrite and fix EnableDisableRulesWalker

---

src/rules/noInferrableTypesRule.ts
test/rules/no-inferrable-types/default/test.ts.lint

Currently, the noInferrableTypes check only runs on variables and parameters, not on property declarations:
```ts
class X {
f: string = 'string'; // not checked :-(
}
```
Compilation and tests fail on my local machine for unrelated reasons, let's hope CircleCI can run this?

noInferrableTypes: check property declarations.

---

src/rules/noUnboundMethodRule.ts
test/rules/no-unbound-method/test.ts.lint
test/rules/no-unbound-method/tslint.json

Added the `no-unbound-method` rule, which forbids the use of `x.foo` where `foo` is a method on a class or interface, but allows `y => x.foo(y)`.

Add `no-unbound-method` rule

---

src/rules/alignRule.ts
test/rules/align/arguments/test.ts.fix
test/rules/align/parameters/test.js.lint
test/rules/align/parameters/test.ts.fix
test/rules/align/parameters/test.ts.lint
test/rules/align/statements/test.ts.fix

Add an ability to auto-fix for `align` rule.
Now `AlignWalker.checkAlignment` doesn't support early break since to get an ability to auto-fix.

Add support to fix `align` rule

---

src/rules/noLetUndefinedRule.ts
test/rules/no-let-undefined/test.js.lint
test/rules/no-let-undefined/test.ts.fix
test/rules/no-let-undefined/test.ts.lint
test/rules/no-let-undefined/tslint.json

Added the `no-let-undefined` rule, which forbids `let x = undefined;`, preferring `let x;`.

Add `no-let-undefined` rule

---

src/rules/awaitPromiseRule.ts
test/rules/await-promise/test.ts.lint
test/rules/await-promise/tsconfig.json
test/rules/await-promise/tslint.json

Added the `await-Promise` rule, which ensures that anything in an `await` expression could actually be a Promise. Prevents needlessly awaiting synchronously available values.
This is complementary to  #1632: That ensures that Promises are awaited, while this ensures that awaiteds are Promises.

Add `await-promise` rule

---

src/rules/noFloatingPromisesRule.ts

This rule uses the type checker.
Re: https://github.com/palantir/tslint/pull/1972#issuecomment-275384846

no-floating-promises: Fix metadata

---

appveyor.yml
circle.yml
package.json

Set the node engine version to `4.1.2` since tslint works with that version, too and reverse the breaking change made with `tslint@4.4.0`.

Set node engine version to 4.1.2

---

src/rules/typedefRule.ts
test/rules/typedef/all/test.ts.lint
test/rules/typedef/all/tslint.json
test/rules/typedef/array-destructuring/test.ts.lint
test/rules/typedef/array-destructuring/tslint.json
test/rules/typedef/none/test.ts.lint
test/rules/typedef/object-destructuring/test.ts.lint
test/rules/typedef/object-destructuring/tslint.json
test/rules/typedef/variable-declaration/test.ts.lint
test/rules/typedef/variable-declaration/tslint.json

This PR adds support for opting in to `object-destructuring` and `array-destructuring` in **typedef** rule.  
Current `variable-declaration` option, if on, will fail if:
```
const [ paramA, paramB ] = [15, 'test'];
```
With this PR it wont, `variable-declaration` only fails on simple non-binding declarations.
Tests samples:
```
const { paramA, paramB } = { paramA: "test", paramB: 15 };
~    [expected object-destructuring: '{ paramA, paramB }' to have a typedef]
const { paramA, paramB }: { paramA: string, paramB: number } = { paramA: "test", paramB: 15 };
const [ paramA, paramB ] = [15, 'test'];
~    [expected array-destructuring: '[ paramA, paramB ]' to have a typedef]
const [ paramA3, paramB3 ]: { number: string, paramB1: string } = [15, 'test'];
```
`variable-declaration` now has it's …

Add new object/array-destructuring options to typedef rule

---

src/rules/memberOrderingRule.ts
test/rules/member-ordering/alphabetize/test.ts.lint
test/rules/member-ordering/alphabetize/tslint.json

Added the 'alphabetize' option to member-ordering, which enforces alphabetical ordering within each category.
This uses `<` for string comparison. I think `.localeCompare` would be troublesome if people in different locales want linting to succeed on all of their machines.

member-ordering: Add 'alphabetize' option

---

src/rules/objectLiteralKeyQuotesRule.ts
test/rules/object-literal-key-quotes/as-needed/test.ts.fix
test/rules/object-literal-key-quotes/as-needed/test.ts.lint

A property `{ "1.23": null }` does not need quotes since `{ 1.23: null }` is the same object. But the values `{ ".123": null }` and `{ .123: null }` differ. Try it out: `node -p '({ 1.23: null })'`.

object-literal-key-quotes: No need to quote a float if its .toString() is the same.

---

src/rules/noImportSideEffectRule.ts
test/rules/no-import-side-effect/default/test.js.lint
test/rules/no-import-side-effect/default/test.ts.lint
test/rules/no-import-side-effect/default/tslint.json
test/rules/no-import-side-effect/ignore-module/test.js.lint
test/rules/no-import-side-effect/ignore-module/test.ts.lint
test/rules/no-import-side-effect/ignore-module/tslint.json

Fix #2116
Introduced a rule which warns when used imports with side-effects. For more details here https://github.com/palantir/tslint/issues/2116.
Have I added the required documentation.

Add `no-import-side-effect` rule

---

src/rules/noAnyRule.ts
src/rules/objectLiteralShorthandRule.ts
test/rules/no-any/test.ts.fix
test/rules/object-literal-shorthand/test.ts.fix

Add fixers for no-any and objectLiteralShorthand (for keys).
For object literals with functions, it's sadly pretty tricky to find the opening `(` token, so for now those will have to live without a fix.

Add fixers for no-any and object-literal-shortand (properties only)

---

docs/develop/contributing/index.md
src/rules/strictBooleanExpressionsRule.ts

This change is just for fixing simple document bugs.
1. strict-boolean-expressions
"|" (bitwise OR operator) is interpreted as table. (See https://palantir.github.io/tslint/rules/strict-boolean-expressions )
2. Typo in the contributing document

Fix document bug in strict-boolean-expressions and the contributing doc

---

src/rules/banTypesRule.ts
test/rules/ban-types/test.ts.lint
test/rules/ban-types/tslint.json

I added a new rule, `ban-types`, that allows a list of specified global types to be banned from use, similar to the existing `ban` rule for functions.

Add a rule to ban specified types from being used in type annotations or type assertions.

---

src/rules/newlineBeforeReturnRule.ts
test/rules/newline-before-return/default/test.ts.lint
test/rules/newline-before-return/default/test.tsx.lint
test/rules/newline-before-return/default/tslint.json

A new rule to force blank lines before return. Based on http://eslint.org/docs/rules/newline-before-return
Making sure all test cases are covered. I took the base file from eslint and added a few cases.

New Rule: newline-before-return

---

src/rules/noInferrableTypesRule.ts
test/rules/no-inferrable-types/default/test.ts.fix
test/rules/no-inferrable-types/default/test.ts.lint
test/rules/no-inferrable-types/ignore-params/test.ts.fix
test/rules/no-inferrable-types/ignore-properties/test.ts.fix
test/rules/no-inferrable-types/ignore-properties/test.ts.lint
test/rules/no-inferrable-types/ignore-properties/tslint.json

[new-fixer] automatically remove inferrable type annotations
[new-rule-option] added `ignore-properties` option to `no-inferrable-types`
Minor Refactoring to use the new `AbstractWalker`
Not sure about the option name. `Parameters` is abbreviated to `params`. Maybe I should do the same for `properties` -> `props`?

Add ignore-properties to no-inferrable-types

---

src/error.ts
src/language/rule/abstractRule.ts
src/linter.ts
src/ruleLoader.ts

Don't die when a rule requiring type checking but doesn't have it

---

src/rules/noAnyRule.ts
src/rules/objectLiteralShorthandRule.ts
test/rules/no-any/test.ts.lint
test/rules/object-literal-shorthand/test.js.lint
test/rules/object-literal-shorthand/test.ts.lint

Users often use `any` when they could equally well use `{}`, because
they are not aware of the empty type.
Users also often don't know what object shorthand is - giving them a
hint as to what syntax is expected makes it easier to fix the lint
warning.
Improve error messages for no-any and object-literal-shorthand.

Improve error messages for no-any and object-literal-shorthand.

---

package.json
yarn.lock

Currently `tslint` dependes on `update-notifier` 1.x, unfortunately the dependency chain of update-notifier means that at the very end `got@5.7.1` is being pulled in:
```
├─┬ tslint@4.4.2
│ ├── diff@3.2.0
│ ├─┬ findup-sync@0.3.0
│ │ └── glob@5.0.15
│ ├─┬ optimist@0.6.1
│ │ ├── minimist@0.0.10
│ │ └── wordwrap@0.0.3
│ ├── resolve@1.2.0
│ └─┬ update-notifier@1.0.3
│   ├─┬ boxen@0.6.0
│   │ ├── ansi-align@1.1.0
│   │ ├── camelcase@2.1.1
│   │ ├── cli-boxes@1.0.0
│   │ ├── filled-array@1.1.0
│   │ └── widest-line@1.0.0
│   ├── is-npm@1.0.0
│   ├─┬ latest-version@2.0.0
│   │ └─┬ package-json@2.4.0
│   │   ├─┬ got@5.7.1
│   │   │ ├─┬ create-error-class@3.0.2
│   │   │ │ └── capture-stack-trace@1.0.0
```
`got@5.7.1` again has an engines restriction of `node<7`, which means that if you install …

fix: update update-notifier

---

src/rules/quotemarkRule.ts
test/rules/quotemark/double-avoid-escape/test.js.lint
test/rules/quotemark/double-avoid-escape/test.ts.fix
test/rules/quotemark/double-avoid-escape/test.ts.lint
test/rules/quotemark/double/test.js.lint
test/rules/quotemark/double/test.ts.fix
test/rules/quotemark/double/test.ts.lint
test/rules/quotemark/jsx-double/test.tsx.fix
test/rules/quotemark/jsx-double/test.tsx.lint
test/rules/quotemark/jsx-single/test.tsx.fix
test/rules/quotemark/jsx-single/test.tsx.lint
test/rules/quotemark/single-avoid-escape/test.js.lint
test/rules/quotemark/single-avoid-escape/test.ts.fix
test/rules/quotemark/single-avoid-escape/test.ts.lint
test/rules/quotemark/single/test.js.lint
test/rules/quotemark/single/test.ts.fix
test/rules/quotemark/single/test.ts.lint

Simple change in quotemarkRule::visitStringLiteral. Search the escaped text for \n and \t and replace with escaped versions. Also added a string containing tab/newline to the test cases for the quotemark rule.
First PR to this project, so I'm sorry if I missed something obvious

Preserve newlines and tabs when autofixing quote marks

---

src/language/walker/syntaxWalker.ts
src/rules/noNonNullAssertionRule.ts
test/rules/no-non-null-assertion/test.ts.lint
test/rules/no-non-null-assertion/tslint.json

New Rule: no-non-null-assertion

---

.npmignore

Add `yarn.lock` to .npmignore, per https://twitter.com/gabro27/status/786825544998481920

Don't publish yarn.lock in dist

---

package.json
src/enableDisableRules.ts
src/rules/adjacentOverloadSignaturesRule.ts
src/rules/commentFormatRule.ts
src/rules/importBlacklistRule.ts
src/rules/jsdocFormatRule.ts
src/rules/newlineBeforeReturnRule.ts
src/rules/noTrailingWhitespaceRule.ts
src/rules/noUnnecessaryInitializerRule.ts
src/rules/noUnnecessaryQualifierRule.ts
src/rules/noUnsafeAnyRule.ts
src/rules/noUnsafeFinallyRule.ts
src/rules/typedefRule.ts
src/rules/unifiedSignaturesRule.ts
src/rules/whitespaceRule.ts
yarn.lock

Use the package `tsutils` for typeguards and other utility functions.
> The idea was to create a separate project which maintains typeguards and AST utilities for everyone, not just tslint and custom rules packages. This way tslint core could remain just a runtime for rules instead of growing to a bulk of utility functions.

Use tsutils package for utilities

---

src/rules/noConsecutiveBlankLinesRule.ts
test/rules/no-consecutive-blank-lines/default/test.ts.fix
test/rules/no-consecutive-blank-lines/multiple/test.ts.fix

add fix function to noConsecutiveBlankLines

add fix function to noConsecutiveBlankLines

---

package.json
src/rules/noSwitchCaseFallThroughRule.ts
test/rules/no-switch-case-fall-through/test.js.lint
test/rules/no-switch-case-fall-through/test.ts.lint
yarn.lock

[bugfix] handle break, throw, continue and return nested in block, if-else and switch
[bugfix] allow empty case clauses before default clause
[enhancement] allow single line comment `// falls through`
Depends on #2217

Rewrite and bugfix no-switch-case-fallthrough

---

src/rules/completedDocsRule.ts
test/rules/completed-docs/defaults/test.ts.lint

Handled an undefined `symbol` returned by the type checker.
Ref: Microsoft/TypeScript#14257

completed-docs: Handle undefined symbol

---

src/rules/noUnusedVariableRule.ts

As discussed in feedback on  #1481 and #1617, for many users `--noUnusedParameters` and `--noUnusedLocals` do not work as a replacement for `noUnusedVariable`. This change de-deprecates the rule and documents the alternative compiler flags (and why they might not work for users) in the description.
Fixes #1617.
This is a proposal, please discuss and feel free to reject :-)

Un-deprecate noUnusedVariable.

---

src/rules/objectLiteralKeyQuotesRule.ts
test/rules/object-literal-key-quotes/as-needed/test.ts.fix
test/rules/object-literal-key-quotes/as-needed/test.ts.lint

`object-literal-key-quotes` flags negative number as not needing quotes

---

docs/_includes/rule_list.html
docs/_layouts/rule.html
docs/_sass/_base.scss
src/rules/completedDocsRule.ts

This PR make some UI changes to the the list of rules, and the individual rule detail pages.
- The rules on the rules list page are now clickable, not just the rule name
- Alternating background colors + hover colors
- "feature" badges for each rule in the list, and larger versions on the actual rule details page
- yellow badge with document icon when `typescriptOnly` is true
- green badge with wrench icon when `hasFix` is true
- red badge with info icon when `requiresTypeInfo` is true
**Here's what the changes look like!**
Eventually it would be really nice to have some interactive rule filters on that page.  To be able to filter the rules list down to only show the rules that require type info, or could be auto-fixed would be awesome!  I wanted to keep this PR minimal & focused though.

Improve the UI for the rules documentation

---

.vscode/settings.json

#2250 changed how vscode wrapped long lines. After that change lines were wrapped at the end of the viewport. This PR restores the old behaviour of wrapping at the specified column.
I also added `wrappingIndent: none`. Wrapped lines will begin in column 0, which makes it easier to distinguish from regular indented lines.
[no-log]

Restore old behaviour of text wrap in vscode

---

src/rules/onlyArrowFunctionsRule.ts
test/rules/only-arrow-functions/default/test.ts.lint

Changed `only-arrow-functions` to allow a non-arrow function if `this` appears somewhere in its body. These cannot be converted to arrow functions.
There is already an exception for `this` as an explicit parameter, but often it comes from a contextual type, as in:
```ts
function f(g: (this: number) => void) { g.call(0); }
f(function() { console.log(this) });
```

only-arrow-functions: Allow functions that use 'this' somewhere in the body

---

src/rules/noUnnecessaryCallbackWrapperRule.ts
test/rules/no-unnecessary-callback-wrapper/test.js.lint
test/rules/no-unnecessary-callback-wrapper/test.ts.fix
test/rules/no-unnecessary-callback-wrapper/test.ts.lint
test/rules/no-unnecessary-callback-wrapper/tslint.json

Added the `no-redundant-callback` rule, which warns on `x => f(x)` (prefer just `f`).
[new-rule] `no-unnecessary-callback-wrapper`

Add `no-unnecessary-callback-wrapper` rule

---

src/rules/arrowParensRule.ts
test/rules/arrow-parens/ban-single-arg-parens/test.ts.fix
test/rules/arrow-parens/ban-single-arg-parens/test.ts.lint

Fixes: #2237
[bugfix] `arrow-parens` with option `ban-single-arg-parens` now correctly handles functions with return type annotation

Fix arrow-parens with return type annotation

---

src/rules/unifiedSignaturesRule.ts
test/rules/unified-signatures/test.d.ts.lint

Improved the error message to indicate which is the other failing overload. This has led to some confusion (https://github.com/palantir/tslint/issues/2016#issuecomment-283059245).

Unified-signatures: When there are more than 2 overloads, include the line number of the other overload to be unified

---

src/language/rule/optionallyTypedRule.ts
src/language/rule/rule.ts
src/linter.ts

Like `AbstractRule`, it provides abstract `apply*` members that must be
implemented.
*(errata: switched the order of checks in `linter.ts` because it felt
quicker having a property check before the function call)*
Also moved `isTypedRule` logic to a separate function, as it's no longer
unique to the `TypedRule` class. An alternative I'd considered but
rejected would be to make a member `isTyped(): this is IRule` on
`IRule`, but that would require classes not inheriting from
`AbstractRule` to also define their own `isTyped()`.
Resolves #2091.

Added an abstract OptionallyTypedRule

---

src/rules/noReferenceImportRule.ts
test/rules/no-reference-import/test.d.ts.lint
test/rules/no-reference-import/tslint.json

Added the `no-reference-import` rule, which forbids `/// <reference types="foo" />` where `import ... from "foo"` is used anyway.
[new-rule] `no-reference-import`

Add `no-reference-import` rule

---

src/rules/arrayTypeRule.ts
test/rules/array-type/array-simple/test.ts.fix
test/rules/array-type/array-simple/test.ts.lint
test/rules/array-type/array/test.ts.fix
test/rules/array-type/array/test.ts.lint

Consider the `undefined` and `never` types to be simple types. This allows writing `undefined[]` or `never[]`.
The second commit changes tests to prove that I changed something. Could be removed if you think it's ugly.
[rule-update] `array-type` now consider `undefined` and `never` as simple types, allowing `undefined[]` and `never[]`

Add more simple types

---

src/rules/preferFunctionOverMethodRule.ts
test/rules/prefer-function-over-method/default/test.ts.lint

The `prefer-function-over-method` rule was warning for abstract methods.  This change adds a test case for that, and resolves it.  The rule already checks for the `static` modifier, so it was simple enough to also check for the `abstract` modifier.
[bugfix] `prefer-function-over-method` now ignores abstract methods

`prefer-function-over-method` should ignore abstract methods

---

package.json
src/rules/preferFunctionOverMethodRule.ts
test/rules/prefer-function-over-method/default/test.ts.lint
yarn.lock

[bugfix] exclude overload signatures from `prefer-function-over-method`
This would have also fixed #2305
Refactor the rule to use AbstractWalker and simplify the algorithm.

Bugfix prefer-function-over-method for overloads

---

README.md

Update description of possible values of `extends`

---

src/rules/useIsnanRule.ts
test/rules/use-isnan/test.ts.lint

The `use-isnan` rule was warning about all binary operators except for the simple assignment operator `=`.  This was problematic because `x || NaN` is a reasonable thing to do.  This change ensures that it only applies to comparison operators.  Instead of checking for the assignment exception, the rule now checks against a complete list of comparison operators.
Most binary operators would be silly to use with a literal `NaN`.  I'm not sure whether it would have been better to just add more exceptions (specifically for `||` and `&&`).  The technique in this PR has the risk that if a new comparison operator is later added to the language (e.g. `<=>`) then the rule will need to be updated.  But it seemed better to me to limit the scope of the rule completely.
[bugfix] `use-isnan` now applies …

`use-isnan` should only apply to comparison operators

---

src/rules/fileHeaderRule.ts
test/rules/file-header/bad-single-line/test.js.lint
test/rules/file-header/bad-single-line/test.ts.lint
test/rules/file-header/bad-single-line/tslint.json
test/rules/file-header/empty-file/test.js.lint
test/rules/file-header/empty-file/test.ts.lint
test/rules/file-header/good-single-line/test.js.lint
test/rules/file-header/good-single-line/test.ts.lint
test/rules/file-header/good-single-line/tslint.json

The file-header rule was not correctly parsing single-line comments. Therefore the regex was not working. That is now fixed.
I fixed the `commentRegexp` so that it will correctly parse single-line comments. It was an easy fix. I simply removed a `?`.
Please make sure I made the correct decision with the tests inside the `empty` directory.
Fixed the file-header rule so that it correctly handles single-line coments.

file-header fix for single-line comments

---

src/rules/newlineBeforeReturnRule.ts
test/rules/newline-before-return/default/test.ts.lint

[bugfix] fix hanling of blank lines between comments
Fixes: #2311

Fix handling of comments in newline-before-return

---

src/rules/noInferrableTypesRule.ts
test/rules/no-inferrable-types/default/test.ts.fix
test/rules/no-inferrable-types/default/test.ts.lint
test/rules/no-inferrable-types/ignore-params/test.ts.fix
test/rules/no-inferrable-types/ignore-params/test.ts.lint
test/rules/no-inferrable-types/ignore-properties/test.ts.fix
test/rules/no-inferrable-types/ignore-properties/test.ts.lint

[bugfix] `no-inferrable-types` don't warn for inferrable type on readonly property
Fixes: #2306
[enhancement] `ignore-properties` option of `no-inferrable-types` now also ignores parameter properties

Bugfix no-inferrable-types with readonly property

---

README.md
docs/usage/cli/index.md
src/runner.ts
src/test.ts
src/tslint-cli.ts
test/executable/executableTests.ts

[bugfix] exit with 0 on type check errors when `--force` is specified
Fixes: #2087
[bugfix] `--test` now correctly strips single quotes from patterns on windows
[enhancement] `--test` can handle multiple paths at once
^useful when shell expands globs
[enhancement] added `-p` as shorthand for `--project` to be consistent with `tsc`
Kind of fixes: #2291
[enhancement] print error when `--type-check` is used without `--project`
[enhancement] don't print stack trace on type check error

Extend cli options

---

package.json

`diff` and `semver` are only used for testing, although `test.ts` is in `src`. Should they be `devDependencies` too?

Move @types to devDependencies

---

src/rules/preferConstRule.ts

Forgot to handle initialized parameters of constructors.
[no-log] the original rewrite it not released yet, so there is no need to add another changelog entry

Minor fix for prefer-const

---

src/rules/returnUndefinedRule.ts

Re: https://github.com/palantir/tslint/pull/2251#issuecomment-287680071

Fix compile error

---

src/rules/variableNameRule.ts

Refactor variable-name rule

---

.gitattributes
src/rules/linebreakStyleRule.ts
test/rules/linebreak-style/failure/CRLF/test.js.fix
test/rules/linebreak-style/failure/CRLF/test.ts.fix
test/rules/linebreak-style/failure/LF/test.js.fix
test/rules/linebreak-style/failure/LF/test.ts.fix

[new-fixer] `linebreak-style`
The rule checks the line ending directly in the source text instead of using a scanner. That way we also find failures inside multiline comments and template strings.

Refactor linebreak-style and add fixer

---

src/rules/variableNameRule.ts
test/rules/variable-name/allow-pascal-case/test.ts.lint
test/rules/variable-name/allow-snake-case/test.ts.lint
test/rules/variable-name/allow-snake-case/tslint.json

Add OPTION_ALLOW_SNAKE_CASE to variable name options
[new-rule-option] "allow-snake-case" option for `variable-name` rule (#2190)
Please let me know if there's anything else you need / would like to change.  Many thanks.

Add OPTION_ALLOW_SNAKE_CASE to variable name options

---

src/rules/trailingCommaRule.ts
test/rules/trailing-comma/multiline-always/test.ts.fix
test/rules/trailing-comma/multiline-always/test.ts.lint

[bugfix] `trailing-comma` no longer crashes on new without parentheses (e.g. `new Foo`)

Bugfix trailing-comma for new without parens

---

test/configurationTests.ts
test/executable/executableTests.ts
test/formatters/tapFormatterTests.ts
test/ruleLoaderTests.ts
tslint.json

Removed a `describe.only` to re-enable testing.
Skipped any broken tests and filed issues. (#2329, #2404, #2405)

Re-enable tests

---

docs/usage/tslint-json/index.md
src/configuration.ts
test/config/tslint-extends-package-warning.json
test/configurationTests.ts
test/executable/executableTests.ts

Adds a config setting `defaultSeverity` to the config file, which applies its severity level to any rule with a `default` setting in the _current_ file. This does not apply to configs that are extended. A future config setting may be added to override all of the severity levels of the extended rule sets.
fixes #2279 
[new-config-option] Adds `defaultSeverity` with options `error`, `warning`, and `off`.

Adds default severity

---

src/rules/noUnnecessaryQualifierRule.ts
test/rules/no-unnecessary-qualifier/test-global-2.ts.lint
test/rules/no-unnecessary-qualifier/test-global.ts.fix
test/rules/no-unnecessary-qualifier/test-global.ts.lint

Now that  #2235 is in, we don't need to worry about multiple source files, so symbolsAreEqual is unnecessary.
Also fixes a bug where symbols with declarations at identical positions but different source files were considered equal.

no-unnecessary-qualifier: Stop using symbolsAreEqual

---

src/configs/latest.ts
src/configs/recommended.ts

[enhancement]: added new rules to the recommended set

Update recommended rules from latest

---

src/rules/preferForOfRule.ts
test/rules/prefer-for-of/test.ts.lint

Don't unnecessarily use a BlockScopeAwareRuleWalker, just store a stack of for-loop scopes.

Clean up prefer-for-of rule

---

src/rules/memberAccessRule.ts
test/rules/member-access/default/test.ts.lint

Skips an index signature in `member-access`.
Previous PR #2435 was wrong, index signatures can not have access modifiers.
Also, it mentioned the wrong rule name!
[bugfix] `member-access`: Skip index signature, it can not have an access modifier

member-access: Skip index signature, it can not have an access modifier

---

README.md
src/configs/all.ts
src/rules/memberOrderingRule.ts
src/rules/returnUndefinedRule.ts
test/ruleLoaderTests.ts

Minimal-change version of #2241
[api] `tslint:all` configuration

Add "tslint:all" configuration

---

src/rules/restrictPlusOperandsRule.ts
test/rules/restrict-plus-operands/test.ts.lint

Fixes: #2443
[bugfix] `restrict-plus-operands` fixes regression where every assignment and comparison was checked
Sorry, my bad.

Fix regression in restrict-plus-operands

---

src/language/rule/abstractRule.ts

Type of `options` should not be used to infer type parameter `T`.
Refs: https://github.com/Microsoft/TypeScript/issues/14829
[no-log]

Fix type parameter of applyWithFunction

---

src/rules/variableNameRule.ts

Fixes a compiler error introduced by merging https://github.com/palantir/tslint/pull/2396

Fix variableNameRule compiler error

---

src/rules/radixRule.ts
test/rules/radix/test.ts.lint

[bugfix] don't warn for missing radix on method calls
[enhancement] added check for global.parseInt and window.parseInt

Bugfix for radix rule and property access

---

src/rules/strictTypePredicatesRule.ts
test/rules/strict-type-predicates/test.ts.lint

Check for construct signatures in `isFunction`.
[bugfix] `strict-type-predicates`: Check for construct signatures in `isFunction`.

strict-type-predicates: Anything with a construct signature is a function

---

src/rules/banTypesRule.ts
src/rules/importSpacingRule.ts
src/rules/noFloatingPromisesRule.ts
src/rules/noStringThrowRule.ts

Removed all remaning uses of `RuleWalker.createFailure`.

Remove remaining uses of `createFailure`

---

src/rules/arrowReturnShorthandRule.ts
test/rules/arrow-return-shorthand/default/test.js.lint
test/rules/arrow-return-shorthand/default/test.ts.lint
test/rules/arrow-return-shorthand/multiline/test.ts.lint

Changes the failure message to mention that parentheses are needed when the expression is an object literal.

arrow-return-shorthand: Improve failure message when return expression is an object literal

---

src/rules/strictBooleanExpressionsRule.ts
test/rules/strict-boolean-expressions/allow-number/tsconfig.json
test/rules/strict-boolean-expressions/allow-string/tsconfig.json
test/rules/strict-boolean-expressions/default/test.ts.lint
test/rules/strict-boolean-expressions/default/tsconfig.json
test/rules/strict-boolean-expressions/no-null-checks-allow-null-union/test.ts.lint
test/rules/strict-boolean-expressions/no-null-checks-allow-null-union/tslint.json
test/rules/strict-boolean-expressions/no-null-checks-allow-number-string/test.ts.lint
test/rules/strict-boolean-expressions/no-null-checks-allow-number-string/tslint.json
test/rules/strict-boolean-expressions/no-null-checks/test.ts.lint
test/rules/strict-boolean-expressions/no-null-checks/tslint.json

If `--strictNullChecks` mode is not enabled, we will consider every value to potentially be a null/undefined union, so we won't consider anything as "always truthy".
[enhancement] `strict-boolean-expressions`: When `--strictNullChecks` is turned off, `allow-null-union` and `allow-undefined-union` turn off "always truthy" errors.

strict-boolean-expressions: Support code without strictNullChecks

---

src/linter.ts
test/linterTests.ts

Fix #2392
The spec that I added extends the `Linter` in order to test the extra
method I added. Since tslint doesn't have any rules which apply fixes in
a file different from the one which is currently being linted, I didn't
come up with additional tests.
The test "mocks" [a codelyzer rule](https://github.com/mgechev/codelyzer/blob/master/src/noAccessMissingMemberRule.ts).

fix(Linter): apply fix to the correct file

---

src/rules/preferForOfRule.ts
test/rules/prefer-for-of/test.ts.lint

Handle `delete` expressions in prefer-for-of
[bugfix] `prefer-for-of`: No error if `delete` is used

prefer-for-of: No error if 'delete' is used

---

.gitignore
.npmignore
.nycrc
package.json
yarn.lock

Add code coverage report. Just execute `yarn coverage` or `npm run coverage`.
We could also report this to coveralls.io or fail the build if coverage drops under a certain threshold.
Currently there is only a test summary printed to stout and the html report.
We already have a pretty good coverage:
```
Statements   : 93.43% ( 7166/7670 )
Branches     : 87.05% ( 3246/3729 )
Functions    : 94.64% ( 1429/1510 )
Lines        : 93.13% ( 6480/6958 )
```
Should `coverage` be executed instead of `test` when running `yarn verify`?
Does this need documentation in the `contributing` section?

Add test coverage report

---

src/rules/noUnnecessaryCallbackWrapperRule.ts
test/rules/no-unnecessary-callback-wrapper/test.ts.fix
test/rules/no-unnecessary-callback-wrapper/test.ts.lint

[bugfix] `no-unnecessary-callback-wrapper`: allow async wrapper function
[bugfix] `no-unnecessary-callback-wrapper`: only check if callback is identifier, allow all other expressions
Fixes: #2509

no-unnecessary-callback-wrapper: only check if callback is identifier

---

scripts/buildDocs.ts

Since the docs refactor by @adidahiya when running `yarn verify` there is a diff in generated docs for formatters because of a changed title.
This PR fixes buildDocs.ts to generate the files the same way they are commited now.
An alternative would be to simply gitignore the generated docs of formatters.
[no-log]

Fix buildDocs

---

src/rules/noUnsafeAnyRule.ts
test/rules/no-unsafe-any/commonjsModule.ts
test/rules/no-unsafe-any/es6Module.ts
test/rules/no-unsafe-any/test.ts.lint

Always allow import statements in `no-unsafe-any`.
[bugfix] `no-unsafe-any`: Allow import declarations

no-unsafe-any: Allow import declarations

---

src/linter.ts

TSLint was looking up the rule severity for all failures even if the rule was already assigned a severity in a previous file linting. This is a problem when there are multiple tslint.json files in different directories (TSLint uses Node resolution to determine which one applies) and if a rule is enabled and becomes disabled later. If failure for rule X occurs, then X is disabled, it will attempt to look up the severity of X again, and it won't be found
fixes #2476 
[bugfix] Fixes "Severity for rule not found" error

Fix error saying severity is missing

---

src/configs/all.ts
src/rules/deprecationRule.ts
test/rules/deprecation/other.ts
test/rules/deprecation/test.ts.lint
test/rules/deprecation/tslint.json

Fixes #825
Warn when @deprecated APIs are used.
Missing lots of test cases.
[new-rule]

deprecation rule

---

docs/usage/configuration/index.md
src/configuration.ts
test/config/tslint-custom-rules-with-package-fallback.json
test/config/tslint-custom-rules-with-package.json
test/configurationTests.ts

When someone uses a `rulesDirectory` we try to resolve it with Node resolve logic first, before falling back to the old algorithm.
[enhancement] `rulesDirectory` can now be resolved with [`dir-resolve`](https://www.npmjs.com/package/dir-resolve) (#2163)

resolve rulesDirectory - fixes #2163

---

package.json
src/rules/noStringLiteralRule.ts
test/rules/no-string-literal/test.ts.fix
test/rules/no-string-literal/test.ts.lint
yarn.lock

[enhancement] `no-string-literal` now handles escaped strings
[new-fixer] `no-string-literal`
I also updated the locked dependency on tslint to v5.0.0

Refactor no-string-literal and add fixer

---

src/rules/noUnnecessaryQualifierRule.ts
test/rules/no-unnecessary-qualifier/arguments.ts.lint

`Symbol#getDeclarations` returns `null` when it's describing an `arguments` reference.  This change short-circuits `symbolIsNamespaceInScope` if declarations are `null`.
Nope.
[bugfix] `no-unnecessary-qualifier`: no longer breaks when walking a function that references `arguments`

Fix no-unnecessary-qualifier handling of implicit arguments

---

src/rules/preferConstRule.ts
test/rules/prefer-const/default/ambient.d.ts.lint
test/rules/prefer-const/default/test.ts.fix
test/rules/prefer-const/default/test.ts.lint

[bugfix] `prefer-const` no longer shows warnings on ambient declarations
Fixes: #2390

prefer-const: don't check ambient declarations

---

src/language/utils.ts
src/rules/noVarKeywordRule.ts
test/rules/no-var-keyword/global.d.ts.lint
test/rules/no-var-keyword/module.d.ts.lint

The `var` keyword is useful in one case: When you want to declare a global variable.
The problem with declaring a global `const` is that this is considered a block-scoped declaration, and will warn for duplicates.
```ts
declare global {
var x: number;
var x: number; // OK
const y: number;
const y: number; // Error
}
```
This PR changes the rule to allow `var` in a position where it *declares* a global variable.
It still warns for:
* `export var x: number;` (not global)
* `var x;` (not a declaration if not in `declare global`)
Note: Also disabled fixer in declaration files, because those should almost always be `const` instead of `let`, and we can't detect `prefer-const` in declarations (#2390).
[enhancement] `no-var-keyword`: Allow global var declarations

no-var-keyword: Allow global var declarations

---

src/rules/fileHeaderRule.ts

Avoid comment regex and use typescript's implementation for finding the first comment
[no-log]

file-header: simplify comment matching

---

src/rules/noUnnecessaryCallbackWrapperRule.ts
test/rules/no-unnecessary-callback-wrapper/test.ts.fix
test/rules/no-unnecessary-callback-wrapper/test.ts.lint

#2510 is too simple; there are cases of non-identifier calls that are still an unnecessary callback, like `x => f()(x)`. We can solve #2509 by looking for uses of the parameters in the called expression, so that `x => x(x)` is still not a failure.
[enhancement] `no-unnecessary-callback-wrapper`: Handle non-identifier functions

no-unnecessary-callback-wrapper: Handle non-identifier functions

---

src/rules/cyclomaticComplexityRule.ts

cyclomatic-complexity: Convert to function

---

src/configs/all.ts
src/rules/numberLiteralFormatRule.ts
test/rules/number-literal-format/test.ts.lint
test/rules/number-literal-format/tslint.json

Added the `number-literal-format` rule, which warns on `.5` and `0.50` (both: prefer `0.5`).
This could also be extended to implement #1391 if anyone wants that.
[new-rule] `number-literal-format`

Add `number-literal-format` rule

---

src/rules/maxClassesPerFileRule.ts
test/rules/max-classes-per-file/one/test.ts.lint
test/rules/max-classes-per-file/two/test.ts.lint

Just a refactor. Also added a period to failure message.

max-classes-per-file: Convert to function

---

src/rules/objectLiteralKeyQuotesRule.ts
test/rules/object-literal-key-quotes/always/test.js.fix
test/rules/object-literal-key-quotes/always/test.js.lint
test/rules/object-literal-key-quotes/always/test.ts.fix
test/rules/object-literal-key-quotes/always/test.ts.lint

[bugfix] `object-literal-key-quotes`: does no longer require quotes for property names containing digits
[bugfix] `object-literal-key-quotes`: correctly stringify numbers when fixing

Rewrite and fix object-literal-key-quotes

---

src/rules/noUnsafeFinallyRule.ts
test/rules/no-unsafe-finally/test.js.lint
test/rules/no-unsafe-finally/test.ts.lint

Just a rewrite. Should be simpler now.

Rewrite no-unsafe-finally

---

src/language/walker/blockScopeAwareRuleWalker.ts
src/language/walker/scopeAwareRuleWalker.ts

See the discussion in #2514.
Saves us from needing a `ProgramAwareBlockScopeAwareRuleWalker`.
After ##2339 and #2341 are in, we will no longer be using these internally.
[api] Deprecate `ScopeAwareRuleWalker` and `BlockScopeAwareRuleWalker`.

Deprecate ScopeAwareRuleWalker and BlockScopeAwareRuleWalker

---

src/configs/all.ts
src/rules/noObjectLiteralTypeAssertionRule.ts
test/rules/no-object-literal-type-assertion/test.ts.lint
test/rules/no-object-literal-type-assertion/tslint.json

Added the `no-object-literal-type-assertion` rule, which warns on `{ } as T`.
[new-rule] `no-object-literal-type-assertion`

Add `no-object-literal-type-assertion` rule

---

src/language/rule/rule.ts
test/formatters/jsonFormatterTests.ts

This was declared to have a value of type `Fix`, but the rendered json is actually different.
We were exposing the `inner*` properties via `JSON.stringify`. Kept those in `toJson()` for backwards-compatibility.

Clarify type of failure JSON

---

src/rules/semicolonRule.ts
test/rules/semicolon/never/test.ts.fix
test/rules/semicolon/never/test.ts.lint

[bugfix] `semicolon`: don't mark semicolon as unnecessary when the next statement is on the same line
Fixes: #2564

semicolon: fix "never" option behavior when not followed by line break

---

src/rules/returnUndefinedRule.ts
test/rules/return-undefined/test.ts.lint

#2573: Handle a contextual type with ambiguous signatures and fall back to `getTypeAtLocation`.
#2566: Allow 'any'.
#2565: Treat an async function returning `Promise<void>` like a regular function returning `void`.
[bugfix] `return-undefined`: Handle contextual types with ambiguous signatures; allow `any`; and handle async functions.

Fix various `return-undefined` bugs

---

src/rules/alignRule.ts
test/rules/align/statements/bom.ts.fix
test/rules/align/statements/bom.ts.lint

[bugfix] `align`: fix false positive for files with BOM
Fixes: #2640
/cc @unicron

align: fix false positive with BOM

---

src/rules/noSwitchCaseFallThroughRule.ts

* Reduce casts
* Create `commentText` helper
* Use `.forEach` and `.some`

Clean up no-switch-case-fallthrough

---

src/rules/noFloatingPromisesRule.ts
test/rules/no-floating-promises/promises/test.ts.lint

Rewrite to walker function.
Add some tests.
[no-log]

no-floating-promises: rewrite as walker function

---

src/rules/importBlacklistRule.ts

import-blacklist: Refactor to use AbstractWalker

---

src/rules/quotemarkRule.ts
test/rules/quotemark/single/test.tsx.lint

[bugfix] `quotemark`: fix regression with jsx attributes
Fixes: #2603

quotemark: bugfix for jsx quotes

---

tslint.json

Switches our config over to `tslint:all`. Just disabled the new rules instead of applying them.

Use tslint:all to lint tslint

---

src/ruleLoader.ts

This repo uses rules that are not yet released to lint its code. That creates a lot of noise in the output because the older version of tslint warns about rules not found ... for every linted file.
This PR changes ruleLoader to only show those warnings once.
[no-log] I guess?

ruleLoader: show warning about missing rules once

---

src/rules/alignRule.ts
test/rules/align/statements/test.ts.lint

See issue #2608
Skip over empty statements when running the `align` rule on statements.  Empty statements can be caused by unnecessary semicolons, and in that case the error message "statements are not aligned" is confusing.  The problem is better handled by the `semicolons` rule.

Don't report 'statements are not aligned' for empty statements

---

tslint.json

#2669 didn't take into account that the global version of "prefer-switch" would still have the old "min-cases".

Set "min-cases" for "prefer-switch" in tslint.json

---

src/rules/variableNameRule.ts
test/rules/_integration/enable-disable/test.ts.lint
test/rules/variable-name/allow-leading-trailing-underscore/test.ts.lint
test/rules/variable-name/allow-leading-underscore/test.ts.lint
test/rules/variable-name/allow-pascal-case/test.ts.lint
test/rules/variable-name/allow-snake-case/test.ts.lint
test/rules/variable-name/allow-trailing-underscore/test.ts.lint
test/rules/variable-name/default/test.ts.lint

Users were confused by the rule requiring `camelcase`, as they thought that should include `UpperCamelCase` (aka `PascalCase`). This change adjusts the error message to be more explicit.
[enhancement] better error messages in `variable-name`

More specific error message for the variable-name rule.

---

src/rules/noUnnecessaryQualifierRule.ts

no-unnecessary-qualifier: Convert to function

---

src/rules/noDefaultExportRule.ts
test/rules/no-default-export/test.ts.lint

Rewrite to walker function and only check top level statements. Excluding declaration files, because they only declare what is already available from some module.
[bugfix] `no-default-export`: correctly handle `export default abstract class {...}`
The rule only checks top level statements, because typescript doesn't allow default exports in namespaces.
Default exports are allowed in `declare module "foo"`, but they are not checked for the same reason as declaration files (see above)

no-default-export: rewrite and fix export default bug

---

src/rules/noUnnecessaryInitializerRule.ts
test/rules/no-unnecessary-initializer/test.ts.fix
test/rules/no-unnecessary-initializer/test.ts.lint

Just a refactor. **EDIT**: Also a bugfix.
[bugfix]: `no-unnecessary-initializer`: Handle `BindingElement` anywhere, not just in a `VariableDeclaration`.

no-unnecessary-initializer: Convert to function

---

src/rules/spaceBeforeFunctionParenRule.ts
test/rules/space-before-function-paren/mixed/test.ts.fix
test/rules/space-before-function-paren/mixed/test.ts.lint
test/rules/space-before-function-paren/never/test.ts.fix
test/rules/space-before-function-paren/never/test.ts.lint

Just a refactor.
The previous implementation had special handling for FunctionDeclaration with an empty name; since this is a compiler error anyway, removed the special handling and its associated tests.
[enhancement] `space-before-function-paren`: Handle `get`/`set` accessor

space-before-function-paren: Rewrite

---

src/rules/oneVariablePerDeclarationRule.ts

one-variable-per-declaration: Convert to function

---

.gitattributes
src/rules/jsdocFormatRule.ts
test/rules/jsdoc-format/jsdoc-bom.ts.lint
test/rules/jsdoc-format/jsdoc-windows.ts.lint
test/rules/jsdoc-format/jsdoc.ts.lint

[bugfix] `jsdoc-format`: fixed error position if line ends with `\r\n`
[bugfix] `jsdoc-format`: don't treat empty comments (`/**/`) as jsdoc
[bugfix] `jsdoc-format`: correctly handle alignment in files with BOM
Fixes: #2505

jsdoc-format: rewrite and fix

---

src/configuration.ts
src/rules/memberOrderingRule.ts
tslint.json

Just enables the lint rule.
Figure the use of `=== true` in `memberOrderingRule.ts` was probably necessary, so updated the types instead.

Enable "no-boolean-literal-compare"

---

src/rules/noUnsafeAnyRule.ts
test/rules/no-unsafe-any/test.ts.lint

No longer fail for `function f(): 0 {}`.
[bugfix] `no-unsafe-any`: Fix bug where number literal in type position was flagged as an unsafe `any`.

no-unsafe-any: Fix bug for number literal type

---

src/rules/typedefWhitespaceRule.ts
test/rules/typedef-whitespace/both/nospace/test.ts.lint
test/rules/typedef-whitespace/both/onespace/test.ts.lint
test/rules/typedef-whitespace/both/space/test.ts.lint
test/rules/typedef-whitespace/left/nospace/test.ts.lint
test/rules/typedef-whitespace/left/onespace/test.ts.lint
test/rules/typedef-whitespace/left/space/test.ts.lint
test/rules/typedef-whitespace/right/nospace/test.ts.lint
test/rules/typedef-whitespace/right/onespace/test.ts.lint
test/rules/typedef-whitespace/right/space/test.ts.lint

[new-fixer] `typedef-whitespace`
[enhancement] `typedef-whitespace` added checks for arrow function, call and construct signature
[bugfix] `typedef-whitespace` don't warn for leading whitespace if token is preceded by line break

typedef-whitespace: Rewrite and add fixer

---

src/rules/completedDocsRule.ts
test/rules/completed-docs/privacies-private/test.ts.lint
test/rules/completed-docs/privacies-private/tslint.json
test/rules/completed-docs/privacies-protected/test.ts.lint
test/rules/completed-docs/privacies-protected/tslint.json
test/rules/completed-docs/privacies-public/test.ts.lint
test/rules/completed-docs/privacies-public/tslint.json

+ I don't think the `public` "privacies" option (or its absence) was being respected at all. We encountered this in a React project where we wanted to require documentation for _just_ private & protected methods.
+ In addition it looks like the existing "privacies" test was specifying privacies under the "visibilities" key? 
+ Added tests for the individual "privacies" levels
[bugfix] Make "completed-docs" rule respect "public" privacy (or lack thereof)

Make the "completed-docs" rule respect "public" privacies option

---

src/rules/noInferredEmptyObjectTypeRule.ts

Refactor to AbstractWalker
The implementation will get cleaned up once I publish the next version of `tsutils` with typeguards for types.
[no-log] just refactoring

no-inferred-empty-object-type: Refactor to AbstractWalker

---

src/rules/preferConstRule.ts
test/rules/prefer-const/default/test.ts.fix
test/rules/prefer-const/default/test.ts.lint

@mikyladewitt reported this bug on Gitter
[bugfix] `prefer-const`: fix false positive with variable used in for-of or for-in

prefer-const: fix false positive with variable used in for-of or for-in

---

package.json
src/rules/restrictPlusOperandsRule.ts
src/rules/returnUndefinedRule.ts
src/rules/strictTypePredicatesRule.ts
yarn.lock

The new version of `tsutils` contains typeguards for types. We can therefore remove the redundant typeguards. 
I left `awaitPromiseRule.ts` untouched, because there is an open PR for that rule.
[no-log]

Update tsutils and remove redundant typeguards

---

src/utils.ts
test/utilsTests.ts

This utility isn't being used any more. Since utilities are exposed by `Lint.Utils`, deprecated instead of deleting.
[api] Deprecate `Lint.Utils.objectify`

Deprecate "objectify"

---

src/runner.ts
src/tslint-cli.ts
test/executable/executableTests.ts

Search for tsconfig.json in specified directory. Exit with error if  there is none.
Ref: #2692
[enhancement] cli: `-p` option handles directories

CLI: handle directories passed with -p

---

src/rules/arrowReturnShorthandRule.ts
src/rules/semicolonRule.ts
src/rules/trailingCommaRule.ts

This PR converts some uses of `ts.getLineAndCharacterOfPosition` to `tsutils.isSameLine` as suggested by @andy-hanson in https://github.com/palantir/tslint/pull/2591#discussion_r111692431
`curly` and `one-line` are not included, because they are not refactored yet
[no-log]

Use isSameLine helper

---

src/rules/eoflineRule.ts

I think we should clearly state that eofline fix is not supported for single-line files. It's not obvious without inspecting [source code](https://github.com/palantir/tslint/blob/master/src/rules/eoflineRule.ts#L47) and looks like bug.

Document that eofline fix is not supported for single-line files.

---

src/configuration.ts
test/configurationTests.ts

Fixes `not a directory` error

---

src/rules/noConsecutiveBlankLinesRule.ts

The current docs do not make sense because the values were not
replaced, see
https://palantir.github.io/tslint/rules/no-consecutive-blank-lines/
Fixed noConsecutiveBlankLines rule documentation. Since `Rule.MINIMUM_ALLOWED_BLANKS` does not exist I have changed the value in the `options` property to 1 (instead of `Rule.DEFAULT_ALLOWED_BLANKS`) in case the `Rule.DEFAULT_ALLOWED_BLANKS` value changes in the future.

[docs] fixed invalid template in noConsecutiveBlankLines rule

---

src/rules/deprecationRule.ts
test/rules/deprecation/other.test.ts
test/rules/deprecation/other.ts
test/rules/deprecation/other2.test.ts
test/rules/deprecation/test.ts.lint

Rewrite to walker function.
Use TypeScript's JsDoc parser
[enhancement] `deprecation`: error message includes deprecation text if available

deprecation: Rewrite and enhance

---

src/rules/alignRule.ts
test/rules/align/members/test.ts.fix
test/rules/align/members/test.ts.lint

[bugfix] `align` with option `"members"`: check members of class expressions; don't check semicolons in classes

align: exclude SemicolonClassElement

---

src/rules/objectLiteralShorthandRule.ts
test/rules/object-literal-shorthand/test.ts.fix
test/rules/object-literal-shorthand/test.ts.lint

[new-fixer] `object-literal-shorthand` can fix longhand methods
[bugfix] `object-literal-shorthand`: fix suggestion for generator functions
[enhancement] `object-literal-shorthand` handles async functions correctly

object-literal-shorthand: Refactor, fix and add fixer for methods

---

src/rules/noUnusedVariableRule.ts

When TSLint is being used to provide as-you-type linting as in Angular IDE, incorrect configuration of program created in makeUnusedCheckedProgram function is causing whole functionality to blow up. The core of the issue is that SourceFiles are being assigned case sensitive path when program is recreated for TSLint validation, which later causes that wrong path to stick and file not found problems appear in whole IDE.
[bugfix] Fix issue with case sensitivity of noUnusedVariable rule on Windows

Fix issue with case sensitivity of noUnusedVariable rule on Windows

---

docs/develop/testing-rules/index.md
src/test.ts
test/rules/_integration/react/tslint.json

This add the ability to pass the path to `tslint.json` instead of the directory containing it to `tslint --test`.
That's useful if you have a test directory structure like tslint and want to call it like `tslint --test test/rules/**/tslint.json`.
In fact this feature makes `ruleTestRunner.ts` obsolete. It could be simply replaced by the above command. Though that would run all tests before printing any output and would not stop at the first failed test.

--test: allow passing path to tslint.json

---

src/rules/strictBooleanExpressionsRule.ts
test/rules/strict-boolean-expressions/default/test.ts.lint

Starts allowing the types 'any', 'true', or 'false' if they appear exactly.
Will still not allow an always-truthy/falsy union (e.g. `true | Date`).
[enhancement] `strict-boolean-expression`: Allow `any`, and `true` and `false` literal types

strict-boolean-expressions: Allow 'any', and 'true' and 'false' literal types

---

src/rules/strictBooleanExpressionsRule.ts
test/rules/strict-boolean-expressions/allow-boolean-undefined-union/test.ts.lint
test/rules/strict-boolean-expressions/allow-boolean-undefined-union/tsconfig.json
test/rules/strict-boolean-expressions/allow-boolean-undefined-union/tslint.json
tslint.json

I find it weird to compare for strict equality on unions of boolean and undefined. Consider the following function:
```ts
function foo(bar?: boolean) {
if (bar) // not allowed by default
// do stuff
}
```
`allow-undefined-union` would allow too much, because it also allows for example `ts.Node | undefined`.
It's already awkward to use `ts.NodeArray#hasTrailingComma === true`. With my recent changes to typescripts typings (https://github.com/Microsoft/TypeScript/pull/15887, https://github.com/Microsoft/TypeScript/pull/15903), that will hit us with the next version of typescript, this pattern will occur in many more places (e.g. `ts.forEachChild`).
That's why I added this new option `allow-boolean-or-undefined`.
[new-rule-options] `strict-boolean-expressions` adds …

strict-boolean-expressions: new option allow-boolean-or-undefined

---

src/linter.ts
src/rules/noUnusedVariableRule.ts
test/executable/executableTests.ts
test/files/tsconfig-allow-js/testfile.test.js
test/files/tsconfig-allow-js/tsconfig.json
test/files/tsconfig-allow-js/tslint.json
test/rules/strict-boolean-expressions/allow-boolean-undefined-union/test.ts.lint

By default typescript checks if compiled output files *would* overwrite input files. Since we are not compiling anything, we need to turn this check off.
[bugfix] don't crash `tslint --project` if `allowJs` is set in tsconfig.json
Fixes: #2568 
The second commit fixes the CI failures on master

Add noEmit to compilerOptions

---

src/rules/typedefWhitespaceRule.ts

Just noticed that this switch always calls `checkSpace` on the same node, so extracted out a function that just gets the option type.

typedef-whitespace: Extract `getOptionType` helper

---

src/rules/completedDocsRule.ts

The list at the end was indented too much and was treated like a block of code. (See [here](https://palantir.github.io/tslint/rules/completed-docs/).)

completed-docs: Fix markdown formatting

---

src/rules/spaceBeforeFunctionParenRule.ts
test/rules/space-before-function-paren/always/test.ts.fix
test/rules/space-before-function-paren/always/test.ts.lint

Fix bug for `async x => x`.
[bugfix] `space-before-function-paren`: Ignore async arrow function with no parentheses

space-before-function-paren: Ignore async arrow function with no parentheses

---

src/rules/noUnsafeAnyRule.ts
test/rules/no-unsafe-any/test.ts.lint

`continue foo;` mistakenly identified `foo;` as being of type `any`.
[bugfix]: `no-unsafe-any`: Don't fail on `continue label;`

no-unsafe-any: Fix bug for `continue` with label

---

src/rules/noUnboundMethodRule.ts
test/rules/no-unbound-method/default/test.tsx.lint

Allows an unbound method to occur as a condition. This is useful if you don't have `strict-boolean-expressions` turned on and the method is optional, so you would use `if (x.method) x.method()`.
[bugfix] `no-unbound-method`: Allow unbound method to be used as a condition

no-unbound-method: Allow use as condition

---

src/rules/noUnsafeAnyRule.ts
test/rules/no-unsafe-any/test.ts.lint

Allow `switch (x) { case x: ... }` where `x` is of type `any`.
[bugfix] `no-unsafe-any`: Allow to switch on a value of type `any`

no-unsafe-any: Allow to switch on a value of type `any`

---

src/rules/noUnsafeAnyRule.ts
test/rules/no-unsafe-any/test.ts.lint

Avoid adding a failure for the `global` in `declare global {}`.
[bugfix] `no-unsafe-any`: Don't mark `declare global {}` as an unsafe any.

no-unsafe-any: Allow `declare global {}`

---

package.json
src/rules/indentRule.ts
test/rules/indent/spaces-2/test.ts.fix
test/rules/indent/spaces-2/test.ts.lint
test/rules/indent/spaces-2/test.tsx.lint
test/rules/indent/spaces-4/test.ts.fix
test/rules/indent/spaces-4/test.ts.lint
test/rules/indent/tabs-2/test.ts.fix
test/rules/indent/tabs-2/test.ts.lint
test/rules/indent/tabs-4/test.ts.fix
test/rules/indent/tabs-4/test.ts.lint
yarn.lock

Remove complex scanning logic. Only search for comments or template spans when indent is wrong.
Added a test for JSX.
[bugfix] `indent` now checks indentation of expressions inside template strings

indent: Simplify and avoid scanning

---

src/rules/noUnboundMethodRule.ts
test/rules/no-unbound-method/default/test.ts.lint

Skips past the parent in the case of `obj.method as any` and the like.
[bugfix] `no-unbound-method`: Skip past the parent if it is a cast or parenthesized expression

no-unbound-method: Skip past casts and parentheses

---

src/rules/preferObjectSpreadRule.ts
test/rules/prefer-object-spread/test.ts.fix
test/rules/prefer-object-spread/test.ts.lint

[bugfix] `prefer-object-spread`:  allow constructor, function and method calls and more as first argument to `Object.assign`
Fixes: #2824
[enhancement] `prefer-object-spread`: lint more locations where return value is used.

prefer-object-spread: lint more locations, allow first parameter with side effects

---

src/rules/noFloatingPromisesRule.ts
test/rules/no-floating-promises/promises/test.ts.lint

Allow `p.catch()` since the promise is handled appropriately.
[enhancement] `no-floating-promises`: Allow 'promise.catch()'

no-floating-promises: Allow 'promise.catch()'

---

package.json
src/tslint-cli.ts

`process.exit()` kills the process immediately and cancels all pending async writes.
After linting finishes, we only set the exitCode and let the program exit when all async stuff is done.
[bugfix] Fixed regression with empty `--out` file
Fixes: #2863

Fix --out: Only set exitCode instead of exiting immediately

---

src/rules/noStringLiteralRule.ts

Clarified the rule documentation.
* The rule does nothing when a string literal is necessary, as in `obj["foo-bar"]`.
* There's nothing unsafe about string literal access if `--noImplicitAny` is turned on.

no-string-literal: Fix documentation

---

src/rules/unifiedSignaturesRule.ts
test/rules/unified-signatures/test.d.ts.lint

Don't suggest to unify `...args: string[]` and `...args: number[]`.
[bugfix] `unified-signatures`: Don't suggest to unify rest parameters.

unified-signatures: Can't unify rest parameters

---

src/rules/binaryExpressionOperandOrderRule.ts
test/rules/binary-expression-operand-order/test.ts.lint

Allow `1 + 1`.
[bugfix] `binary-expression-operand-order`: Allow if both sides of the binary expression are literals.

binary-expression-operand-order: Allow both sides to be literals

---

circle.yml
src/language/utils.ts
src/rules/deprecationRule.ts
src/rules/spaceBeforeFunctionParenRule.ts
src/rules/whitespaceRule.ts
test/rules/deprecation/test.ts.lint
test/rules/return-undefined/test.ts.lint

Added a wrapper function for `ts.isWhiteSpaceLike` or `ts.isWhiteSpace`. Fixes `whitespace` and `space-before-function-paren`. Fixes: #2891
Added a workaround for the missing `symbol.getJsDocTags()` in `deprecationRule`.
Make `Promise<T>` available for tests of `return-undefined` to make it work with typescript@<2.2.0.
Circle node | TypeScript version
--- | ---
0 | 2.1.x
1 | 2.2.x
2 | current dev dependency (2.3.4)
3 | next
[bugfix] Restore compatibility with typescript@2.1 and 2.2 for `whitespace`, `space-before-function-paren` and `deprecation`

Ensure compatibility with older typescript in CI

---

src/language/rule/typedRule.ts
src/linter.ts
src/rules/memberAccessRule.ts
src/rules/memberOrderingRule.ts
src/rules/quotemarkRule.ts

[enhancement] Print stack trace of exceptions
Rules that used to throw an exceptions just to warn about something have been converted to show the warning and return.

Print stack trace of exceptions

---

CHANGELOG.md
package.json
src/linter.ts

I intentionally left out https://github.com/palantir/tslint/commit/8e84685150092aa500257518a0b63081fe3056f1; I'm going to save that for v5.5.0. I mostly just want to ship the fixes for TS < 2.3.
I will tag 5.4.3 on this release branch once approved and _then_ merge it back into master.

Prepare release v5.4.3

---

src/rules/preferConstRule.ts
test/rules/prefer-const/default/test.ts.fix
test/rules/prefer-const/default/test.ts.lint

[enhancement] `prefer-const`: handle destructuring in for-of loop initializer as if `{"destructuring": "all"}` was specified
Fixes: #2902 
/cc @WilcoBakker

prefer-const: special handling for destructuring in for-of

---

src/tslint-cli.ts

Commander by default adds a `-V` option as shorthand for `--version`.
This PR changes the shorthand back to `-v`.
[cli] restore `-v` option
Fixes: #2925

cli: Restore -v option

---

package.json
src/linter.ts
src/rules/completedDocsRule.ts
src/rules/curlyRule.ts
src/rules/deprecationRule.ts
src/rules/matchDefaultExportNameRule.ts
src/rules/noInferrableTypesRule.ts
src/rules/noUnusedExpressionRule.ts
src/rules/noUnusedVariableRule.ts
src/rules/onlyArrowFunctionsRule.ts
src/rules/restrictPlusOperandsRule.ts
src/rules/strictBooleanExpressionsRule.ts
src/rules/trailingCommaRule.ts
src/rules/unifiedSignaturesRule.ts
src/rules/useDefaultTypeParameterRule.ts
src/rules/whitespaceRule.ts
src/runner.ts
test/configurationTests.ts
test/rules/whitespace/all/import.ts.lint
yarn.lock

Updates to typescript 2.4.0 and fixes compile errors.
[bugfix]: `whitespace`: now correctly handles dynamic imports introduced in typescript@2.4.0
Fixes: #2920

Update to typescript 2.4.0

---

src/rules/noUnusedVariableRule.ts
test/rules/no-unused-variable/default/import.ts.fix
test/rules/no-unused-variable/default/import.ts.lint

When an unused import is deleted, the line break is removed too.
Unless there are more sentences in the same line, so the break is preserved.
- Can you think on other scenarios we need to cover?
- This is my first time contributing to TSLint and consuming TS compiler API. Let me know if there's something that can be improved.
"[enhancement] `no-unused-variable`: Don't leave empty lines when import is removed"

Don't leave blank lines when no-unused-variable autofix removes whole import

---

tslint.json

The TODO said that the line should be removed when tslint 5.3 has been released, which happend [23 days ago](https://github.com/palantir/tslint/releases/tag/5.3.0).
The JSON standard doesn't allow comments, so there shouldn't be any comments in JSON files.

Removed "prefer-switch" because tslint 5.3 is out

---

src/rules/switchFinalBreakRule.ts
test/rules/switch-final-break/default/test.ts.lint

[bugfix] `switch-final-break`: don't fail if break jumps to a label outside of the switch

switch-final-break: don't fail for break statement with label

---

docs/usage/third-party-tools/index.md

I've added Emacs/Flycheck, which comes with a tslint-based syntax checker, to the third-party tools list.

Add Emacs/Flycheck to third-party tool list

---

src/language/walker/syntaxWalker.ts
src/rules/completedDocsRule.ts
test/rules/completed-docs/types/test.ts.lint
test/rules/completed-docs/types/tslint.json
test/rules/completed-docs/visibilities/test.ts.lint
test/rules/completed-docs/visibilities/tslint.json

I've extended the `completed-docs` rule to check enum members. This is disabled by default and can be enabled by including a new argument "enum-members". This can also be configured to only require documentation for members of internal enums or exported enums.
[new-rule-option] `completed-docs`: Add `enum-members` option

completed-docs: Add support for enum members

---

package.json
src/rules/deprecationRule.ts
src/rules/preferForOfRule.ts
src/rules/preferObjectSpreadRule.ts
test/rules/prefer-for-of/test.ts.lint
yarn.lock

Simplify some rules.
[bugfix] `prefer-for-of` correctly handles variable scopes and other unrelated identifiers

Update to latest tsutils

---

README.md

Added a link to "inline disabling and enabling of rules with comment flags", as it a bit hard to find IMO.
Added link to readme

Readme: Added link to flags

---

README.md

The current link for Visual Studio only works for Visual Studio 2015. There are no intentions to upgrade this plugin to Visual Studio 2017 :|
There is a fork (which works well) for Visual Studio 2017, I have added that link and renamed the old "Visual Studio" link to "Visual Studio 2015"
Also updated the link to marketplace.visualstudio.com
Nope

Readme: Added VS 2017 link, updated VS 2015 link

---

src/rules/noSwitchCaseFallThroughRule.ts
test/rules/no-switch-case-fall-through/test.ts.lint

[enhancement] `no-switch-case-fall-through` matches `// falls through` comments case insensitive and allows trailing text

no-switch-case-fall-though: accept different comment formats

---

src/language/utils.ts
src/rules/noInferrableTypesRule.ts
test/rules/no-inferrable-types/default/test.ts.fix
test/rules/no-inferrable-types/default/test.ts.lint

Adds the initializer text to logic in `typeIsInferrable`, and allows it to contain `Infinity`.
Fixes #2777.
[enhancement] Added NaN and (+/-)Infinity as numbers to `no-inferrable-types`

Added NaN and (+/-)Infinity as numbers to no-inferrable-types

---

src/rules/arrayTypeRule.ts
test/rules/array-type/array-simple/test.ts.fix
test/rules/array-type/array-simple/test.ts.lint

[bugfix] `array-type`: consider `this` to be simple type

Fix 2792 this simple type

---

src/rules/noUnsafeAnyRule.ts
test/rules/no-unsafe-any/test.ts.lint

[bugfix] `no-unsafe-any`: allow truthyness and falsyness checks
Fixes: #2981
There's some more work to do in this rule. It simply ignores some branches of the AST like destructuring and LHS of some binary expressions. Will fix that after this PR lands.

no-unsafe-any: allow truthyness and falsyness checks

---

src/rules/awaitPromiseRule.ts
test/rules/await-promise/custom-promise/test.ts.lint
test/rules/await-promise/es6-promise/test.ts.lint

Rule await-promise accepts not only union type but intersection type.

Fix #2986 await-promise accept intersection

---

src/rules/spaceBeforeFunctionParenRule.ts
test/rules/space-before-function-paren/always/test.ts.fix
test/rules/space-before-function-paren/always/test.ts.lint
test/rules/space-before-function-paren/mixed/test.ts.fix
test/rules/space-before-function-paren/mixed/test.ts.lint
test/rules/space-before-function-paren/never/test.ts.fix
test/rules/space-before-function-paren/never/test.ts.lint

This PR applies options for anonymous functions expression to default exports of function declarations without name.
With this change there are no distinction between function declarations and function expression, therefore this two cases were combined.
There is no addition check for `default` in `modifiers` for `FunctionDeclaration` because other cases with omitted name are errors in TS/JS. 
Optionally behavior for unnamed functions as default export might be controlled with separate options, however this is likely an overkill.
[bugfix] `space-before-function-paren` Handle default exports of functions without names like anonymous functions (fixes #3040)

Handle unnamed default exports like anonymous functions (fixes #3040)

---

README.md
package.json
scripts/npmPublish.sh

**Warning: When this PR is merged `NPM_TOKEN` should be deleted from the CircleCI environment variables.**
Switches from a GH/CircleCI based publishing flow to a local one. This allows us to add contributors to TSLint without giving them publishing/releasing permissions. 
Does the local publishing script seem reasonable? Does re-cloning the repo to a temporary directory seem reasonable? I tested the script myself, but obviously didn't publish an actual release.
Possible improvements to this PR:
* We could probably automate the creation of the git tag as well. For now, I decided to leave it as a manual step (since you have to paste the changelog into GH anyways).
* I only test the build locally with one version of TS. We could do what we do on CircleCI and make `publish:local` run the …

switch from CircleCI -> local release process

---

src/rules/noUnnecessaryQualifierRule.ts
test/rules/no-unnecessary-qualifier/arguments.ts.lint
test/rules/no-unnecessary-qualifier/test-global.ts.lint
test/rules/no-unnecessary-qualifier/test.ts.lint

Seems like typescript used to return the same symbol. That was changed in typescript@2.5.0-dev and caused the tests to fail.
This fix now compares the declarations of the symbols instead of checking the symbols for equality.
Fixes: #3047
[no-log]

no-unnecessary-qualifier: make it work with typescript@next

---

.editorconfig
src/rules/completedDocsRule.ts
test/rules/completed-docs/variables/test.ts.lint
test/rules/completed-docs/variables/tsconfig.json
test/rules/completed-docs/variables/tslint.json
test/rules/completed-docs/visibilities/test.ts.lint
test/rules/completed-docs/visibilities/tslint.json

This PR fixes two issues:
1. When checking if a variable meets the required visibility, the modifiers on the variable were being used, but the variable doesn't have modifiers - the modifiers are on the variable statement which is two levels up. These changes step up two levels to get the correct modifiers.
2. When checking variables, _all_ variables were being checked, including those inside for loops, catch statements, and local variables inside functions. This PR limits variable checking to variables that have a parent of a `SourceFile` - i.e. variables at the file-level.
As a side note, I've also fixed the `.editorconfig` file to have a rule for tslint.json files that enforces an indent size of 2 instead of the default 4, because all tslint.json files I could see used an indentation of …

completed-docs: Limit variable checking to file-level variables and use correct visibility

---

src/rules/noFloatingPromisesRule.ts
test/rules/no-floating-promises/promises/test.ts.lint

```ts
createPromise()
.then(() => next(), next); // No longer an error when rule `no-floating-promise` is enabled.
```
[bugfix] `no-floating-promises`: recognize rejection handler passed as second argument to `promise.then()`

Recognize promise then call with rejection handler as valid floating promise handling

---

src/tslint-cli.ts
test/executable/executableTests.ts

The `tslint` CLI now gives an unhelpful `Missing files ` error when you do not specify any files to lint or the --project argument.
This PR improves the error message so future people won't have to google it like I did :)...
I have updated and run the tests.
[enhancement] Improved CLI error message when no filenames are specified

Improve CLI error message when no files are specified

---

src/rules/adjacentOverloadSignaturesRule.ts
src/rules/alignRule.ts
src/rules/memberOrderingRule.ts
src/rules/noInternalModuleRule.ts
src/rules/noMergeableNamespaceRule.ts
src/rules/noReferenceImportRule.ts
src/rules/noUnnecessaryInitializerRule.ts
src/rules/objectLiteralKeyQuotesRule.ts
src/rules/orderedImportsRule.ts
src/rules/unifiedSignaturesRule.ts
src/rules/useDefaultTypeParameterRule.ts
src/utils.ts

A recent change to TypeScript (Microsoft/TypeScript#17213) specified the NodeArray type to be readonly. This doesn't change the run-time behavior but will cause compile-time errors if compiling against ts2.5. This is fixed by changing types for node arrays to use the ReadonlyArray type.

Use ReadonlyArray for node arrays

---

src/configs/all.ts
src/configs/latest.ts
src/rules/noDuplicateImportsRule.ts
test/rules/no-duplicate-imports/test.d.ts.lint
test/rules/no-duplicate-imports/test.ts.lint
test/rules/no-duplicate-imports/tslint.json

[new-rule] `no-duplicate-imports`
Fixes: #2869
Some thoughts about the current implemenation:
* There no option `includeExports` like in the ESLint rule. Do we want this?
* ImportEqualsDeclarations are ignored
* There's no fixer. That can be added later.
* In some cases you cannot simply merge imports. The rule will still complain about them (maybe the error message should be changed?):
```ts
import foo from 'foo';
import foo2 from 'foo'; // cannot be combined with preceding import
import * as bar from 'bar';
import {baz} from 'bar'; // cannot be combined with preceding import
```

Implement new rule no-duplicate-imports

---

src/rules/noNullKeywordRule.ts
test/rules/no-null-keyword/test.ts.fix
test/rules/no-null-keyword/test.ts.lint

Allows `x === null`, but disallows `x == null`. The latter will be automatically fixed to `x == undefined`.
Fixes: #2782
[new-fixer] `no-null-keyword`: fix `x == null` to `x == undefined`
[enhancement] `no-null-keyword` allows strict comparison

no-null-keyword: Allow strict comparison

---

src/rules/oneLineRule.ts
test/rules/one-line/all/test.ts.lint

[bugfix] `one-line` correctly handles multiline type parameters
Fixes: #2952

one-line: bugfix for multiline type parameters

---

src/rules/noUnusedVariableRule.ts
test/rules/no-unused-variable/type-checked/destructuring.ts.lint
test/rules/no-unused-variable/type-checked/some.test.ts

Avoid typescript crash when trying to get type of destructured variable declaration.
Also avoid walking the AST multiple times when `--declaration` is not enabled. That should result in better performance and fewer false negatives.
[bugfix] `no-unused-variable` fixed crash when using destructuring
Fixes: #2876
Fixes: #3001

no-unused-variable: don't crash at destructuring

---

src/rules/noThisAssignmentRule.ts

Due to string concat a space was missing in the description of the `no-this-assignment` rule.
I feel like creating an issue might be a bit of an overkill here...

Missing space in no-this-assignment description

---

src/rules/preferObjectSpreadRule.ts
test/rules/prefer-object-spread/test.ts.fix
test/rules/prefer-object-spread/test.ts.lint

Permits functions as first argument to Object.assign
- [bugfix] [`prefer-object-spread`](https://palantir.github.io/tslint/rules/prefer-object-spread/) Permit functions as first argument to Object.assign

allow functions as first argument to Object.assign

---

.gitignore

As this project uses `yarn` to manage dependencies, `npm5`'s `package-lock.json` should be ignored.
This rule cannot be applied to global `.gitignore,` because in general it should be stored in git repository.

Ignore npm5's package-lock.json

---

src/rules/orderedImportsRule.ts
test/rules/ordered-imports/import-sources-any/test.ts.fix
test/rules/ordered-imports/import-sources-any/test.ts.lint
test/rules/ordered-imports/lowercase-first/test.ts.fix
test/rules/ordered-imports/lowercase-first/test.ts.lint
test/rules/ordered-imports/named-imports-any/test.ts.fix
test/rules/ordered-imports/named-imports-any/test.ts.lint

Fixes #3043
[enhancement] `ordered-imports`: support importEqualsDeclaration

feat(ordered-imports): support importEqualsDeclaration

---

src/rules/callableTypesRule.ts
test/rules/callable-types/test.ts.fix
test/rules/callable-types/test.ts.lint

[bugfix] `callable-types`: don't remove export modifier of interfaces
Fixes: #2941

callable-types: preserve modifiers

---

src/rules/noReferenceImportRule.ts

This should fix the documentation for the for the `no-reference-import` rule to actually be readable and understood.  Right now it makes no sense.
currently: http://palantir.github.io/tslint/rules/no-reference-import

Escape code in no-reference-import documentation metadata

---

src/ruleLoader.ts

Custom rule files are no longer being loaded with a hardcoded/fixed extenson (`.js`).
With this change all rule files will be resolved using Nodes path resolution. This means that the extension will be detected automatically and other extension loaders like `ts-node` can be used.
This means that rules can be also written in TypeScript and loaded through TS-Node.
[no-log] custom lint rules will be resolved using node's path resolution

fix(ruleLoader): resolve rule files using node path resolution

---

src/runner.ts

Only import the sources needed for rule tests if the `--test` option is used. ~That fixes #3072 for our standard users. Developers using the `--test` feature might still have trouble with the missing `./test` directory caused by `yarn clean`.~
That avoid loading unnecessary modules like `colors`, `diff`, `semver` and everything in `src/test/`

Only import ./test when needed

---

src/rules/whitespaceRule.ts
test/rules/whitespace/all/test.ts.fix
test/rules/whitespace/all/test.ts.lint
test/rules/whitespace/all/tslint.json
test/rules/whitespace/none/test.ts.lint

[new-rule-option] `whitespace`: Add `check-rest-spread` option (#2122)

New rule option: 'check-rest-spread' for 'whitespace' rule

---

src/rules/whitespaceRule.ts
test/rules/whitespace/all/test.ts.fix
test/rules/whitespace/all/test.ts.lint
test/rules/whitespace/all/tslint.json

This PR adds the "check-type-operator" option to the whitespace rule. The implementation is very similar to the binary operator one.
[new-rule-option] `check-type-operator` for `whitepace` rule

Add "check-type-operator" option for whitespace rule

---

src/rules/noFloatingPromisesRule.ts

- [ x] Documentation update
`no-floating-promises` metadata: `no-unused-expressions` is actually `no-unused-expression`

Update for no-floating-promises description details

---

src/rules/noInvalidTemplateStringsRule.ts
src/rules/objectLiteralSortKeysRule.ts
test/rules/no-invalid-template-strings/test.ts.lint

- [x ] Addresses an existing issue: #[2738](https://github.com/palantir/tslint/issues/2738)
- [x ] bugfix
- [x ] Includes tests
Checks if ${} sequence is preceeded by backslash.

no-invalid-template-strings: fix for escaped template expressions

---

src/runner.ts

Currently runnting tslint yields two empty lines, e.g.:
```
$ "$(yarn bin)"/tslint .
$
```
e.g. when running this linter via [`run-p`](https://github.com/mysticatea/npm-run-all) for example, the output is:
[enhancement] remove superfluous empty lines on tslint output.

Silence tslint on no output / tslint produces empty lines on successful lint run

---

.vscode/launch.json
src/rules/preferObjectSpreadRule.ts
test/rules/prefer-object-spread/test.ts.fix
test/rules/prefer-object-spread/test.ts.lint

Allows for Object.assign(obj, this)

prefer-object-spread: ignore Object.assign({}, this)

---

src/rules/noUnnecessaryTypeAssertionRule.ts
test/rules/no-unnecessary-type-assertion/test.ts.fix
test/rules/no-unnecessary-type-assertion/test.ts.lint

Type assertions prevent a type from being widened in a couple of
situations, such as in an object literal or the inferred return type of
a function.

Refine no-unnecessary-type-assertion rule to not flag necessary assertions

---

src/rules/quotemarkRule.ts
test/rules/quotemark/avoid-template/tslint.json
test/rules/quotemark/jsx-double/tslint.json
test/rules/quotemark/single-avoid-escape/tslint.json

Added a couple util functions to quotemark rule. Checks argument list for OPTION_SINGLE or OPTION_DOUBLE in such a way that argument order doesn't matter. Currently, isEnabled() will return false if no single/double option is specified. Maybe defaulting to double quotes makes more sense?

quotemark-rule: single/double options can be at any index in arg list

---

src/rules/noSubmoduleImportsRule.ts
test/rules/no-submodule-imports/static-imports/test.ts.lint
test/rules/no-submodule-imports/static-imports/tslint.json

Today I wanted to use the new `no-submodule-imports` rule. I need to whitelist `@angular/core/testing` for example, but doing that will check if the import starts with `@angular/core/testing/` (note the trailing slash).
This PR also tests for exact matches, allowing me to whitelist `@angular/core/testing` instead of `@angular/core`
[enhancement] `no-submodule-imports` allows whitelisting of submodules like `@angular/core/testing`

no-submodule-imports: consider exact matches as whitelisted

---

src/rules/deprecationRule.ts
test/rules/deprecation/other.test.ts
test/rules/deprecation/test.ts.lint

Imports and exports don't do any harm. We now only show errors at deprecated usage to correctly handle deprecated overload signatures. So this is basically a followup on #2883.
[bugfix] `deprecation` no longer shows errors on imports and exports

deprecation: Don't show errors on imports and exports

---

src/language/rule/abstractRule.ts
src/rules/awaitPromiseRule.ts
src/rules/deprecationRule.ts
src/rules/matchDefaultExportNameRule.ts
src/rules/noBooleanLiteralCompareRule.ts
src/rules/noFloatingPromisesRule.ts
src/rules/noForInArrayRule.ts
src/rules/noUnboundMethodRule.ts
src/rules/noUnnecessaryQualifierRule.ts
src/rules/noUnsafeAnyRule.ts
src/rules/noUnusedVariableRule.ts
src/rules/noUseBeforeDeclareRule.ts
src/rules/noVoidExpressionRule.ts
src/rules/objectLiteralSortKeysRule.ts
src/rules/preferTemplateRule.ts
src/rules/promiseFunctionAsyncRule.ts
src/rules/restrictPlusOperandsRule.ts
src/rules/returnUndefinedRule.ts
src/rules/strictBooleanExpressionsRule.ts
src/rules/strictTypePredicatesRule.ts
src/rules/useDefaultTypeParameterRule.ts

With this change we no longer need a closure to pass the `TypeChecker` or `Program` to the `walkFn`.
[api] `AbstractRule#applyWithFunction` allows additional parameter that is passed through to `walkFn`

applyWithFunction: allow passing TypeChecker or Program directly

---

src/formatters/msbuildFormatter.ts
test/formatters/msbuildFormatterTests.ts

Normalize the filepath so VS's error list has the correct interactions.

---

test/files/project-multiple-fixes/before.test.ts
test/files/project-multiple-fixes/tslint.json

We don't need to execute and fix that many rules to ensure everything works as expected. By removing `whitespace` from the test's `tslint.json` the execution time is reduced from 4.7s to 2.7s on my computer.
That's enough to not run into a timeout even if CI is really slow.
Fixes: #3127
Rewriting the test to not spawn a new process only reduces the execution time by 0.2s - 0.5s
[no-log]

Speed up test for --project --fix

---

src/rules/noUnusedVariableRule.ts
test/rules/no-unused-variable/default/import.ts.fix
test/rules/no-unused-variable/default/import.ts.lint

Enhancement for "no-unused-variable" fixer: Delete trailing comments when deleting an import declaration. Keep the leading comments to prevent deleting licenses.

no-unused-variable: Also delete trailing comments for imports.

---

package.json
src/rules/memberOrderingRule.ts
src/rules/noInferrableTypesRule.ts
src/rules/noSubmoduleImportsRule.ts
src/rules/preferConstRule.ts
src/rules/typedefRule.ts
src/utils.ts
test/executable/executableTests.ts
yarn.lock

Update to the new version of typescript and fix all new errors.
Unfortunately `moduleNameHasNonRelativeName` is no longer exposed which would break the build. We can either wait for https://github.com/Microsoft/TypeScript/issues/17890 to be fixed in the next patch release or merge as is and remove the assertion in `noSubmoduleImportsRule` later. 
[bugfix] `prefer-const` correctly handle `catch` without binding parameter introduced in `typescript@2.5.1`
Fixes #3154

Update to typescript@2.5.1

---

src/rules/memberAccessRule.ts
test/rules/member-access/default/test.ts.fix
test/rules/member-access/default/test.ts.lint

[bugfix] `member-access` autofix now correcly inserts `public` keyword after decorators
Fixes: #3158

member-access: fix insertion position of fixer

---

src/rules/noUnnecessaryQualifierRule.ts

#3052 made `no-unnecessary-qualifier` work with upcoming changes in typescript@2.5
In the meantime typescript added a new API to do this in a more correct way: https://github.com/Microsoft/TypeScript/pull/17457
/cc @andy-ms 
[no-log]

no-unnecessary-qualifier: better fix for ts@2.5

---

src/rules/noNamespaceRule.ts
test/rules/no-namespace/default/test.ts.lint

[bugfix] `no-namespace` ignores global augmentation
Fixes #3157

no-namespace: ignore global augmentation

---

src/rules/noNonNullAssertionRule.ts

This commit clarifies that the `non-null-assertion` is the `!` postfix operator.
Even if the description was already correct, clearly stating what this rule is about `!` makes it easier to understand.
N/A
**[docs]** `no-non-null-assertion` description clarifies that it relates to the `!` postfix operator

Clarify description of no-non-null-assertion

---

docs/develop/custom-rules/index.md
package.json
test/config/tslint-custom-rules-uncompiled.json
test/executable/executableTests.ts
test/files/custom-rules/testUncompiledRule.ts
yarn.lock

Now that loading uncompiled rules is an officially documented feature, there should be a test for it.
I chose to add it to `executableTests.ts` because we spawn a new process for each test. Otherwise ts-node could have side-effects on the other tests because it changes how `require` works. That's why it's not located in `ruleLoaderTests.ts`
[no-log]

test: add test for loading uncompiled rules with ts-node

---

src/enableDisableRules.ts
test/rules/_integration/enable-disable/test.ts.lint

Don't remove failures that start at the end of a disabled range.
The bug caused line switches to disable failures that started at the beginning of the line following the disabled line.
Fixes: #3174
[bugfix] Fixed line switches to not disable failures in the next line following the disabled line

don't remove failure that starts at end of disabled range

---

src/rules/noStringLiteralRule.ts
test/rules/no-string-literal/test.ts.fix
test/rules/no-string-literal/test.ts.lint

The AST contains the escaped name. That bug is fixed in typescript@2.5.0. This adds a fix for older versions.
Fixes: #2965
[bugfix] `no-string-literal` correctly fix property names with leading underscores

no-string-literal: correctly fix property names with leading underscores

---

src/rules/orderedImportsRule.ts
test/rules/ordered-imports/grouped-imports/test.ts.fix
test/rules/ordered-imports/grouped-imports/test.ts.lint
test/rules/ordered-imports/grouped-imports/tslint.json

Added an extra options to ordered-imports to enforce grouping by libraries, parent directories & the current directory.
Should the grouping fix clear the sorting fixes?
[new-rule-option] `"grouped-imports"` for `ordered-imports` rule

Update ordered-imports rule: add default grouping

---

src/rules/deprecationRule.ts
test/rules/deprecation/other.test.ts
test/rules/deprecation/test.ts.lint

Basically the same change I did to resolve the correct call signature. I forgot `NewExpression` back then.
[bugfix] `deprecation` checks correct constructor overload

deprecation: check correct constructor overload

---

src/error.ts
src/rules/orderedImportsRule.ts
src/runner.ts

https://github.com/Microsoft/TypeScript-wiki/blob/master/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work
Fixes: #3143
[no-log]

Fix prototype chain of FatalError

---

src/configuration.ts

When `suppliedConfigFilePath` is passed to `findConfigurationPath()`, `inputFilePath` is completely ignored and should therefore be optional.
[bugfix] Correctly mark `inputFilePath` as an optional parameter in `Configuration.findConfiguration()`

Mark inputFilePath as optional in findConfiguration()

---

src/rules/objectLiteralSortKeysRule.ts
test/rules/object-literal-sort-keys/default/test.ts.lint

Changes the behaviour of `object-literal-sort-keys` when using alphabetical ordering, and allows object keys to be grouped together separated with blank lines.
[enhancement] [`object-literal-sort-keys`](https://palantir.github.io/tslint/rules/object-literal-sort-keys/): allow grouping of object properties via additional blank lines when using alphabetical ordering.

object-literal-sort-keys: Allow grouping of object properties via additional blank lines

---

src/rules/restrictPlusOperandsRule.ts
test/rules/restrict-plus-operands/test.ts.lint

Suggest template literals when an operand is a string.
Most violations in Google code base is "string + number". Users might do `.toString()` to pass this check if they didn't know about template literals.
[enhancement] `restrict-plus-operands`: More specific error message when arguments include strings

restrict-plus-operands: Minor error message change.

---

src/rules/noConditionalAssignmentRule.ts
test/rules/no-conditional-assignment/test.ts.lint

Rewrite to walker function.
The rule now allows intentional assignments like `if (foo(a = b));` or `if ((a || (a = b)).foo);`. If this is a typo the compiler should reveal that error.
[bugfix] `no-conditional-assignment`: exclude intentional assignments, e.g. inside functions
[enhancement] `no-conditional-assignment` added check for conditional (ternary) expressions

no-conditional-assignment: rewrite and check conditional expressions

---

src/rules/spaceBeforeFunctionParenRule.ts
test/rules/space-before-function-paren/always/test.ts.fix
test/rules/space-before-function-paren/always/test.ts.lint
test/rules/space-before-function-paren/mixed/test.ts.fix
test/rules/space-before-function-paren/mixed/test.ts.lint
test/rules/space-before-function-paren/never/test.ts.fix
test/rules/space-before-function-paren/never/test.ts.lint

Fix considers the following cases as exceptions and skips whitespace check:
- arrow function with type parameters
- anonymous functions with type parameters

Fix 'space-before-function-paren' for anonymous/arrow generic functions

---

src/test.ts
src/verify/parse.ts
test/rules/_integration/typescript-version/if-else.ts.lint
test/rules/no-unused-variable/check-parameters/test.ts.lint
test/rules/no-unused-variable/default/class.ts.lint
test/rules/no-unused-variable/default/false-positives.ts.lint
test/rules/no-unused-variable/default/function.ts.lint
test/rules/no-unused-variable/default/import.ts.fix
test/rules/no-unused-variable/default/import.ts.lint
test/rules/no-unused-variable/default/react-addons3.tsx.lint
test/rules/no-unused-variable/default/react3.tsx.lint
test/rules/no-unused-variable/default/react4.tsx.lint
test/rules/no-unused-variable/default/var.ts.lint
test/rules/no-unused-variable/ignore-pattern/var.ts.lint
test/rules/no-unused-variable/type-checked/destructuring.ts.lint

Fixes build failures with typescript@next
Instead of duplicating all tests that have different output between typescript versions, I chose to add support for #if #else and #endif directives to the test markup. The syntax is inspired by C/C++.
The directives are processed before the file is actually parsed. Therefore it can be used to conditionally set the text of a message substitution.
Currently you can only test the typescript version.
I'll update the docs afterwards.
[no-log] will add a changelog entry to the docs PR

Enable if-else in test markup, fix build

---

src/rules/noUnusedVariableRule.ts

Remove warning printed to console when a user of `tslint` is using the
`no-unused-variable` rule while also using the TypeScript compiler
with the `noUnusedLocals` and `noUnusedParameters` options set.
While it's not technically necessary to use the `noUnusedVariableRule`
rule with the TypeScript compiler options set, using this rule
is still useful when using the `--fix` option in `tslint` to
automatically remove unused variables.
Fixes #3219

fix(noUnusedVariableRule): remove warning

---

src/configs/all.ts
src/configs/recommended.ts
src/rules/orderedImportsRule.ts
test/rules/ordered-imports/module-source-path/test.ts.fix
test/rules/ordered-imports/module-source-path/test.ts.lint
test/rules/ordered-imports/module-source-path/tslint.json

Add an additional argument to ordered-import rule allowing sorting by trailing end of path.  This allows sorting modules with relative path by filename
[enhancement] Allow sorting imports by trailing end of path

Ordered-Imports Rule: Allow sorting by the trailing end of the module path

---

src/rules/noUnusedVariableRule.ts
test/rules/no-unused-variable/ignore-pattern/a.test.ts
test/rules/no-unused-variable/ignore-pattern/var.ts.lint

I have a import that I need to ignore (custom reactNamespace), however ignore-pattern is not applied to imports.
applies the importPattern to importNames (in addition to the existing behavior)
not sure if importName.text is the correct thing to test against, but it seems to work.

noUnusedVariableRule should apply the ignorePattern to imports

---

.editorconfig
src/rules/arrowParensRule.ts
test/rules/arrow-parens/ban-single-arg-parens/test.ts.fix
test/rules/arrow-parens/ban-single-arg-parens/test.ts.lint

Fixing `avoid-single-arg-parens` could lead to invalid code if there were trailing commas and/or the close paren is on the next line or parameter is on another line than the `async` keyword.
[bugfix] `arrow-parens` with option `"ban-single-arg-parens"` no longer produces invalid code when fixed

arrow-parens: fix invalid code produced by fixer

---

src/rules/noInvalidThisRule.ts
test/rules/no-invalid-this/enabled/test.ts.lint

Functions with contextual "this" will be ignored.
Are additional test cases needed?

[bug-fix] no-invalid-this / ignore functions w "this" param

---

src/rules/memberOrderingRule.ts

Fix example for member-ordering to be valid

---

package.json
src/rules/deprecationRule.ts
src/rules/importBlacklistRule.ts
src/rules/noDuplicateImportsRule.ts
src/rules/noReferenceImportRule.ts
src/rules/noRequireImportsRule.ts
src/rules/noSubmoduleImportsRule.ts
test/rules/import-blacklist/test.ts.lint
test/rules/no-submodule-imports/static-imports/test.ts.lint
yarn.lock

Simplify import related rules.
[enhancement] `import-blacklist` also checks exports and dynamic imports
Fixes: #3254
[enhancement] `no-submodule-imports` also checks exports

Update to latest tsutils, fix import-blacklist

---

src/rules/noUnnecessaryTypeAssertionRule.ts
test/rules/no-unnecessary-type-assertion/test.ts.fix
test/rules/no-unnecessary-type-assertion/test.ts.lint
test/rules/no-unnecessary-type-assertion/tslint.json

In Google we use type aliases for the `any` type to remind the developers that the type is loose and they need to fix it. This option allows "no-unnecessary-type-assertion" to ignore those explicitly added assertions.

[no-unnecessary-type-assertion]: adds an option to ignore whitelisted type assertions.

---

docs/usage/cli/index.md
docs/usage/type-checking/index.md
src/tslint-cli.ts

Deprecated `--type-check`. It's no longer necessary. Most users don't read the changelog and may not have noticed it.
It breaks consumers that expect a certain output format. And it confuses users, because `--exclude` does not work as expected.
We should remove it in v6.0
[deprecation] CLI argument `--type-check` is no longer necessary and will be removed in the next major version

deprecate --type-check

---

src/rules/callableTypesRule.ts
test/rules/callable-types/test.ts.fix
test/rules/callable-types/test.ts.lint

[bugfix] `callable-types` auto fix produces invalid results

[bugfix] callable types suggestion forgot parens on unions and intersections

---

src/rules/variableNameRule.ts
test/rules/variable-name/allow-pascal-case/test.ts.lint

[bugfix] `variable-name` fixed crash on empty variable name
Fixes: #3288

variable-name: don't crash on syntax errors

---

src/rules/objectLiteralShorthandRule.ts
test/rules/object-literal-shorthand/always/test.ts.fix
test/rules/object-literal-shorthand/always/test.ts.lint
test/rules/object-literal-shorthand/never/test.ts.fix
test/rules/object-literal-shorthand/never/test.ts.lint

I didn't want to occupy @aervin even more with my optimization ideas. So I made a follow-up to address certain things:
* removed a `return` in `disallowShorthandWalker` that shouldn't be there and I missed during review, added a test case
* simplified the fix for shorthand -> longhand method
* narrowed the error location of longhand method
* added a test case for destructuring assignment
[no-log]

object-literal-shorthand: various optimizations

---

src/ruleLoader.ts
src/rules/typeofCompareRule.ts

Show a deprecation warning if the rule is used with typescript 2.2 or newer.
That allows us to remove this rule when we drop support for typescript@2.1
Fixes: #2187
Closes: #2066
[deprecation] `typeof-compare` is deprecated because typescript already does that check

deprecate typeof-compare

---

src/test.ts
src/verify/lintError.ts

Removed unnecessary import of `Error` which caused a crash at runtime if there was an error in a `.lint` file.
`CompilerHost` used for rule tests can now handle any `lib.xxx.d.ts` file, not just the default.
[bugfix] `--test` works correctly with any `compilerOptions.target`

--test: allow target other than default

---

src/rules/deprecationRule.ts
test/rules/deprecation/test.ts.lint

[enhancement] `deprecation` checks object destructuring

deprecation: properly check destructuring

---

src/rules/maxClassesPerFileRule.ts
test/rules/max-classes-per-file/one/test.ts.lint
test/rules/max-classes-per-file/one/tslint.json
test/rules/max-classes-per-file/two/tslint.json

Rule accepts an optional `"include-class-expressions"` argument. If arg is provided, class expressions count toward the file's overall class count, otherwise they are ignored.

[enhancement] max-classes-per-file / config to exclude class expressions

---

src/rules/noUnboundMethodRule.ts
test/rules/no-unbound-method/default/test.ts.lint

Allow `!i.m` where `m` is a method.
[bugfix] `no-unbound-method`: Allow negation of method

no-unbound-method: Allow negation

---

package.json
src/configs/all.ts
src/custom-types.d.ts
src/rules/noImplicitDependenciesRule.ts
test/ruleLoaderTests.ts
test/ruleTests.ts
test/rules/no-implicit-dependencies/default/builtin-only.ts.lint
test/rules/no-implicit-dependencies/default/nested-package/package.json
test/rules/no-implicit-dependencies/default/nested-package/test.ts.lint
test/rules/no-implicit-dependencies/default/subdir/test.ts.lint
test/rules/no-implicit-dependencies/default/test.js.lint
test/rules/no-implicit-dependencies/default/test.ts.lint
test/rules/no-implicit-dependencies/default/tslint.json
test/rules/no-implicit-dependencies/dev/test.ts.lint
test/rules/no-implicit-dependencies/dev/tslint.json
test/rules/no-implicit-dependencies/optional/test.ts.lint
test/rules/no-implicit-dependencies/optional/tslint.json
test/rules/no-implicit-dependencies/package.json
test/tslint.json
yarn.lock

[new-rule] `no-implicit-dependencies`
Fixes: #3235

new rule 'no-implicit-dependencies'

---

src/rules/semicolonRule.ts
test/rules/semicolon/strict-bound-class-methods/test.ts.fix
test/rules/semicolon/strict-bound-class-methods/test.ts.lint
test/rules/semicolon/strict-bound-class-methods/tslint.json

[new-rule-option] `semicolon` adds `"strict-bound-class-methods"`
Fixes: #3216

semicolon: add "strict-bound-class-methods" option

---

src/rules/noEmptyInterfaceRule.ts
test/rules/no-empty-interface/test.ts.lint

[bugfix] `no-empty-interface` allows providing type arguments for extended type
Fixes: #3256
The rule now ignores every interface whose parent has type arguments. That leads to some false-negatives:
```ts
interface Base<T> {
prop: T;
}
interface Good extends Base<string> {}
interface Bad<T> extends Base<T> {}
interface ProbablyGood<T extends string> extends Base<T> {}
interface ProbablyGood2<T = string> extends Base<T> {}
interface Base2<T, U = void> {
prop: T,
prop2: U;
}
interface Bad2<T, U> extends Base2<T, U> {}
interface Good2<U, T> extends Base2<T, U> {}
interface Good3<T> extends Base2<T> {} // looks like `Bad`, but isn't ... would require the type checker
```
There will be no error on any of these declarations. One might expect errors on `Bad` and `Bad2` (and maybe even on …

no-empty-interface: allow providing type arguments for extended type

---

src/rules/noAngleBracketTypeAssertionRule.ts
test/rules/no-angle-bracket-type-assertion/test.ts.fix
test/rules/no-angle-bracket-type-assertion/test.ts.lint

Only add one failure for nested assertions and fix them all together.
[bugfix] `no-angle-bracket-type-assertion` fixed order when autofixing consecutive assertions
Fixes: #2957 
[bugfix] `no-angle-bracket-type-assertion` fixer adds parentheses when necessary
Fixes: #2955
It's very weird that the tests didn't fail all the time.
```ts
var b = <number><any>5;
// before it was fixed to
var b = 5 as number as any;
// now it is fixed to
var b = 5 as any as number; // this line was always in the `.fix` file
```
Only some specific changes to `test.ts.lint` caused the test to fail at this line. The offending line stayed unchanged all the time ...
https://github.com/palantir/tslint/issues/2957#issuecomment-311175391

no-angle-bracket-type-assertion: fixed replacement order and add parens

---

src/rules/onlyArrowFunctionsRule.ts
test/rules/only-arrow-functions/default/test.ts.lint

[bugfix] `only-arrow-function` allow function if `this` is used in parameter initializer

only-arrow-functions: also find uses of `this` in parameters

---

src/formatters/codeFrameFormatter.ts
src/formatters/proseFormatter.ts
src/formatters/stylishFormatter.ts
src/formatters/verboseFormatter.ts
src/language/formatter/abstractFormatter.ts
src/language/rule/rule.ts
src/linter.ts
test/formatters/codeFrameFormatterTests.ts
test/formatters/stylishFormatterTests.ts

[enhancement] `Sort failures by line and character for formatters `

Sort failures by failure's line and character

---

src/language/utils.ts
src/rules/returnUndefinedRule.ts
test/rules/return-undefined/test.ts.lint

[bugfix] `return-undefined` fixed regressions: once again allows anything if return type is `any`
Fixes: #2812
[bugfix] `return-undefined` declared return type takes precedence over contextual type
[bugfix] `return-undefined` handles union return types in async functions
Fixes: #3234

return-undefined: various bug fixes

---

test/rules/deprecation/test.ts.lint

typescript@next changes how JSDoc is associated with variable declarations if there are 2 or more variables in the VariableDeclarationStatement.
I don't know if this is a bug or intended. However, it breaks our tests on CI.
[no-log]

fix CI failures with typescript@next

---

src/rules/awaitPromiseRule.ts
src/test.ts
src/verify/lintError.ts
test/rules/await-promise/custom-promise/test.ts.lint
test/rules/await-promise/es6-promise/test.ts.lint
test/rules/await-promise/for-await-of/test.ts.lint
test/rules/await-promise/for-await-of/tsconfig.json
test/rules/await-promise/for-await-of/tslint.json

[enhancement] `await-promise` enforces that `for-await-of` is only used with `AsyncIterableIterator`
Fixes: #3232
Depends on: #3296

await-promise: check for-await-of

---

src/formatters/vsoFormatter.ts
test/formatters/vsoFormatterTests.ts

[bugfix] `vso` formatter no longer duplicates output for fixed failures
I noticed this while looking through the formatters to find out how the `fixes` parameter is used. Obviously this formatter got it wrong...

vsoFormatter: don't duplicate output for fixed failures

---

src/rules/noImplicitDependenciesRule.ts
test/rules/no-implicit-dependencies/default/bom/package.json
test/rules/no-implicit-dependencies/default/bom/test.ts.lint
test/rules/no-implicit-dependencies/default/subdir/test.ts.lint

Strip BOM from the contents of `package.json` to avoid `JSON.parse` throwing an error.
[no-log]

no-implicit-dependencies: strip BOM before parsing JSON

---

src/rules/completedDocsRule.ts
test/rules/completed-docs/locations/test.ts.lint

Added a test case for async methods and private async to ensure modifiers are joined correctly.
The descriptors for nodes were joined by `","`, which made ugly things like `public,async`.

Joined descriptors in completed-docs with spaces, not commas.

---

src/rules/awaitPromiseRule.ts
test/rules/await-promise/es6-promise/test.ts.lint

[bugfix] `await-promise` correctly recognises classes extending Promise
Fixes: #3381

await-promise: correctly unwrap ReferenceTypes

---

src/rules/banCommaOperatorRule.ts
test/rules/ban-comma-operator/test.ts.lint

This improves the failure message, improves the description metadata, and adds rationale in the metadata for the `ban-comma-operator` based on the discussions in #3380
[enhancement] `ban-comma-operator` - improved failure message and documentation

Improve failure message & docs for ban-comma-operator rule (#3380)

---

package.json
src/rules/completedDocsRule.ts

1. [tslib needs to be updated](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript) for the new emit helper `__makeTemplateObject`, used for template literals.
2. 2.6's improved checking of computed property names in object literals found a typo in a constant in completedDocsRule.ts.
1. Did completedDocsRule *ever* work? Why doesn't `src/rules/completed-docs/tagExclusion.ts` contain the `TAGS_FOR_*` constants instead of completedDocsRule.ts? I made the smallest fix possible, but the right thing might be to move those constants.
1. tslib 1.8 works fine on TS 2.5 and 2.6. I haven't tried it on earlier versions, but the additional helpers shouldn't change anything.

Fix compile errors on TS 2.6

---

src/rules/noDuplicateImportsRule.ts
test/rules/no-duplicate-imports/test2.d.ts.lint
test/rules/no-duplicate-imports/test3.d.ts.lint

Allows two *ambient* modules to have separate imports:
```ts
declare module "a" {
import foo from "foo";
}
declare module "b" {
import foo from "foo";
}
```
Preserves existing behavior for module augmentations.
@ajafff It would be nice to reuse more code from `findImports` in tsutils but it doesn't seem possible given that it currently takes the whole source file as input, so I can't run it on a single `declare module`.
[bugfix] no-duplicate-imports: Allow duplicate imports from separate ambient module declarations

no-duplicate-imports: Allow duplicate imports from separate ambient module declarations

---

src/formatters/codeFrameFormatter.ts
test/formatters/codeFrameFormatterTests.ts

Output code warnings in yellow instead of red

---

circle.yml
package.json

CircleCI updated to yarn 1.x.x. This caused our builds to fail because we tested with node versions that didn't support the `shell` option in `child_process.spawn`.
To fix this we need to use at least 4.8.0, 5.7.0 or 6.0.0 and above. See https://github.com/yarnpkg/yarn/issues/4337 for more details.
While fixing this I noticed that we always used node 4.2.6 on every node. Even executing `nvm use <version>` didn't change this, see https://discuss.circleci.com/t/node-npm-version-build-issues/11471. I fixed that by using `nvm alias default <version>`
[no-log]

Fix CI - use newer versions of node

---

src/rules/noRedundantJsdocRule.ts
test/rules/no-redundant-jsdoc/test.ts.lint

[bugfix] `no-redundant-jsdoc` fixed crash on unhandled tag
Fixes: #3413
@andy-ms I also added `JSDocTypeLiteral` to the always redundant tags. Unfortunately I don't even know what exactly that is. Can you confirm that it is expected to always show an error on this tag?

no-redundant-jsdoc: handle class tag

---

.gitattributes
src/rules/objectLiteralSortKeysRule.ts
test/rules/object-literal-sort-keys/default/crlf.ts.lint

[bugfix] `object-literal-sort-keys` fixed regression that effectively disabled the rule with `\r\n` line breaks
Fixes: #3426

object-literal-sort-keys: don't consider \r\n as two line breaks

---

package.json
src/formatters/codeFrameFormatter.ts
src/formatters/stylishFormatter.ts
src/test.ts
test/formatters/codeFrameFormatterTests.ts
test/ruleTestRunner.ts
yarn.lock

Latest version of chalk comes with type definitions. This breaks all namespace imports. Fortunately they only need to be converted to default imports.
[no-log]

update chalk dependency

---

src/rules/completed-docs/exclusionFactory.ts
src/rules/completedDocsRule.ts
tslint.json

No rule logic is changed: just the types of scoping used to call it.

Converted completed-docs rule to use a function instead of a walker

---

src/rules/banCommaOperatorRule.ts
test/rules/ban-comma-operator/test.ts.lint

Rule `ban-comma-operator` raises an issue on every usage of comma operator, while using it inside for-loop incrementor IMO should be authorised. 
```typescript
for (let i = 0, j = 0; i < 10; i++, j++) {
}
```
[enhancement] `ban-comma-operator` ignores comma operator inside for-loop incrementor

ban-comma-operator: ignore for-loop incrementors

---

src/rules/fileHeaderRule.ts
test/rules/file-header/bad-shebang/test.ts.fix
test/rules/file-header/bad-shebang/tslint.json
test/rules/file-header/bad-single-line/test.ts.fix
test/rules/file-header/bad-single-line/tslint.json
test/rules/file-header/bad-use-strict/test.ts.fix
test/rules/file-header/bad-use-strict/tslint.json
test/rules/file-header/bad/test.ts.fix
test/rules/file-header/bad/tslint.json
test/rules/file-header/good/test.ts.fix

Adds a fixer to `file-header`. The rule will now insert text from a new second option as the header of your file if that option is provided and `--fix` is enabled. 
If the rule finds a header comment that's incorrect, it's replaced with the specified header. If the rule doesn't find a header comment at all, the specified header is inserted at the top of the document.
Is the newline handling legit? 
[new-fixer] `file-header`

[new-fixer] file-header rule

---

package.json
yarn.lock

[bugfix] Update commander.js dependency to prevent users from transitively installing a buggy 2.12.0 release

Updated version of commander.js package

---

.circleci/config.yml

CI fails on master because dependencies are not found in later jobs. That's because we cache dependencies by the checksum of yarn.lock.
If `yarn install` changes yarn.lock, all following jobs won't find the cache, because they use yarn.lock from git.
This change saves yarn.lock to the workspace and attaches the workspace before loading the dependency cache.
[no-log]

Fix CI failures with updated yarn.lock

---

src/rules/preferConstRule.ts
test/rules/prefer-const/default/test.ts.fix
test/rules/prefer-const/default/test.ts.lint

The `k` in `{[k: string]: string}` is a `ts.ParameterDeclaration`. It must not be treated like a parameter in the value domain.
IIRC I fixed a similar bug while rewriting `no-shadowed-variable`.
[bugfix] `prefer-const` false negative with index signature named like a variable

prefer-const: don't treat index signatures as parameters

---

src/rules/noUseBeforeDeclareRule.ts

[docs] Enhance `no-use-before-declare` documentation to clarify the rule's status

Update no-use-before-declare docs

---

src/rules/noShadowedVariableRule.ts
test/rules/no-shadowed-variable/default/ambient.d.ts.lint
test/rules/no-shadowed-variable/default/test.ts.lint

[bugfix] `no-shadowed-variable` now excludes declaration files and ambient modules
Fixes: #3088

no-shadowed-variable: ignore declaration files and ambient modules

---

src/rules/preferConditionalExpressionRule.ts
test/rules/prefer-conditional-expression/check-else-if/test.ts.lint
test/rules/prefer-conditional-expression/default/test.ts.lint

[bugfix] `prefer-conditional-expression`: don't repeat error on nested if statements
Fixes: #3350
To fix the above issue, only the change under the `// Be careful not to fail again for the "else if"` comment is necessary.
While adding tests, I noticed that `check-else-if` added the error on the inner `if` when nesting with blocks. I fixed that along the way which leads to a bigger refactor.

prefer-conditional-expression: avoid error on nested if statement

---

src/rules/completedDocsRule.ts
test/rules/completed-docs/accessors-public/test.ts.lint
test/rules/completed-docs/accessors-public/tsconfig.json
test/rules/completed-docs/accessors-public/tslint.json
test/rules/completed-docs/accessors/test.ts.lint
test/rules/completed-docs/accessors/tsconfig.json
test/rules/completed-docs/accessors/tslint.json
test/rules/completed-docs/defaults/test.ts.lint
test/rules/completed-docs/types/test.ts.lint

The `"properties"` for the `completed-docs` rule now checks `GetAccessor` and `SetAccessor` node types.
[enhancement] `"properties"` option for `completed-docs` rule now checks getter and setter accessors.

completed-docs: Added option to check get and set accessors.

---

src/rules/indentRule.ts

Add the `hasFix` property to the metadata of the `indent` rule.  
The [docs for this rule](https://palantir.github.io/tslint/rules/indent/) mention auto-fixing, but the green "**🔧 Has Fixer**" badge doesn't appear, which could lead people to assume (like I did) that this rule has no fixer.
Perhaps make the `hasFix` property required instead of optional so that rule authors are required to correctly set this properly.  Further more, maybe add a check to see if `hasFix: false` is set but the rule contains a call on the `Lint.Replacement`, or `Lint.RuleFailure` has something passed into the 6th parameter for a fix.

docs update - Add `hasFix` metadata for the indent rule

---

src/rules/oneLineRule.ts
test/rules/one-line/all/test.ts.fix
test/rules/one-line/all/test.ts.lint

[bugfix] `one-line` fixed crash on syntax error in class or interface
Fixes: #3537

one-line: avoid crash on parse error

---

src/rules/noMagicNumbersRule.ts
test/rules/no-magic-numbers/custom/test.ts.lint

- [x ] New feature, bugfix, or enhancement
- [x ] Includes tests
Enhancement of 'no-magic-number' based on issue #3514
[enhancement]: 'no-magic-numbers' ignores parseInt radix parameter

fix 'no-magic-number' ignores parseInt radix parameter

---

src/rules/completedDocsRule.ts
test/rules/completed-docs/types/test.ts.lint

[bugfix] `completed-docs`: don't require documentation on methods in object literals
Also simplifies some other checks.

completed-docs: exclude object literal methods

---

src/rules/noDuplicateSuperRule.ts
test/rules/no-duplicate-super/test.ts.lint

- [x ] Addresses an existing issue: #3275
- [x ] New feature, bugfix, or enhancement
- [x ] Includes tests
Added case for ternary operator in no-duplicate-super rule.
[bugfix] using ternary operator for calling super() now passes no-duplicate-super rule.

fix no-duplicate-super validates with ternary operator

---

src/rules/whitespaceRule.ts
test/rules/whitespace/all/test.ts.fix
test/rules/whitespace/all/test.ts.lint

- [x ] New feature, bugfix, or enhancement
- [x ] Includes tests
Added PropertyDeclaration to the whitespace rule walker.
[bugfix] 'whitespace' rule checks property declarations if 'check-decl' is enabled

fix whitespace rule with 'check-decl' also lint property declarations

---

src/rules/completedDocsRule.ts

Corrected the example config that uses `tags`.
Also, the published documentation says (incorrectly) that there is an "exists" property, but the committed docs correctly states that it's called "existence", so I guess the latest documentation just hasn't been pushed to the website yet.
[no-log] completed-docs: fixed example config for tags

completed-docs: corrected example config for tags

---

src/rules/arrowParensRule.ts
test/rules/arrow-parens/ban-single-arg-parens/test.ts.fix
test/rules/arrow-parens/ban-single-arg-parens/test.ts.lint

Fixer for ban-single-arg-parens doesn't add unnecessary whitespace before argument if parent node is a call expresion.
[bugfix] no unnecessary whitespace before argument in callback functions fixed with arrow-parens fixer

fix no unnecessary space before parameter from arrow-parens fixer

---

src/rules/objectLiteralSortKeysRule.ts
test/rules/object-literal-sort-keys/shorthand-first/test.ts.lint
test/rules/object-literal-sort-keys/shorthand-first/tslint.json

Fix #3606
Similar to PR #2831 but different implementation and focused only on shorthand-first
[new-rule-option] [object-literal-sort-key] Add shorthand-first option

[new-rule-option] [object-literal-sort-key] Add shorthand-first option

---

src/rules/banCommaOperatorRule.ts

#3611 1001 ### PR checklist   
correctly lists ban-comma-operator as a non-TS-specific rule; changes "type" from "typescript" to "functionality" (is that right?)
[docs] `ban-comma-operator`: fix metadata, list as "functionality" rule

[docs] [ban-comma-operator] metadata updates

---

src/rules/typeofCompareRule.ts

The condition was off. #3286 actually deprecated the rule only for typescript@2.1.
Well, not really, because `ts.versionMajorMinor` was introduced in a later release.
That means nobody gets a deprecation warning right now.
This PR fixes both issues.

fix condition for deprecation of typeof-compare

---

src/rules/noUnsafeAnyRule.ts
test/rules/no-unsafe-any/test.ts.lint

You can basically use everything in object spread. Therefore it should not be an error when spreading `any`.
The tests make sure we only allow object spread, not object rest.
`any` in array spread is not allowed. You need an `Iterable` there. I also added tests for this.
[bugfix] `no-unsafe-any` allows spreading an `any`-value into an object

no-unsafe-any: allow object spread

---

src/rules/callableTypesRule.ts
test/rules/callable-types/test.ts.fix
test/rules/callable-types/test.ts.lint

[bugfix] `callable-types` adds parentheses when fixing a type literal inside an array type

callable-types: add parens inside ArrayType

---

src/formatters/stylishFormatter.ts
test/formatters/stylishFormatterTests.ts

Make the filename clickable in IDE by adding `:line:col` of the first failure at the end of the filename. The line and column information has a transparent color. There will be no transparency in terminals without colors.
Do we need to add a note about this in the docs?
[enhancement] clicking the filename in `stylish`-formatter's output jumps to the first failure in that file.

stylish-formatter: make filename clickable

---

.vscode/launch.json

Show stdout in VSCode's debug console instead of only `console.log`.
https://github.com/Microsoft/vscode/issues/19750#issuecomment-332924834
[no-log]

launch.json: show stdout in debug console

---

test/rules/no-unnecessary-type-assertion/test.ts.fix
test/rules/no-unnecessary-type-assertion/test.ts.lint

Adds a test where type inference narrows a type and an assertion is needed.
It's already handled correctly. I just want to make sure this remains correct.
[no-log]

Add test for no-unnecesary-type-assertion

---

test/formatters/codeFrameFormatterTests.ts

While reviewing #3402 I notices that it contains two different expected results depending on the value of `chalk.enabled`. Before running the test `chalk.enabled` is set to true anyway. That makes it dead code. The expected plain text output was already outdated.
This PR removes the unused the plain text assertion.
I tried running running the test completely without colors. That didn't work for some reason.

remove test for plain test output

---

src/rules/strictTypePredicatesRule.ts
test/rules/strict-type-predicates/strict-null-checks/test.ts.lint

The rule didn't allow comparing `typeof foo` to anything but a string literal. Even NonSubstitutionTemplateLiteral was not allowed. This PR makes the rule less strict, but this doesn't really matter since the compiler already catches most errors.
[bugfix] `strict-type-predicates` allows comparing typeof result with non-literals
Fixes: #3508

strict-type-predicates: allow comparing typeof with expression

---

src/configs/all.ts
src/configuration.ts
src/rules/noDynamicDeleteRule.ts
test/rules/no-dynamic-delete/test.ts.fix
test/rules/no-dynamic-delete/test.ts.lint
test/rules/no-dynamic-delete/tslint.json

Equivalent to tslint-microsoft-contrib's no-delete-expression. Renamed because all deletes are technically of node kind DeleteExpression, though they may sometimes contain an expression as the argumentExpression.
Allowed string literals of invalid property accesses, numeric literals, and negative numeric literals because those can't be simplified.
Suggested fixes for converting valid string literals to direct lookups and simplified unnecessarily positive numbers (like `+7` to `7`).
Fixes #3553.
[new-rule] `no-dynamic-delete`

Added no-dynamic-delete rule

---

src/ruleLoader.ts
test/ruleLoaderTests.ts

Fixes #3638 
tslint-loader was using an undocumented feature which allowed `rulesDirectory` to be an empty string without warnings or errors: https://github.com/wbuchwalter/tslint-loader/blob/4d166651d916a0c43dd5a11099d6ff532350e27b/index.js#L59
This did expose a bug in tslint 5.9.0, though, because we started throwing an error prematurely before resolving the rulesDirectory path to an absolute path.

Resolve custom paths when loading rules

---

src/runner.ts

The support for the `noAssert` argument dropped in the upcoming
Node.js version 10.x and the argument should be removed therefore.
I would call it a bug fix. It can be argued against that just as well though.
Refs: https://github.com/nodejs/node/pull/18395
I was not able to compile anything and was not able to run the tests therefore.
I always got the following error: 
```
node_modules/tsutils/typeguard/type.d.ts(15,73): error TS2694: Namespace 'ts' has no exported member 'UniqueESSymbolType'.
```
Not sure what to choose here...

Remove buffers `noAssert` argument

---

src/rules/fileHeaderRule.ts

The rule `file-header` does not play nice with `no-trailing-whitespace` if the file header includes blank lines. For example, after applying `file-header` with `--fix`, you might end up with something like this:
```js
/* 
* Copyright My Company 2018
* 
* Project Identifier
* 
* All Rights Reserved, blah blah blah legal stuff.
*/
```
Note the trailing whitespace on the ` * ` lines. This means you would have to run `tslint --fix` *twice* to get the desired result.
This PR adds a simple solution of right-trimming each line of the file header.
[bugfix] Makes rule `file-header` play nice with rule `no-trailing-whitespace`

Removes trailing whitespace from file-header

---

package.json
src/rules/completedDocsRule.ts
src/rules/deprecationRule.ts
src/rules/noRedundantJsdocRule.ts
src/rules/typedefWhitespaceRule.ts
src/runner.ts
yarn.lock

Updates the package.json, fixes some compiler issues where some typescript APIs changed, and makes 2 rules work under 2.7.2.

Build tslint with TypeScript 2.7.2.

---

src/rules/noUnusedVariableRule.ts
test/rules/no-unused-variable/default/import.ts.lint

Changed to: "All imports on this line are unused"
Clarified lint message for "All imports are unused." , which suggests that all imports in the _file_ are unused, when the intention is all imports in the _line_.

Clarified lint message "All imports are unused."

---

src/rules/noEmptyRule.ts
test/rules/no-empty/allow-empty-functions/test.ts.lint
test/rules/no-empty/allow-empty-functions/tslint.json
test/rules/no-empty/default/test.ts.lint

Introduces option to allow function declarations to be empty while using `no-empty`.
This is my first PR to tslint, so any feedback is welcome.  
I was a bit unsure if I did the correct setup for the `options` property (an `array` with an `anyOf` of the two strings).
[enhancement] Introduces option to allow function declarations to be empty while using `no-empty`.

Add the option allow-empty-functions in no-empty

---

src/rules/commentFormatRule.ts
test/rules/comment-format/exceptions-pattern/test.ts.fix

- Add fixer for check-space option in comment-format rule
[new-fixer] `comment-format`

[new-fixer]: Add space before comment message fixer

---

src/rules/completedDocsRule.ts

- It was unclear to me if it works for JSDocs (because in another rule "JSDoc comment" is used instead of "Documentation"
- Updated the style for the inline code
supersedes https://github.com/palantir/tslint/pull/3006

Improved "complete docs" docs

---

src/rules/noUnboundMethodRule.ts
test/rules/no-unbound-method/default/test.ts.lint

Reading a property of the unbound method with square brackets, though rare, should be allowed because it's not related to whether `this` is bound.
No, but I'm happy to provide more details about where I needed this irl if necessary.
[bugfix] `no-unbound-method`: allow square bracket property access

no-unbound-method: add another exception

---

src/rules/noFloatingPromisesRule.ts

There are a few typos in the docs for the `no-floating-promises` rule.
[docs] Fix typos in the `no-floating-promises` rule docs.

Fix some typos in `no-floating-promises` rule docs.

---

docs/develop/custom-rules/index.md

🎉 Hey! Thanks for taking a look here at my PR 🙇 Grateful to be using TSLint 😎 I found a 404 while browsing the documentation 📝 
Fixes a link in the documentation.
[documentation]

Fix link to Configuration page

---

src/rules/code-examples/preferWhile.examples.ts
test/rules/prefer-while/test.ts.fix
test/rules/prefer-while/test.ts.lint

- Updated docs to make sense semantically (use vars that should exist in the scope of each for-loop)
- Updated tests with same issue
[docs] Updated `prefer-while` docs to be semantically correct

[docs] Fix prefer-while docs

---

src/rules/noEmptyRule.ts
test/rules/no-empty/allow-empty-catch/test.ts.lint
test/rules/no-empty/allow-empty-functions/test.ts.lint
test/rules/no-empty/default/test.ts.lint

I do like #3624 and I wanted to use it.
It already has support for classes, as it has special test case with constructor, which is handled differently.
Yet, class might need to have an empty method - and even if one is using `allow-empty-function`, then empty method is considered as violation.
When empty method may be valid? Class implements interface, want to provide empty implementation for abstract method from parent class or one is using ducktyping.
`[bugfix] allow-empty-functions option of no-empty rule is now properly respecting empty methods`

no-empty: fix lack of methods handling

---

src/rules/noDuplicateVariableRule.ts
src/rules/noShadowedVariableRule.ts
src/rules/preferConstRule.ts
src/tsconfig.json
test/tsconfig.json

Some Walker fields had to be initialized with inline initializers
instead of lazily intialized when .walk() is called.
Turns on a new TS strictness flag.
[no-log] internal change

Turn on strictPropertyInitialization for src/ and test/.

---

src/rules/noMagicNumbersRule.ts
test/rules/no-magic-numbers/custom/test.ts.lint
test/rules/no-magic-numbers/custom/tslint.json
test/rules/no-magic-numbers/default/test.ts.lint

The rule's `allowed-numbers` were mapped using the`String` constructor, which strips the `-` off of `-0`. Using `Object.is` because `0 === -0` in JS.

no-magic-numbers - support for negative zero

---

src/rules/code-examples/noUseBeforeDeclare.examples.ts
src/rules/noUseBeforeDeclareRule.ts
test/rules/no-use-before-declare/test.ts.lint

The rule checks that identifiers have a declaration with a `pos` <= to the reference `pos`, which isn't the case when destructuring w/ a rename. 
```ts
var { x: y } = { x: 43 };
```
Any edge cases with the destructuring syntax that would require additional tests?
[bugfix] [`no-use-before-declare`](https://palantir.github.io/tslint/rules/no-use-before-declare/) Fixes false positives when using the destructuring syntax (#3761)

bugfix - no-use-before-declare - exception for destructuring w/ rename

---

rules/no-floating-promises/index.html

Existing documentation for the no-floating-promises rule included a duplicate word and a typo, which has been addressed here.

Removed duplicate word from no-floating-promise docs

---

src/test.ts

JSON.stringify fails in some cases because its fails to convert circular structure to string

Handle tsconfig.json errors without using JSON.stringify

---

src/rules/noUnusedVariableRule.ts
test/rules/no-unused-variable/default/var.ts.lint
test/rules/no-unused-variable/ignore-pattern/var.ts.lint
test/rules/no-unused-variable/type-checked/destructuring.ts.lint

The latest versions of TS 2.9-nightly change how they report some diagnostics, this PR makes sure the rule doesn't throw given those changes.
However, the changes in 2.9 make it much more complex for this rule to work as intended, especially with respect to the `ignorePattern` option. As per the discussion in #3918, we henceforth deprecate the rule for TS 2.9 and later, since the compiler handles most of what this rules does adequately.
[deprecation] no-unused-variable is deprecated because typescript now covers most of its functionality

Deprecate no-unused-variable rule for typescript@next; also fix runtime error

---

test/rules/no-unused-variable/check-parameters/test.ts.lint
test/rules/no-unused-variable/default/class.ts.lint
test/rules/no-unused-variable/default/false-positives.ts.lint
test/rules/no-unused-variable/default/function.ts.lint
test/rules/no-unused-variable/default/import.ts.lint
test/rules/no-unused-variable/default/react-addons1.tsx.lint
test/rules/no-unused-variable/default/react-addons2.tsx.lint
test/rules/no-unused-variable/default/react-addons3.tsx.lint
test/rules/no-unused-variable/default/react1.tsx.lint
test/rules/no-unused-variable/default/react2.tsx.lint
test/rules/no-unused-variable/default/react3.tsx.lint
test/rules/no-unused-variable/default/react4.tsx.lint
test/rules/no-unused-variable/default/var.ts.lint
test/rules/no-unused-variable/ignore-pattern/var.ts.lint
test/rules/no-unused-variable/type-checked/destructuring.ts.lint
test/rules/no-unused-variable/type-checked/test.ts.lint

Fixes current test errors with TypeScript@next by disabling `no-unused-variable` tests when running against a version of TS that makes it deprecated
[no-log]

Don't run no-unused-variable tests when deprecated against version of TS

---

src/rules/encodingRule.ts
src/runner.ts

(node:16148) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
allocUnsafe should be fine because in both cases, the buffer is immediately filled and thrown out.

Use Buffer.allocUnsafe instead of the deprecated new Buffer()

---

src/rules/noImplicitDependenciesRule.ts
test/rules/no-implicit-dependencies/dev/test.ts.lint

I would like to modify current behavior of `no-implicit-dependencies` to include peer dependencies even if dev dependencies are set to be checked.
Currently `no-implicit-dependencies` considers by default dependencies and peer dependencies. When `dev` option is configured, it will consider dev dependencies instead of peer dependencies. This change makes `dev` option include peer dependencies, so it's no longer one or the other.
[rule-change] no-implicit-dependencies now always considers peer dependencies

no-implicit-dependencies always checks peer dependencies

---

src/rules/noImplicitDependenciesRule.ts
test/rules/no-implicit-dependencies/whitelist-with-dev/test.ts.lint
test/rules/no-implicit-dependencies/whitelist-with-dev/tslint.json
test/rules/no-implicit-dependencies/whitelist/test.ts.lint
test/rules/no-implicit-dependencies/whitelist/tslint.json

This allows you to specify a whitelist of modules that will not be part of package.json such as project-relative aliases
This adds an option to `no-implicit-dependencies` to specify dependencies that will be known not to be included in package.json such as project-relative imports.
[new-rule-option] [no-implicit-dependencies] whitelist

[new-rule-option] [no-implicit-dependencies] - add whitelist (#3839)

---

package.json
src/rules/noStringLiteralRule.ts
src/rules/noUnsafeAnyRule.ts
test/rules/no-implicit-dependencies/whitelist-with-dev/test.ts.lint
yarn.lock

`whitelist-with-dev` with option `"dev"`: the rule looks at both `dev` and `peer` dependencies, thus allowing `typescript` package to be used.
_As it turned out, there is another PR fixing this (https://github.com/palantir/tslint/pull/4011)_
Changes overview:
* the method was used in `noStringLiteralRule.ts`
* the method was used in `tsutils` (fixed in 2.27.2, version bumped)
* `tsutils@2.27.2` relies on typescript@2.9.x (version bumped)
* minor change in `noUnsafeAnyRule.ts` due to updated typings

Fix CI: no-implicit-dependencies test failure; typescript@next failure

---

src/rules/noConsoleRule.ts
test/rules/no-console/all/test.ts.lint

In the code below:
``` typescript
let x = [1, 2, 3];
console.log(x);
x.forEach(console.log);
```
The linter not warns only on line 2, but also on line 3

no-console: fix #3207

---

docs/usage/cli/index.md
src/index.ts
src/linter.ts
src/runner.ts
src/tslintCli.ts
test/linterTests.ts

Sometimes you may want to run linting but ignore any warnings produced, such as in a CI environment where you only want lint failures to fail the build (many runners will check both the exit code and STDERR to see if the program has passed).
This mimics the `quiet` flag available in ESLint, which hides errors from output when passed.
Adds a new CLI flag, `quiet`, to allow hiding of lint warnings.
What's the best way to test this? I've been having trouble trying to do it in the `linterTests`. I've been trying:
```typescript
const withWarningDeclaration =
`
console.log("This line will not pass linting with the default rule set");
`;
it("shows warnings", () => {
const config = DEFAULT_CONFIG;
config.rules.set("no-console", {
ruleArguments: ["log"],
ruleName: "no-console",
ruleSeverity: …
```

enhancement: Add quiet flag to hide warnings

---

src/rules/noInvalidTemplateStringsRule.ts
test/rules/no-invalid-template-strings/test.ts.lint

* Don't flag unmatched ${ in a regular string
* Also flag the entire expression, not just the opening brace
[enhancement] Don't flag unmatched ${ in no-invalid-template-strings

Reduce false positive rate in no-invalid-template-strings

---

src/rules/quotemarkRule.ts
test/rules/quotemark/backtick/test.ts.fix
test/rules/quotemark/backtick/test.ts.lint
test/rules/quotemark/backtick/tslint.json

This lets users enforce only backtick "`" strings for everywhere that it’s permissible.
> See #539
> The corresponding option in eslint is called "backtick": http://eslint.org/docs/rules/quotes
> See https://ponyfoo.com/articles/template-literals-strictly-better-strings
Adds an option "backtick" to "quotemark" rule, which would allow users to enforce "`" only strings where permissible.
[rule-change], [enhancement]

Add "backtick" option for quotemark

---

src/rules/preferMethodSignatureRule.ts
test/rules/prefer-method-signature/test.ts.fix
test/rules/prefer-method-signature/test.ts.lint

Correct the broken auto-fix code of `prefer-method-signature` rule.
[bugfix] Correct the auto-fix code of `prefer-method-signature` rule, now capable to handle 
multiline signature.

Fix4057 Correct the broken auto-fix code of `prefer-method-signature` rule.

---

src/configs/all.ts
src/rules/commentTypeRule.ts
test/rules/comment-type/combo/test.ts.lint
test/rules/comment-type/combo/tslint.json
test/rules/comment-type/directive/test.ts.tslint
test/rules/comment-type/directive/tslint.json
test/rules/comment-type/doc/test.ts.lint
test/rules/comment-type/doc/tslint.json
test/rules/comment-type/multiline/test.ts.lint
test/rules/comment-type/multiline/tslint.json
test/rules/comment-type/single-line/test.ts.lint
test/rules/comment-type/single-line/tslint.json

Adds a new rule `comment-type` which allows you to specify the type of comments you allow in your project.
[new-rule] comment-type

[new-rule] add comment-type rule

---

src/rules/oneLineRule.ts
test/rules/one-line/all/test.ts.fix
test/rules/one-line/all/test.ts.lint

This rule previously did not check the block in `case 0: { ... }` because `isBlockLike` returns true for `CaseClause`s.
[bugfix] `one-line`: Check block in a case clause

one-line: Check block in case clause

---

src/rules/fileNameCasingRule.ts
src/utils.ts
test/rules/file-name-casing/snake-case/NoPascalCase.lint
test/rules/file-name-casing/snake-case/no-camel-case.ts.lint
test/rules/file-name-casing/snake-case/tslint.json

Adds an option to enforce snake-cased filenames (follow-up to #3434).
Fixes #4088 
[new-rule-option]: `"snake-case"` in `"file-name-casing"`

Add snake_case option for file-name-casing rule

---

docs/usage/configuration/index.md
src/configuration.ts
test/configurationTests.ts

jsRules can now be a boolean. If it is set to true then parseConfig file, will copy over all active rules that can be applied to js to the jsRules configuration.
I added comments to the files changed

feat(configuration): set js rules to all valid active rules

---

src/rules/completedDocsRule.ts
test/rules/completed-docs/interface-members/test.ts.lint
test/rules/completed-docs/interface-members/tsconfig.json
test/rules/completed-docs/interface-members/tslint.json
test/rules/completed-docs/types/test.ts.lint

Properties and methods in interfaces were not being analyzed by the `completed-docs` rule. Now they are.
Nope.
[enhancement] completed-docs: check properties and methods in interfaces

completed-docs: methods and properties on interfaces are checked.

---

src/rules/whitespaceRule.ts
test/rules/whitespace/check-postbrace/test.ts.fix
test/rules/whitespace/check-postbrace/test.ts.lint
test/rules/whitespace/check-postbrace/tslint.json

Implements a whitespace option `check-postbrace` that is checking for a space, new line or tab after an open curly brace.

[new-rule] add whitespace rule for open braces

---

src/configuration.ts
src/linter.ts
src/runner.ts

- ~~[ ] Documentation update~~
Moves `isFileExcluded` from runner to configuration, then import it to both runner and linter.
No documentation update because this is already what is expected from the existing documentation.
[bugfix] allow `exclude` to work with node API

fix(#3881): allow `exclude` to work with node API

---

docs/usage/configuration/index.md
src/configuration.ts
src/runner.ts
src/tslintCli.ts
test/config/tslint-custom-rules-with-dir-and-format.json
test/executable/executableTests.ts

Makes it possible to configure the lint formatter from the config file.

Configure format from file

---

src/rules/alignRule.ts

Fix a typo in the options description for the "align" rule.
[docs] Fix docs typo

[docs] Fix typo in align docs

---

src/tslintCli.ts

It seems like the codebase is ready for both `string` and `string[]` for `rulesDirectory`, hence the change is just a cli option creation. _(I have traced it back to `Linter > getEnabledRules > arrayify`)_
⚠️ It seems, also, that there are no tests for this use case, at least i haven't found one. 
✅ The current test suit passes.

feat: make cli expect array for rules dir

---

src/formatters/proseFormatter.ts
test/formatters/proseFormatterTests.ts

Changed the prose formatter to use the format:
```
file:line:column - message
```
instead of:
```
file[line, column]: message
```
Nope.
[enhancement] prose formatter uses `line:column` instead of `[line, column]`

Used colons for separating the line and character number in prose formatter

---

src/rules/whitespaceRule.ts
test/rules/whitespace/all/test.ts.fix
test/rules/whitespace/all/test.ts.lint

- ~[ ] Documentation update~
The missing whitespace after open brace is marked as an error.
(It didn't work with 'as' statement)

fix(#4210): fix whitespace rule in importClause with 'as' statement

---

src/rules/whitespaceRule.ts
test/rules/whitespace/all/import-type.lint

Don't check for space after `import` in `TypeQuery`
[bugfix] `whitespace` Don't require space between import and paren with in type imports

Don't check space after import-ed type. Fixes #3987

---

.vscode/launch.json

Just a small typo fix in launch.json. The name of tslintCli.ts was changed in #3978 but the line in the VS Code file was not.
n/a
n/a

Fix typo in launch.json

---

src/formatters/vsoFormatter.ts

Documentation is updated as VSO, VSTS is now known as AzureDevOps.

Includes new name Azure DevOps for VSO

---

src/rules/fileNameCasingRule.ts
test/rules/file-name-casing/complex/InvalidNonComponentName.ts.lint
test/rules/file-name-casing/complex/invalid-component-name.tsx.lint
test/rules/file-name-casing/complex/my-button.component.ts.lint
test/rules/file-name-casing/complex/tslint.json

fixes #4220. Fixes #4071
Following #4220 we could pass a key-value pair where the key represents a regex that will be used
for matching against the names.
A little caveat, the regex is always a termination regex.
For example:
`.component.tsx` is actually `.component.tsx$` (notice the `$`).
Allowing arbitrary Regex is a rabbit hole, at least this way we ware safe to remove the last part of the Regex from the string and be able to check the remaining name, since we do not want to check validate the regex section of the name.
I am missing the correct `options` configuration, I am not sure what is the correct config.
```
[enhancement] file-name-casing-rule supports regex expression for matching file
```

Add support for complex matching to file-name-casing-rule

---

src/rules/preferObjectSpreadRule.ts

Support for spread properties in object literals wasn't added until
ES2018, not ES2015.  The proposal is here:
https://github.com/tc39/proposal-object-rest-spread
And MDN documents it as such too:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Spread_in_object_literals

prefer-object-spread: this is new to ES2018, not ES2015

---

src/rules/noMagicNumbersRule.ts
test/rules/no-magic-numbers/custom/test.ts.lint
test/rules/no-magic-numbers/default/test.ts.lint

I just fixed an issue about showing the offending value for no-magic-numbers rule.
Before:
`'magic numbers' are not allowed`
Now:
`'magic numbers' are not allowed: 3`
I didn't create one for such a small thing. Should I?

Show offending value in 'no-magic-numbers' error message

---

src/rules/noUnusedExpressionRule.ts

Typo correction on "no-unused-expression" rule : 
Three arguments are available but the description says that only  **two** may be provided.

Corrects typo (no-unused-expression)

---

test/configurationTests.ts

Several of the tests in configurationTests.ts make comparisons on config rules using assert.deepEqual, which doesn't work on Maps. Because of this, configs that differed could still pass the tests. This commit fixes that by calling demap on the maps before the comparisons.
This is strictly fixing the tests. One quirk I noticed is boolean configurations result in `[]` as the rule arguments, while normal configurations result in `undefined`. If this behavior is not desired, it should probably be fixed in a separate PR.

Fix configuration tests when comparing rules

---

src/rules/noShadowedVariableRule.ts

- [v] Addresses an existing issue: #4306 
- [v] Documentation update
Clarify the rationale behind `no-shadowed-variable` and add some references.
I couldn't find a way to run documentation locally, so I am not too sure how it would look like on Jekyll. It would be great to have a documentation on running docs locally.
N/A

Clarify no-shadowed-variable doc (#4306)

---

src/rules/semicolonRule.ts
test/rules/semicolon/never/test.ts.fix
test/rules/semicolon/never/test.ts.lint

`SemicolonNeverWalker.checkVariableStatement` handles the case where `declarations` is an empty array.
1. Is there any documentation that needs to be updated as a result of this change?
2. Unsure if better to export one of the existing utility functions:
- `last` (`memberOrderingRule.ts`)
- `arrayLast` (`switchFinalBreakRule.ts`).

Fix semicolon: Cannot read property 'initializer' of undefined

---

src/configuration.ts
test/config/tslint-with-merge.yaml
test/configurationTests.ts

This will change the yaml parser to use the default schema, which allows some additional Yaml types, see http://yaml.org/type/
Namely, this will allow the merge syntax, allowing users to define common rules and then merge them into the typescript and javascript rules.
For a full list of the additional Yaml types added, see the [js-yaml schema definition](https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/schema/default_safe.js).
Note: This change removes the options passed to `yaml.safeLoad` since they are no longer required. The default safe schema is what we want, and the `strict: true` is not a valid option, since js-yaml removed it a while back, see here: https://github.com/nodeca/js-yaml/commit/e6bac15
[enhancement] Yaml parser now uses default schema, allowing for `<<:` to be …

Use default js-yaml schema

---

src/language/formatter/formatter.ts
src/rules/callableTypesRule.ts
src/rules/noInferredEmptyObjectTypeRule.ts
test/rules/callable-types/test.ts.fix
test/rules/callable-types/test.ts.lint

Walker for `callable-types` rule handles the case where an interface contains a single construct signature declaration.
[bugfix][`callable-types`](https://palantir.github.io/tslint/rules/callable-types/) support interfaces containing a single construct signature (#4291)

Fix callable-types should handle `new(): T` just like `(): T`

---

src/rules/noVoidExpressionRule.ts
test/rules/no-void-expression/default/test.ts.lint
test/rules/no-void-expression/ignore-arrow-function-shorthand/test.ts.lint

The no-void-expression rule currently warns in this case:
x && console.log(x);
I think this can be accepted, since it's a common way to make a compact
"if".
Same with the ignore-arrow-function-shorthand option, tslint currently
warns for:
[].forEach(x => x && console.log(x))
This patch changes the rule to accept these.
Fixes #4297
Fixes #2919
See commit message above.
No.
[bugfix] The no-void-expression rule now accepts void expressions as arguments of boolean binary operators (e.g.: x && console.log(x)).

[no-void-expression] Allow void expressions in binary expressions

---

.circleci/config.yml

Node 4 is no longer supported.
This unblocks https://github.com/palantir/tslint/pull/4274

Changes the node version from 4 to 6 for TS 2.1 tests.

---

src/rules/returnUndefinedRule.ts
test/rules/return-undefined/test.ts.lint

Added check for generators => handle them as `ReturnKind.Void` in the corresponding rule.
* I check for `FunctionLikeDeclarationBase.asteriskToken` to detect generators. Is this the best way?
[bugfix] Added exception for generators in `return-undefined` rule

Add exception for generators in "return-undefined" rule

---

package.json
scripts/custom-typings.d.ts
yarn.lock

* The typings are now included in the package (see https://github.com/lydell/json-stringify-pretty-compact/pull/16).
* This fixes "node_modules/json-stringify-pretty-compact/index.d.ts:7:12 - error TS2300: Duplicate identifier 'stringify'" compile errors.
n/a

Update 'json-stringify-pretty-compact' to 1.2.0 and remove unnecessary type declaration

---

src/formatters/junitFormatter.ts
test/formatters/junitFormatterTests.ts

This updates the JUnit formatter to use the required property `classname`.
This change is related to an issue for [Gitlab-CE](https://gitlab.com/gitlab-org/gitlab-ce/issues/50964) which has problems with displaying JUnit results if they are missing the `classname` property.
Not sure if we should add other properties which are required, but cannot be filled with a proper value like `time` or `tests` and `errors`. These could be filled with a dummy value, but I would rather leave them out.
[enhancement] `Improve JUnit formatter`

Improve JUnit formatter

---

src/rules/noImplicitDependenciesRule.ts
test/rules/no-implicit-dependencies/whitelist/test.ts.lint
test/rules/no-implicit-dependencies/whitelist/tslint.json

For the rule `no-implicit-dependencies` an array of whitelisted modules can be added. However, this didn't work when trying to whitelist a module that started with an `@` symbol.
This is important since projects with custom paths in their compiler options can now use this lint configuration option without the false positives.
With this change, the rule can be used as follows.
```json
"no-implicit-dependencies": [true, ["@components", "@app"]]
```
[bugfix]

allow whitelisted modules to start with `@` symbol

---

src/rules/noInvalidThisRule.ts
test/rules/no-invalid-this/enabled/test.ts.lint

* Keep track of evaluation context: look to the closest parent function
and decide if it is allowed to refer to `this`
* Fix a false negative in the tests from #3267
Previously, the `no-invalid-this` rule only had shallow tracking of context. `this` should be allowed if any only iff the closest parent non-arrow function is either a) a class method, or b) a function with a `this` type parameter.
There were several drawbacks of not tracking context directly:
- The rule didn't treat method declaration syntax the same as function declaration syntax on object literals, causing a false positive on method declaration syntax in object literals (#4033)
- The rule could not distinguish between a correct function with a `this` type parameter and a function _inside_ a function with a `this` type …

no-invalid-this: false positive for method syntax

---

src/configs/all.ts
src/rules/noDefaultImportRule.ts
test/rules/no-default-import/default/test.ts.lint
test/rules/no-default-import/default/tslint.json
test/rules/no-default-import/fromModules/test.ts.lint
test/rules/no-default-import/fromModules/tslint.json

As the `no-default-export`, the rule supposed to reduce usage of default imports/exports.
New rule supposed to narrow the scope of your changes in the case of medium-sized (and bigger) projects. Say, you have 20 packages and every removed default export from utility package would lead to changes in each package, which might be harder to get merged by various reasons (harder to get your code approved due to a number of required reviewers; longer build time due to a number of affected packages). That's why "requires too many changes elsewhere" is a reason why I see `no-default-export` ignored so often.
Unlike `no-default-export`, the rule requires you to make changes only in the package you work on and the package you import from (unless the member you try to import already exported as a …

[new-rule] no-default-import

---

src/rules/orderedImportsRule.ts
test/rules/ordered-imports/grouped-imports/test.ts.fix
test/rules/ordered-imports/grouped-imports/test.ts.lint

As stated in #3727 when enforcing grouping we should also enforce there is at most one group of imports of the same type in the file. 
[enhancement] When `grouped-imports` option of the `ordered-imports` rule is set, the fact that imports of the same type are all in one group is also checked.

ordered-imports: check that all imports of the same type are groupped

---

src/rules/noObjectLiteralTypeAssertionRule.ts
test/rules/no-object-literal-type-assertion/test.ts.lint

Allow unknown in 'no-object-literal-type-assertion' rule.

---

src/configs/all.ts
src/configs/recommended.ts
src/rules/code-examples/functionConstructor.examples.ts
src/rules/functionConstructorRule.ts
test/rules/function-constructor/test.ts.lint
test/rules/function-constructor/tslint.json

Blocks using the `Function()`/`new Function()` methods to create new functions.
Fixes #3554.
[new-rule] `function-constructor`

Added function-constructor rule

---

test/executable/executableTests.ts

Fix test that failed locally because it took too long. Not sure why this is only becoming an issue now - could be something that got added, but for now we may as well get 5.12 released and then figure it out.

Fix failing test

---

src/rules/noDefaultImportRule.ts

Fix typo in the description for no-default-import rule.
[docs] Fix docs typo

[docs] Fix typo in no-default-import

---

docs/circle.yml

Updated the old gems on the gh-pages branch to find out we need to bump the minor version of ruby too.

Bump docs ruby minor version to 2.3.7

---

src/configs/latest.ts
src/configs/recommended.ts

Addresses the issue I brought up in https://github.com/palantir/tslint/pull/4198#issuecomment-449134147
Also enables some v5.12 rules in `tslint:latest`

Revert breaking change to tslint:recommended, update tslint:latest

---

src/rules/arrayTypeRule.ts
test/rules/array-type/array-simple/test.ts.fix
test/rules/array-type/array-simple/test.ts.lint
test/rules/array-type/array/test.ts.fix
test/rules/array-type/array/test.ts.lint
test/rules/array-type/generic/test.ts.fix
test/rules/array-type/generic/test.ts.lint

Add unknown to the simple types. Updated tests to test this functionality.
[bugfix] `unknown` is recognized as simple type in `array-type`

Add unknown as simple type to `array-type`

---

src/rules/strictBooleanExpressionsRule.ts
test/rules/strict-boolean-expressions/ignore-rhs/test.ts.lint
test/rules/strict-boolean-expressions/ignore-rhs/tsconfig.json
test/rules/strict-boolean-expressions/ignore-rhs/tslint.json

If specified, the right-hand operand of `&&` and `||` will not be checked
as a strict boolean expression.
[new-rule-option] `strict-boolean-expressions` accepts `ignore-rhs` option to disable checking the right-hand side of the `&&` and `||` operators as strictly boolean.

Add `ignore-rhs` option for `strict-boolean-expressions`

---

src/test.ts
src/verify/lines.ts
src/verify/parse.ts
test/rule-tester/linesTests.ts
test/rule-tester/parseTests.ts

I added more tests on the changes in this PR: https://github.com/palantir/tslint/pull/4390
Please check if the tests are idiomatic for the project
[enhancement] Mention file names in test script parse failures

Mention file names in script parse failures (#4381)

---

src/rules/strictTypePredicatesRule.ts
test/rules/strict-type-predicates/strict-null-checks/test.ts.lint
test/rules/strict-type-predicates/unknown/test.ts.lint
test/rules/strict-type-predicates/unknown/tsconfig.json
test/rules/strict-type-predicates/unknown/tslint.json

Fixes the issue where a comparison with unknown would falsly give an error. Instead, comparison with unknown should always be allowed.
[bugfix] fix `strict-type-predicate` with `unknown`

Fix strict-type-predicate for unknown

---

src/rules/quotemarkRule.ts
test/rules/quotemark/avoid-template/tslint.json
test/rules/quotemark/double-avoid-template/test.ts.fix
test/rules/quotemark/double-avoid-template/test.ts.lint
test/rules/quotemark/double-avoid-template/tslint.json
test/rules/quotemark/single-avoid-escape/tslint.json
test/rules/quotemark/single-avoid-template/test.ts.fix
test/rules/quotemark/single-avoid-template/test.ts.lint
test/rules/quotemark/single-avoid-template/tslint.json

Add an additonal check to make sure we never render a warning of the format `" should be "` or ``` ` should be ` ```.
Whats the best test for this? I couldn't find a way to write a test that failed before making this fix, but I feel like we shouldn't merge this without one.
[bugfix] fix some `quotemark` issues when using backticks with the `avoid-template` option

Fix quotemark avoid-template issues

---

src/rules/trailingCommaRule.ts

FIxes an uncaught exception thrown by `trailing-comma`.
[bugfix] `trailing-comma`

trailing-comma: check for a closing parenthesis

---

src/rules/noUnboundMethodRule.ts
test/rules/no-unbound-method/whitelist/test.tsx.lint
test/rules/no-unbound-method/whitelist/tsconfig.json
test/rules/no-unbound-method/whitelist/tslint.json

Added configuration option to whitelist methods and operators for `no-unbound-method` rule, so that it will not report errors in cases such as:
`expect(x.method).toHaveBeenCalled()`
`typeof x.method === 'function'`
Please verify that options for this rule are backwards compatible.
[new-rule-option] Added `whitelist` option to `no-unbound-method`

Whitelist option for `no-unbound-method`

---

src/rules/curlyRule.ts
src/rules/newlineBeforeReturnRule.ts
src/utils.ts
test/rules/newline-before-return/default/test.ts.fix
test/rules/newline-before-return/default/test.ts.lint
test/rules/newline-before-return/default/test.tsx.fix

I've realized that **newline-before-return** didn't have a fixer which seems to be quite straightforward. Here are my two cents. 
I've added tests and everything seems OK.
[new-fixer] added fixer for **newline-before-return** rule

Added fixer for newline-before-return rule

---

src/rules/banRule.ts
test/rules/ban/test.ts.lint
test/rules/ban/tslint.json

Fix a bug where `a.b.c()` may also match with `a.c()`.
[bugfix] `ban`: Fix a false positive which would occur when banning method calls nested inside objects. Previously, banning `["a", "b", "c"]` would trigger lint failures on the syntax `b.c()`, which was not the intent of this rule.

Fix [ban]: wrong logic matching deeply nested methods

---

src/language/walker/programAwareRuleWalker.ts
src/language/walker/ruleWalker.ts
src/language/walker/scopeAwareRuleWalker.ts

Fixes #4298
- [ x] Addresses an existing issue: #4298

Mark RuleWalker and ProgramAwareRuleWalker as deprecated

---

docs/usage/configuration/index.md
src/configuration.ts
test/configurationTests.ts

Changed behavior of `jsRules:true` to copy over ALL rule configurations that are compatible with JS, including any that are explicitly disabled.
The original PR (https://github.com/palantir/tslint/pull/3641) that added `jsRules:true` functionality seemed to make a point to describe its desired/implemented behavior to copy over all "active" rules that are valid for JS. Does the term "active" mean something special that is not simply "those that are not disabled"? Is there still some kind of rule configurations that I should be skipping over?
[bugfix] Explicit disabling of rules is now copied over to jsRules when using jsRules:true

Fix behavior of jsRules:true to include explicitly disabled rules.

---

src/rules/quotemarkRule.ts
test/rules/quotemark/backtick/test.ts.fix
test/rules/quotemark/backtick/test.ts.lint

Don't use backticks instead of single/double quotes when it breaks TypeScript syntax.
Any other edge cases.
[bugfix] `quotemark: backtick` no longer incorrectly flags string literals that must use single/double quotes

Fix #4514: [quotemark: backtick] Incorrectly flags string literals that must use single/double quotes

---

src/configs/all.ts
src/language/rule/rule.ts
src/rules/code-examples/staticThis.examples.ts
src/rules/staticThisRule.ts
src/rules/unifiedSignaturesRule.ts
test/rules/static-this/test.ts.fix
test/rules/static-this/test.ts.lint
test/rules/static-this/tslint.json

Implement static-this rule
[new-rule]

Implement static-this rule (#4428)

---

src/rules/whitespaceRule.ts

The whitespace rule allows using up to eleven arguments in the configuration (not ten).

Fix metadata of the whitespace rule

---

src/formatters/checkstyleFormatter.ts
src/language/formatter/abstractFormatter.ts

Fixes #4555 
[bugfix] Fixed regression in CheckstyleFormatter backwards compatibility

Fix regression in CheckstyleFormatter backwards compatibility

---

src/rules/promiseFunctionAsyncRule.ts
test/rules/promise-function-async/test.ts.lint

Single statement lamda functions that delegate to another promise-returning function are allowed.
**Configuration**
```json
{
"rules": {
"promise-function-async": true
}
}
```
**Before**
```typescript
public async asyncPromiseMethodB() {
return new Promise<void>();
}
public delegatingMethod = () => this.asyncPromiseMethodB(1);
~~~~~ [functions that return promises must be async]
```
**After**
```typescript
public async asyncPromiseMethodB() {
return new Promise<void>();
}
public delegatingMethod = () => this.asyncPromiseMethodB(1);
// No lint error
```
[enhancement] `promise-function-async` now allows single statement lamda functions that delegate to another promise-returning function

Address 2637: Relax promise-function-async for short arrow functions

---

src/rules/whitespaceRule.ts
test/rules/whitespace/all/test.ts.fix
test/rules/whitespace/all/test.ts.lint

Adds a case to handle ExportDeclaration, to properly lint and fix statements such as:
```ts
export { A, B };
```
[bugfix] Lint export statements with `whitespace` rule

Add whitespace rule for ExportDeclaration

---

docs/formatters/index.md

Add note to docs clarifying positioning as zero-indexed for machine formatters
cc @JoshuaKGoldberg

Docs: add note to docs about zero-indexing for machine formatters

---

src/rules/noUnboundMethodRule.ts
test/rules/no-unbound-method/default/test.tsx.lint
test/rules/no-unbound-method/whitelist/test.tsx.lint
test/rules/no-unbound-method/whitelist/tslint.json

Added configuration option to `no-unbound-method` that does allows not reporting errors in `delete` statements `delete obj.method;`
[new-rule-option] Added `allow-delete` option to `no-unbound-method` rule

Add `allow-delete` option to `no-unbound-method` rule

---

src/rules/noTrailingWhitespaceRule.ts
test/rules/no-trailing-whitespace/zero-width-no-break-space/test.ts.lint
test/rules/no-trailing-whitespace/zero-width-no-break-space/test2.ts.lint
test/rules/no-trailing-whitespace/zero-width-no-break-space/tslint.json

Temporary fix to handle files starting with a byte order mark (see https://github.com/ajafff/tsutils/issues/94).
[bugfix] `no-trailing-whitespace` no longer flags files starting with a byte order mark

fix for #4518: (no-trailing-whitespace) flags leading empty line as error

---

src/rules/noShadowedVariableRule.ts
test/rules/no-shadowed-variable/default/test.ts.lint
test/rules/no-shadowed-variable/ignore-underscore/test.ts.lint
test/rules/no-shadowed-variable/ignore-underscore/tslint.json

Add option to ignore shadowed underscore.
**Usage**
```json
{
"rules": {
"no-shadowed-variable": [true, {"underscore": false}]
}
}
```
**Before**
```javascript
import _ = require('lodash');
function foo(_) {
~ [Shadowed name: '_']
console.log(_);
}
```
**After**
```javascript
import _ = require('lodash');
function foo(_) {
// No lint error
console.log(_);
}
```
Have I made all the necessary changes to documentation?
[enhancement]: added option to `no-shadowed-variable` to ignore shadowed underscores

Implement 4201: add option to ignore shadowed underscore

---

src/formatters/junitFormatter.ts
test/formatters/junitFormatterTests.ts

This fixes an issue with the junit formatter. Successful test cases are now output when files are linted without error.

Add junit output for files which are successfully linted.

---

src/rules/completed-docs/exclusionFactory.ts
src/rules/completed-docs/exclusions.ts
src/rules/completedDocsRule.ts
test/rules/completed-docs/accessors-public/tsconfig.json
test/rules/completed-docs/accessors/tsconfig.json
test/rules/completed-docs/defaults/tsconfig.json
test/rules/completed-docs/functions/overloads-separate-docs/default/test.ts.lint
test/rules/completed-docs/functions/overloads-separate-docs/default/tslint.json
test/rules/completed-docs/functions/overloads-separate-docs/false/test.ts.lint
test/rules/completed-docs/functions/overloads-separate-docs/false/tslint.json
test/rules/completed-docs/functions/overloads-separate-docs/true/test.ts.lint
test/rules/completed-docs/functions/overloads-separate-docs/true/tslint.json
test/rules/completed-docs/interface-members/tsconfig.json
test/rules/completed-docs/locations/tsconfig.json
test/rules/completed-docs/methods/overloads-separate-docs/default/test.ts.lint
test/rules/completed-docs/methods/overloads-separate-docs/default/tslint.json
test/rules/completed-docs/methods/overloads-separate-docs/false/test.ts.lint
test/rules/completed-docs/methods/overloads-separate-docs/false/tslint.json
test/rules/completed-docs/methods/overloads-separate-docs/true/test.ts.lint
test/rules/completed-docs/methods/overloads-separate-docs/true/tslint.json
test/rules/completed-docs/privacies-private/tsconfig.json
test/rules/completed-docs/privacies-protected/tsconfig.json
test/rules/completed-docs/privacies-public/tsconfig.json
test/rules/completed-docs/privacies/tsconfig.json
test/rules/completed-docs/tags/content/tsconfig.json
test/rules/completed-docs/tags/existence/tsconfig.json
test/rules/completed-docs/types/tsconfig.json
test/rules/completed-docs/variables/tsconfig.json
test/rules/completed-docs/visibilities/tsconfig.json

Opt-in (false by default) boolean flag that can be applied to functions and methods to require their overloads each receive their own documentation comment.
Also deleted a bunch of unnecessary `tsconfig.json` files that were still in the tests directory for completed-docs. I should have removed them when converting it to TypeScript.
[new-rule-option] `completed-docs`: `overloads` option to enforce documentation of each overload signature

Added an overloads option in completed-docs

---

CHANGELOG.md
package.json
src/linter.ts

- [bugfix] `backtick` option for [`quotemark`](https://palantir.github.io/tslint/rules/quotemark/) rule no longer incorrectly flags string literals that must use single/double quotes (#4535)
- [bugfix] Fixed regression in CheckstyleFormatter backwards compatibility (#4561)
- [bugfix] [`whitespace`](https://palantir.github.io/tslint/rules/whitespace/) rule now lints export statements (#4554)
- [bugfix] [`no-trailing-whitespace`](https://palantir.github.io/tslint/rules/no-trailing-whitespace/) no longer flags files starting with a byte order mark (#4543)
- [enhancement] [`promise-function-async`](https://palantir.github.io/tslint/rules/promise-function-async/) now allows single statement lamda functions that delegate to another promise-returning function (#4553)
- [enhancement] Add note to …

Prepare release v5.14.0

---

src/rules/staticThisRule.ts
test/rules/static-this/test.ts.fix
test/rules/static-this/test.ts.lint

Fix #4579: false positive static-this in HOC

---

package.json
yarn.lock

Upgrade `js-yaml` to avoid Denial of Service
Based on the [npm audit](https://www.npmjs.com/advisories/788), there is an security issue with `js-yaml`, so upgrade to the latest version to fix.

Upgrade js-yaml to avoid Denial of Service

---

src/rules/orderedImportsRule.ts
test/rules/ordered-imports/groups-complex/test.ts.fix
test/rules/ordered-imports/groups-complex/test.ts.lint

Existing replacement code deletes lines around import declarations if they contain any line break. This means it deletes actual code in the case where a fragment of text has both line breaks and characters.
An ideal fix would be to keep the (previously deleted) code as close to the import it depends on...assuming it depends on an import at all. Of course, this ramps up the complexity, because any given line of code could use a combination of imports.
This fix results in the code just appearing below the import blocks in the order they were processed.
[bugfix] fix linebreak handling in `ordered-imports`

ordered-imports: don't remove linebreaks if text contains non-whitespace characters

---

src/rules/noVoidExpressionRule.ts
test/rules/no-void-expression/default/test.ts.lint

Allow void expressions in conditional expressions.
Any extra test cases you would like me to cover?
[bugfix] `no-void-expression` now allows conditional expressions

Fix #4556 - False positive: No void expression

---

src/rules/interfaceNameRule.ts
test/rules/interface-name/always-prefix/test.ts.lint
test/rules/interface-name/never-prefix/test.ts.lint

Interface name (never-prefix) doesn't return error for I18nSomething
[bugfix] `interface-name` now handles interface starting with "I18n" correctly

Handle I18n case

---

src/configs/all.ts
src/configuration.ts
src/rules/noNullUndefinedUnionRule.ts
src/rules/noUnusedVariableRule.ts
test/rules/no-null-undefined-union/test.ts.lint
test/rules/no-null-undefined-union/tsconfig.json
test/rules/no-null-undefined-union/tslint.json

[new-rule] `no-null-undefined-union`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/palantir/tslint/4589)

Add "no-null-undefined-union" rule.

---

src/rules/noNullUndefinedUnionRule.ts
src/rules/quotemarkRule.ts
test/rules/quotemark/backtick/test.ts.fix
test/rules/quotemark/backtick/test.ts.lint

This commit fixes the cases where export statements, string literal type as generic type parameter, and string literals in object literal property assignments were incorrectly flagged. This also fixes a small lint error (specifying a type parameter same as default).
This commit fixes the cases where export statements, string literal type as generic type parameter, and string literals in object literal property assignments were incorrectly flagged. This also fixes a small lint error (specifying a type parameter same as default).
Make sure the tests capture all the use cases.
[bugfix] quotemark: backtick should no longer flag strings that require single/double quotes

Excuse edge cases in quotemark backtick (#4588)

---

src/rules/unnecessaryConstructorRule.ts
test/rules/unnecessary-constructor/test.ts.lint

This commit checks the modifiers of each constructor declaration. If it has any modifier that isn't `public`, then it is actually necessary and shouldn't be flagged.
Iterate through the modifiers of each constructor declaration. If it has any modifiers that isn't `public`, keep it.
[bugfix] unnecessary-constructor: don't flag constructors that are actually necessary

Check for non-public modifiers in constructors (#4511)

---

CHANGELOG.md
package.json
src/linter.ts

- [bugfix] [`no-void-expression`](https://palantir.github.io/tslint/rules/no-void-expression/) now allows conditional expressions (#4606)
- [bugfix] fix linebreak handling in [`ordered-imports`](https://palantir.github.io/tslint/rules/ordered-imports/) (#4583)
- [bugfix] fix [`static-this`](https://palantir.github.io/tslint/rules/static-this/) false positive for higher order components (#4580)
- [bugfix] Fixed crash in [`unnecessary-else`](https://palantir.github.io/tslint/rules/unnecessary-else/) from blank `if` statements (#4603)
- [bugfix] Fixed false positive in [`unnecessary-else`](https://palantir.github.io/tslint/rules/unnecessary-else/) after non-jumping statement (#4603)
- [bugfix] [`interface-name`](https://palantir.github.io/tslint/rules/interface-name/) now handles interface …

Prepare release v5.15.0

---

src/rules/commentFormatRule.ts

Continuation of https://github.com/palantir/tslint/pull/197
JetBrains IDE screencast https://streamable.com/4sxnz
[enhancement] `comment-format` rule now whitelists `//region` comments generated by JetBrains IDE

comment-format: whitelist //region comments

---

src/rules/noParameterPropertiesRule.ts

- [x ] Documentation update
[documentation] `no-parameter-properties`: fix unclear rule description

no-parameter-properties: fix unclear rule description

---

package.json
src/formatters/codeFrameFormatter.ts
test/formatters/codeFrameFormatterTests.ts

[babel-code-frame](https://www.npmjs.com/package/babel-code-frame) is deprecated and future updates will be published under the babel npm organization as [@babel/code-frame](https://www.npmjs.com/package/@babel/code-frame).
Updated `babel-code-frame` v6.22.0 to `@babel/code-frame` v7.0.0
Updated `@types/babel-code-frame` v6.20.0 to `@types/babel__code-frame` v7.0.1
`chalk` now has types so we don't need to cast as any in the test.
The test used old code-frame behavior:
```
first failure (first-name)
> 1 | module CodeFrameModule {
2 |     export class CodeFrameClass {
3 |         private name: string;
4 | 
full failure (full-name)
> 1 | module CodeFrameModule {
2 |     export class CodeFrameClass {
3 |         private name: string;
4 | 
warning failure (warning-name)
> 1 | module …
```

[enhancement] Update babel-code-frame to @babel/code-frame

---

package.json

Update nyc from v10.2.0 to v13.3.0
The number of known vulnerabilities for tslint's dependencies drops from **29** to 3.
```
✔  17:26 ~/tslint [ update-nyc L | ✔  ] $ npm install nyc
+ nyc@10.3.2
updated 1 package and audited 812 packages in 3.634s
found 29 vulnerabilities (17 low, 9 moderate, 2 high, 1 critical)
run `npm audit fix` to fix them, or `npm audit` for details
✔  17:27 ~/tslint [ update-nyc L | ✚ 1 ] $ npm i nyc@latest
+ nyc@13.3.0
added 61 packages from 65 contributors, removed 86 packages, updated 67 packages, moved 1 package and audited 670 packages in 4.313s
found 3 vulnerabilities (1 low, 1 high, 1 critical)
run `npm audit fix` to fix them, or `npm audit` for details
✔  17:27 ~/tslint [ update-nyc L | ✚ 1 ] $ git diff
diff --git a/package.json b/package.json
index …
```

[enhancement] Update nyc from v10.2.0 to v13.3.0

---

docs/rules/index.md

An incorrect rule type selector in rules documentation page (docs/rules/index.md) was omitting the following rules:
* `align`
* `arrow-parens`
* `eofline`
* `import-spacing`
* `indent`
* `jsdoc-format`
* `linebreak-style`
* `max-line-length`
* `newline-before-return`
* `new-parens`
* `no-consecutive-blank-lines`
* `no-irregular-whitespace`
* `no-trailing-whitespace`
* `number-literal-format`
* `quotemark`
* `semicolon`
* `trailing-comma`
* `typedef-whitespace`
* `whitespace`

Fix typo in rule docs generation

---

src/configuration.ts
src/rules/noNullUndefinedUnionRule.ts
test/rules/no-null-undefined-union/test.ts.lint

[rule-change] Relax `no-null-undefined-union` rule.

Relax "no-null-undefined-union" rule.

---

src/rules/interfaceNameRule.ts
test/rules/interface-name/always-prefix/test.ts.lint

I stoped to use isLowerCase or isUpperCase to use a real regex. These functions was buggy with numbers.
I add a better support for prettier too.
[bugfix] `interface-name` now correctly handle numeric characters

Fix interface name rule

---

.prettierrc
tslint.json

Use prettierrc instead of a config in tslint.json
User with prettier have now a correct auto-formatting of the project

Add prettierrc

---

src/rules/code-examples/switchDefault.examples.ts

Last switch case does not need a break statement as the switch will already end after it. This way this example will also ensure following the rule switchFinalBreakRule which it does not at the moment.

Remove unnecessary break in switchDefault example

---

src/rules/interfaceNameRule.ts
test/rules/interface-name/always-prefix/test.ts.lint
test/rules/interface-name/never-prefix/test.ts.lint

More edge case for this rule.
Theses cases are considered valid in both `always`  and `never`.
IS
IIS3Foobar
IS3Foobar -> This one is fixed now
IISFoobar
ISFoobar
"[bugfix] `interface-name`"

Fix interfaceName rule

---

docs/develop/custom-rules/index.md
src/rules/radixRule.ts

This should have no functional impact, just fixing a typo in code and documentation
The parameter name is limited to the scope of the function in which it is used, and therefore it is not possible to have a side effect with this change. Please confirm my understanding.
[new-fixer]

fix identifer to identifier typo - note missing (i)

---

src/rules/noInferredEmptyObjectTypeRule.ts
test/rules/no-inferred-empty-object-type/test.ts.lint

As the generic parameters are inferred as `unknown` in newer TS versions (> 3.4.x), this rule no longer applies in those versions, and those places that would have previously thrown an error, as seen in the tests, no longer should throw as they are no longer inferred as `{}`.
TS above 3.4.x infers the types to `unknown` instead of `{}`, so the tests no longer apply.
[no-log]

[no-inferred-empty-object-type] Skip test in TS > 3.4.x

---

src/rules/restrictPlusOperandsRule.ts
test/rules/restrict-plus-operands/test.ts.lint

It can be difficult for users to find out why exactly they received the
"restrict-plus-operands" lint error. In particular, users often end up
with `any` types leaking into their code (e.g. in tests), and are then
puzzled why this triggers.
To fix, this change includes a textual representation of the type in the
error message, e.g.:
[Operands of '+' operation must either be both strings or both numbers, but found 5 + undefined[]]
The type representation isn't always super pretty (e.g. the
`undefined[]` bit above), but should still be helpful, and also matches
TS compiler's representation of these.
[enhancement] Improve error message for `restrict-plus-operands` rule.

Include actual types for restrict-plus-operands.

---

.circleci/config.yml
package.json
scripts/verifyCleanLockfile.sh
yarn.lock

Refactor CI config, require lockfile to be up to date

---

src/rules/quotemarkRule.ts
test/rules/quotemark/backtick/test.ts.fix
test/rules/quotemark/backtick/test.ts.lint
test/rules/quotemark/backtick/test<2.7.1.ts.fix
test/rules/quotemark/backtick/test<2.7.1.ts.lint
test/rules/quotemark/backtick/test>=2.7.1.ts.fix
test/rules/quotemark/backtick/test>=2.7.1.ts.lint

This edge cases were previously flagged when they should be ignored, as changing them breaks typescript. This commit makes it so they are ignored. It also organizes a little better, using functions instead of multi-layered conditionals (it was getting confusing).
I keep finding other edge cases that I previously missed. I *think* this is all of them now, but we shall see. Related to #4588.
See if y'all find any other edge cases.
[bugfix] Excuse more quotemark backtick edge cases

[quotemark] Excuse more backtick edge cases

---

package.json
yarn.lock

Another advisory was released for js-yaml: https://npmjs.com/advisories/813    
[enhancement] Update dependency js-yaml from ^3.13.0 to ^3.13.1

[enhancement] Update js-yaml from v3.13.0 to v3.13.1

---

docs/usage/third-party-tools/index.md

For now `vscode-tslint` plugin is deprecated. A link to the new official plugin is provided.

[enhancement] VSCode plugin link updated

---

src/rules/noUnusedVariableRule.ts

fixed "no-unused-variable" argument count, see linked issue

fixed "no-unused-variable" argument count

---

src/rules/unnecessaryConstructorRule.ts
test/rules/unnecessary-constructor/test.ts.fix
test/rules/unnecessary-constructor/test.ts.lint

Add a fixer for "unnecessary-constructor" rule.
Also don't flag constructors with decorated parameters since the parameter decorator can have side effects.
This was added in the initial commit of "unnecessary-constructor" rule but [removed later](https://github.com/palantir/tslint/pull/3647/commits/56ac48a9ebe6680a33c795091874b17a3126b862). What are the concerns?
I ran this fixer across Google's mono repo. The fixes produced are legit to me.

Add a fixer for "unnecessary-constructor" rule.

---

src/rules/noUseBeforeDeclareRule.ts

deprecate no-use-before-declare for TS 2.9+

Deprecate no-use-before-declare rule for typescript 2.9+

---

package.json
src/rules/noObjectLiteralTypeAssertionRule.ts
test/rules/no-object-literal-type-assertion/default/test.ts.lint
yarn.lock

These are not normal type assertions and asserting that literal objects
are immutable is a normal usage pattern.
Allow const assertions in no-object-literal-type-assertion. These are not equivalent to normal type assertions, and using them on literal objects is expected behavior.
[enhancement] Allow const assertions in no-object-literal-type-assertion

Allow const assertions in no-object-literal-type-assertion

---

src/rules/noInferredEmptyObjectTypeRule.ts
src/rules/quotemarkRule.ts
test/rules/quotemark/backtick/test.ts.fix
test/rules/quotemark/backtick/test.ts.lint

This commit makes quotemark backtick ignore use strict declarations, enum members, lookup types, and strings containing octal escape sequences.
See description. Just ignore the cases mentioned in the bug.
Make sure I captured all the variations of the said cases in the tests.
[bugfix] Quotemark backtrack now ignores enum members, use strict declarations, lookup types, and strings containing octal escape sequences.

[quotemark] Exclude some cases from backtick rule

---

src/tslintCli.ts

--quiet hide warnings instead of errors
CLI parameter describe
[no-log]

quiet describe typo

---

src/rules/noRedundantJsdocRule.ts
test/rules/no-redundant-jsdoc/test.ts.lint

```
The 'no-redundant-jsdoc' rule threw an error in 'some-file.ts':
Error: Unexpected tag kind: JSDocThisTag
```
This appears to be similar to #3413
- [ x ] New feature, bugfix, or enhancement
- [ x ] Includes tests
Adds `JSDocThisTag` to the redundant cases.
I appreciate this is my first contribution to this project so feel free to point me in the direction of any contribution guidelines that I've overlooked.
[bugfix] `no-redundant-jsdoc` no longer errors on `JSDocThisTag`

Fixes "no-redundant-jsdoc" exception on this tag

---

src/language/rule/rule.ts
src/rules/variableNameRule.ts
test/rules/no-null-undefined-union/test.ts.lint
test/rules/no-null-undefined-union/ts350.ts.lint
tslint-vscode.json

Related to #4677 
[documentation] Minor fix for `variable-name` rule metadata

Fix up variable-name rule metadata

---

README.md

This makes the entire block copy-pastable!
[no-log]

Add "cd tslint" to README quick start

---

CHANGELOG.md
package.json
scripts/generate-changelog.ts
src/linter.ts
test/rules/no-inferred-empty-object-type/test.ts.lint
tslint-vscode.json

- [bugfix] [`quotemark`](https://palantir.github.io/tslint/rules/quotemark/) backtic option now ignores enum members, use strict declarations, lookup types, and strings containing octal escape sequences. (#4693)
- [bugfix] [`no-redundant-jsdoc`](https://palantir.github.io/tslint/rules/no-redundant-jsdoc/) no longer errors on `JSDocThisTag` (#4690)
- [chore] Update devDependency mocha from v3.2.0 to v6.1.4 (#4669) (#4674)
- [chore] Update devDependency js-yaml from ^3.13.0 to ^3.13.1 (#4663)
- [chore] Update deprecated devDependency github to @octokit/rest (#4673)
- [chore] Update devDependency nyc from v13.3.0 to v14.1.1 (#4699)
- [deprecation] [`no-use-before-declare`](https://palantir.github.io/tslint/rules/no-use-before-declare/) rule for typescript >= 2.9.0 (#4695)
- [documentation] …

Prepare v5.17.0

---

CHANGELOG.md
package.json
src/linter.ts

Fixes #4106 
- [feature] New `--print-config` CLI flag (#4744)
- [bugfix] [`no-unnecessary-type-assertion`](https://palantir.github.io/tslint/rules/no-unnecessary-type-assertion/) no longer flags `x!` non-null assertions if `--strictNullChecks` is not enabled (#3724)
- [bugfix] [`quotemark`](https://palantir.github.io/tslint/rules/quotemark/) handles unbalanced quotes more gracefully without crashing (#4344)
- [docs] Add tslint-playground link to README and bug report template (#4150)
- [enhancement] [`no-magic-numbers`](https://palantir.github.io/tslint/rules/no-magic-numbers/) rule ignores arguments passed into default Number methods (#3668)
- [new-fixer] [`comment-format`](https://palantir.github.io/tslint/rules/comment-format/) (#3583)
- [new-rule-option] `"allow-trailing-lowercase"` …

Prepare release v5.18.0

---

src/configs/all.ts
src/configuration.ts
src/rules/completed-docs/exclusions.ts
src/rules/noForInRule.ts
src/rules/noImplicitDependenciesRule.ts
test/rules/no-for-in/test.ts.lint
test/rules/no-for-in/tslint.json

I have no idea what I'm doing, this is taken straight from the Microsoft-tslint-contrib repo, with some minor tweaks made. Help lol

Add noForIn rule

---

src/rules/noAsyncWithoutAwaitRule.ts
test/rules/no-async-without-await/test.ts.lint

Check for if `node.type` property exists when `node.body` is  `undefined`

no-async-without-await: check type property and add tests

---

src/rules/typedefRule.ts
test/rules/typedef/variable-declaration-ignore-function/test.ts.lint
test/rules/typedef/variable-declaration-ignore-function/tslint.json

Add new option for `typedef` rule. 
Ignores typedef requirement for vars for arrow and non arrow functions.
[new-rule-option] `typedef` new option: `variable-declaration-ignore-function`

[new-rule-option] Introduce new typedef rule option (variable-declaration-ignore-function)

---

src/rules/strictComparisonsRule.ts
test/rules/strict-comparisons/allow-object-equal-comparison/test.ts.lint
test/rules/strict-comparisons/allow-string-order-comparison/test.ts.lint
test/rules/strict-comparisons/default/test.ts.lint

check if `rightType` or `leftType` in `Binary Expression` contains `null` or `undefined`.

Fix strict comparison false positive

---

src/rules/awaitPromiseRule.ts

- ~[ ] Documentation update~
Allows the new `AsyncGenerator` type introduced in https://github.com/microsoft/TypeScript/pull/30790 as one of the hardcoded names for async iterables.
Is this the right approach? I think so, but 🤷‍♂ hard to tell with these kind-of-sort-of breaking changes.

Allowed new 'AsyncGenerator' name for await-promise async iterables

---

src/rules/noAngleBracketTypeAssertionRule.ts
test/rules/no-angle-bracket-type-assertion/test.ts.fix
test/rules/no-angle-bracket-type-assertion/test.ts.lint

check only for binary expression in the parent.

no-angle-bracket-type-assertion: check only for binary expression

---

src/rules/strictBooleanExpressionsRule.ts
test/rules/strict-boolean-expressions/default/test.ts.lint
test/rules/strict-boolean-expressions/ignore-rhs/test.ts.lint

check expression only if `left` node is not a `BooleanBinaryExpression`

4746: fix weird failures in strict-boolean-expressions for 'ignore-rhs' option

---

src/rules/arrayTypeRule.ts
test/rules/array-type/array-simple/test.ts.fix
test/rules/array-type/array-simple/test.ts.lint

`(T)` is now considered a simple type if `T` is a simple type.
[bugfix] Fix false positive for simple parenthesized array types with array-simple (#4844)

Fix false positive for simple parenthesized array types with array-simple (#4844)

---

src/rules/noUnnecessaryTypeAssertionRule.ts
test/rules/no-unnecessary-type-assertion/strict/test.ts.fix
test/rules/no-unnecessary-type-assertion/strict/test.ts.lint
test/rules/no-unnecessary-type-assertion/strict/tsconfig.json
test/rules/no-unnecessary-type-assertion/strict/tslint.json

This commit fixes #4840
Fixed simple bug. 
Nope.
[bugfix] fix `no-unnecessary-type-assertion` no error when `"strict": true` in compiler flags

Fix bug where the strict ts flag wasn't recognised correctly by `no-unnecessary-type-assertion`

---

src/rules/objectLiteralShorthandRule.ts
test/rules/object-literal-shorthand/never/test.ts.lint
test/rules/object-literal-shorthand/onlyMethods/test.ts.fix
test/rules/object-literal-shorthand/onlyMethods/test.ts.lint
test/rules/object-literal-shorthand/onlyMethods/tslint.json

Support granular configuration in `object-literal-shorthand`
[new-rule-option] `object-literal-shorthand` supports `{"property"?: "never", "method"?: "never"}` as config options

Support granular config in 'object-literal-shorthand'

---

src/rules/fileNameCasingRule.ts
test/rules/file-name-casing/complex/tslint.json
test/rules/file-name-casing/ignore/tslint.json

[bugfix] 'ignore' option for `file-name-casing` rule works correctly

fix(file-name-casing): ignore option works correctly

---

package.json
yarn.lock

Github/dependabot reported a high severity bug with `jsdiff`. The exact wording is
```
WS-2018-0590 More information
high severity
Vulnerable versions: < 3.5.0
Patched version: 3.5.0
A vulnerability was found in diff before v3.5.0, the affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS) attacks.
```
This diff bumps up the version to the latest available jsdiff 4.0.1. 
No
N/A

Upgrade diff to 4.0.1

---

CHANGELOG.md
package.json
src/linter.ts

- [bugfix] fix [`strict-boolean-expressions`](https://palantir.github.io/tslint/rules/strict-boolean-expressions/) false positive with `"ignore-rhs"` option (#4833)
- [bugfix] fix [`no-unnecessary-type-assertion`](https://palantir.github.io/tslint/rules/no-unnecessary-type-assertion/) no error when `"strict": true` in compiler flags (#4841)
- [bugfix] "ignore" option for [`file-name-casing`](https://palantir.github.io/tslint/rules/file-name-casing/) rule works correctly (#4848)
- [bugfix] fix [`array-type`](https://palantir.github.io/tslint/rules/array-type/) false positive for simple parenthesized types with "array-simple" option (#4844)
- [new-rule-option] [`object-literal-shorthand`](https://palantir.github.io/tslint/rules/object-literal-shorthand/) supports `{"property"?: "never", …

Prepare release v5.20.0

---

src/configs/all.ts

Comment out `no-use-before-declare"` from rules.

fix[config]: remove deprcated rules from tslint: all config

---

src/rules/returnUndefinedRule.ts

- ~[ ] Documentation update~
TypeScript no longer guarantees a .typeArguments member on the Type object, as they're apparently capable of being lazily-defined (?). Instead we're to use a `checker.getTypeArguments` method.
Once 3.7 is out of beta/RC we'll be able to upgrade our dev dependency to rely on it.

Used checker.getTypeArguments in return-undefined rule when possible

---

src/rules/orderedImportsRule.ts
test/rules/ordered-imports/case-insensitive-legacy/test.ts.fix
test/rules/ordered-imports/case-insensitive-legacy/test.ts.lint
test/rules/ordered-imports/case-insensitive-legacy/tslint.json
test/rules/ordered-imports/case-insensitive/test.ts.fix
test/rules/ordered-imports/case-insensitive/test.ts.lint

This makes it consistent with TypeScript's Organize Imports command
Fixes #4063
This makes the sorting consistent with what TypeScript's Organise Imports ordering does, see https://github.com/Microsoft/TypeScript/issues/25114
Nothing in particular.
[bugfix] Make `ordered-imports` consistent with TypeScript's Organise Imports ordering
[new-rule-option] `case-insensitive-legacy` for `ordered-imports` rule

Change normalisation of ordered-imports

---

package.json
src/rules/noRedundantJsdocRule.ts
test/rules/no-redundant-jsdoc/test.ts.lint
yarn.lock

Allows usage of JSDoc `@author` tag.
[bugfix] allow JSDoc `@author` tag

[bugfix] allow jsdoc author tag (#4849)

---

src/rules/typedefRule.ts
test/rules/typedef/all/test.ts.lint
test/rules/typedef/arrow-call-signature/test.ts.lint
test/rules/typedef/arrow-parameter/test.ts.lint

Typedef `arrow-call-signature` now return error for
```
someFunc(() => {});
```
Actually, with all typedef rules actives.
```
const A = () => {} // error (return type)
someFunc(() => {}); // no error
someFunc((n) => {}); // error (param type)
setTimeout(function() {}, 1000); // error (return type)
```
After the PR, error everywhere ; for consistency.
Here https://github.com/palantir/tslint/issues/2000#issuecomment-435629910, a suggestion is a `child-arrow-call-signature`. That's a possibility, but we have to (for consistency) add a `child-arrow-parameter` too, which is also a suggestion here https://github.com/palantir/tslint/issues/813.
We, then, have to decide before if we want also a `child-parameter` and a `child-call-signature`.
I can do it if you prefer. 
Personally I don't think …

Improve typedef for callback used as parameter

---

src/formatters/vsoFormatter.ts
test/formatters/vsoFormatterTests.ts

Updated the vso formatter to include the severity of the failure.
(Severity `warning` was hard-coded)
[enhancement] vso formatter now reports severity of rule failures

Add severity support for vso formatter

---

src/rules/importBlacklistRule.ts

Added examples in `optionExamples` and change `optionsDescription` to specify the requirement of an array of regular expression

4660-[import-blacklist]: Added examples and fix optionsDescription

---

docs/usage/cli/index.md
src/formatters/verboseFormatter.ts
src/linter.ts
src/runner.ts
src/tslintCli.ts
test/executable/executableTests.ts
test/runner/runnerTests.ts

Removes the `prose` formatter and its associated tests.
The `prose` formatter also printed details on file fixes, which was used in some tests. I ended up keeping it in and just deprioritizing it in the docs. It feels like changing the default formatter to `stylish` will serve the purpose of improving the general CLI output by default?
[api] Changed default formatter to stylish

Defaulted formatter to stylish

---

docs/develop/custom-rules/index.md

Documentation update to reflect

docs: update custom rule example 

---

src/rules/preferSwitchRule.ts
test/rules/prefer-switch/default/test.ts.lint
test/rules/prefer-switch/min-cases-2/test.ts.lint

Check if `elseStatement` is undefined
[enhancement]: `prefer-switch` is more lenient with `if` statements containing multiple OR conditions without any `else` clause

[prefer-switch]: Allow if-else statement with mulitple OR

---

CHANGELOG.md
package.json
src/linter.ts

- :fire: BREAKING CHANGES :fire:
- [api] Changed default formatter to stylish (#4872)
- [enhancement] Removed formatting and whitespace rules from `tslint:recommended` configuration (#4871)
- [enhancement] Removed pedantic rules from `tslint:recommended` configuration (#4312)
- [enhancement] `vso` formatter now reports severity of rule failures (#4286)
- [enhancement] [`typedef`](https://palantir.github.io/tslint/rules/typedef/) rule `arrow-call-signature` option is more consistent in reporting errors on lambdas and will flag more violations that were missed in the previous rule implementation (#4533)
- [bugfix] [`ordered-imports`](https://palantir.github.io/tslint/rules/ordered-imports/) is now consistent with TypeScript's Organise Imports ordering (#4064)
- [bugfix] …

Prepare release v6.0.0-beta0

---

src/linter.ts
test/executable/executableTests.ts

- ~~[ ] Documentation update~~
Add `path.resolve` when`fs.writeFileSync` called with temp file path.
Credits for the idea hot to fix the issue goes to @dhleong https://github.com/palantir/tslint/issues/4880#issue-509605076
Actually tests were failing on macOS Catalina before this fix.

fix: writeFileSync can not write to temp files on macOS 10.15

---

src/rules/fileHeaderRule.ts
test/rules/file-header/good-newline/test.ts.lint
test/rules/file-header/good-newline/tslint.json

Remove `null` check from `Regex` test
[bugfix] fix `enforce-trailing-newline` option in `file-header` rule

fix[file-header]: fix enforce-trailing-newline option

---

docs/develop/testing-rules/index.md

Add missing colon after `[error]` in `docs/develop/testing-rules/index.md`.
These changes simply maintain the uniformity of the documentation. :)

docs: add missing colon after `[error]`

---

src/language/utils.ts
src/rules/noUnnecessaryQualifierRule.ts

Moving it into just the file that uses it fixes the issue of it being exported in the public `.d.ts` files.
[bugfix] Internalized isPrivateIdentifier to fix TS<3.8 compiles

Internalized isPrivateIdentifier helper

---

package.json
src/rules/alignRule.ts
src/rules/noRedundantJsdocRule.ts
src/rules/oneLineRule.ts
yarn.lock

fix: add support for TypeScript 4.0

---

CHANGELOG.md
package.json
src/linter.ts

-   [bugfix] add support for TypeScript 4.0 peer dependency (#4943)

Prepare release v6.1.3
